/* Career progression consumes facts; it never chooses a match winner. */
(function(root,factory){const api=factory();if(typeof module==='object')module.exports=api;else root.PROGRESSION=api;})(typeof window==='object'?window:this,function(){
 'use strict';
 const clamp=(v,a=0,b=100)=>Math.max(a,Math.min(b,Number.isFinite(v)?v:0));
 const key=p=>p.name+'-'+p.tier+(p.tier==='钻'?'-'+p.cut:''),pair=(a,b)=>JSON.stringify([a,b].sort());
 const familiar=u=>100*Math.max(0,u||0)/(Math.max(0,u||0)+40);
 const weight=phase=>phase===7?3:[1,4].includes(phase)?2:1;
 function ensure(s,mapIds=[]){s.ledger??=[];s.mapRecords??=[];s.participation??=[];s.familiarity??={};s.rapport??={};s.mapKnowledge??={};s.growthReports??=[];s.mapCoach??={};s.mapLineup??={};for(const id of [...new Set([...mapIds,...Object.keys(s.mapKnowledge)])]){const prior=clamp(s.mapKnowledge[id]??50);s.mapCoach[id]??=prior;s.mapLineup[id]??=prior;s.mapKnowledge[id]=clamp(.6*s.mapCoach[id]+.4*s.mapLineup[id]);}s.progressionVersion=1;return s;}
 function syncMaps(s){for(const id of Object.keys(s.mapCoach))s.mapKnowledge[id]=clamp(.6*s.mapCoach[id]+.4*s.mapLineup[id]);}
 function members(s,cards){return s.roster.map(k=>{const p=cards.find(c=>key(c)===k);if(!p)throw Error('成长参赛卡不存在：'+k);return {key:k,playerId:p.playerId,team:p.team};});}
 function bond(s,ps){let same=0,rapport=0;for(let i=0;i<ps.length;i++)for(let j=i+1;j<ps.length;j++){same+=!!ps[i].team&&ps[i].team===ps[j].team;rapport+=clamp(s.rapport[pair(ps[i].playerId,ps[j].playerId)]||0);}return clamp(20+.15*ps.reduce((n,p)=>n+familiar(s.familiarity[p.playerId]),0)/5+2*same+.045*rapport);}
 function snapshot(s){return {team:{...s.team},coach:{...s.coach}};}
 function report(s,id,type,before,extra={}){const after=snapshot(s),delta=(a,b)=>Object.fromEntries(Object.keys(a).map(k=>[k,b[k]-a[k]]));const row={id,year:s.year,phase:s.phase,type,before,after,teamDelta:delta(before.team,after.team),coachDelta:delta(before.coach,after.coach),...extra};s.growthReports.push(row);s.growthReports=s.growthReports.slice(-24);return row;}
 function resetYear(s,ids){ensure(s,ids);for(const id of Object.keys(s.mapLineup))s.mapLineup[id]=50;syncMaps(s);s.growthReports=[];}
 function replace(s,retained,cards){ensure(s);for(const id of Object.keys(s.mapLineup))s.mapLineup[id]=clamp(50+retained/5*(s.mapLineup[id]-50));syncMaps(s);s.team.羁绊=bond(s,members(s,cards));}
 function recover(s,kind){const state=s.team.状态;if(kind==='half')s.team.状态=clamp(50+.75*(state-50));else if(kind==='map')s.team.状态=clamp(50+.5*(state-50));else if(kind==='match')s.team.状态=clamp(50+.25*(state-50));else if(kind==='timeout'&&state<50)s.team.状态=clamp(state+(50-state)*(.1+.002*s.coach.临场));}
 function round(s,win,cards,evidence={}){s.team.状态=clamp(50+.9*(s.team.状态-50)+(win?2:-2)+clamp(evidence.performance||0,-1,1));s.team.熟练=clamp(s.team.熟练+.04*(1-s.team.熟练/100));const ps=members(s,cards);for(let i=0;i<ps.length;i++)for(let j=i+1;j<ps.length;j++){const id=pair(ps[i].playerId,ps[j].playerId);s.rapport[id]=clamp((s.rapport[id]||0)+.03);}s.team.羁绊=bond(s,ps);}
 function beginMap(s,m,cards,context={}){ensure(s,[m.mapId]);if(m.progression)return m.progression;const ps=members(s,cards);m.progression={version:1,year:s.year,phase:s.phase,players:ps,coach:{...s.coach,...context.coach},before:snapshot(s),expected:clamp(context.expected??.5,0,1),standardExpected:context.standardExpected,plannedExpected:context.plannedExpected,kind:context.kind||'formal',roundsSettled:context.roundsSettled??0,legacy:!!context.legacy,windows:[]};return m.progression;}
 function window(s,m,kind,id){const p=m.progression;if(!p||p.windows.some(w=>w.id===id))return false;p.windows.push({id,kind,round:m.rounds.length});recover(s,kind);return true;}
 function settleMap(s,m,cards,id,{quick=false}={}){ensure(s,[m.mapId]);if(s.ledger.includes(id))return null;if(!Number.isInteger(m.home)||!Number.isInteger(m.away)||Math.min(m.home,m.away)<0||Math.max(m.home,m.away)<13||Math.abs(m.home-m.away)<2)throw Error('未完成的地图不能结算成长');const p=m.progression||beginMap(s,m,cards,{kind:quick?'quick':'formal'}),before=snapshot(s),win=m.home>m.away;if(quick){for(let i=p.roundsSettled;i<m.rounds.length;i++){round(s,m.rounds[i].win,cards);p.roundsSettled=i+1;if(i===11)window(s,m,'half',id+':half');}}
  const h=s.mapCoach[m.mapId],v=s.mapLineup[m.mapId];s.mapCoach[m.mapId]=clamp(h+2*((win?1:0)-p.expected));s.mapLineup[m.mapId]=clamp(v+(win?1.5:.8)*(1-v/100));syncMaps(s);
  const familiarGains={};for(const member of p.players){const gain=(1+(win?.25:0))*(.75+.005*p.coach.声望);s.familiarity[member.playerId]=(s.familiarity[member.playerId]||0)+gain;familiarGains[member.key]=gain;}
  const probs=m.rounds.map(r=>r.probability).filter(Number.isFinite),n=m.rounds.length;const observed=n?m.rounds.filter(r=>r.win).length/n:0;const expected=probs.length===n&&n?probs.reduce((a,b)=>a+b,0)/n:null;
  const tactical=!p.legacy&&Number.isFinite(p.plannedExpected)&&Number.isFinite(p.standardExpected)?clamp(50+100*(p.plannedExpected-p.standardExpected)):null;
  const clinical=!p.legacy&&expected!==null?clamp(50+100*(observed-expected)*n/(n+12)):null;
  recover(s,'map');s.team.羁绊=bond(s,members(s,cards));s.ledger.push(id);
  const record={id,year:s.year,phase:s.phase,mapId:m.mapId,home:m.home,away:m.away,win,players:p.players,roster:p.players.map(p=>p.key),roundCount:n,familiarGains,expected:p.expected,evaluation:{tactical,clinical},mapBefore:{coach:h,lineup:v,score:.6*h+.4*v},mapAfter:{coach:s.mapCoach[m.mapId],lineup:s.mapLineup[m.mapId],score:s.mapKnowledge[m.mapId]}};s.mapRecords.push(record);record.growth=report(s,id,'map',p.before||before,{mapId:m.mapId,mapDelta:record.mapAfter.score-record.mapBefore.score,familiarGains});return record;
 }
 function slow(current,target){return Number.isFinite(target)?clamp(current+clamp(.05*(target-current),-1,1)):current;}
 function settleMatch(s,cards,{id,matchId,kind,win,mapRecords}){if(s.ledger.includes(id))return null;const before=snapshot(s),maps=mapRecords||[],ps=maps.length?maps.at(-1).players:members(s,cards);const mean=field=>{const rows=maps.filter(r=>Number.isFinite(r.evaluation?.[field]));return rows.length?rows.reduce((n,r)=>n+r.evaluation[field]*Math.max(1,r.roundCount),0)/rows.reduce((n,r)=>n+Math.max(1,r.roundCount),0):null;};const evaluation={tactical:mean('tactical'),clinical:mean('clinical')};s.coach.战术=slow(s.coach.战术,evaluation.tactical);s.coach.临场=slow(s.coach.临场,evaluation.clinical);
  s.team.熟练=clamp(s.team.熟练+.3*(1-s.team.熟练/100));for(let i=0;i<ps.length;i++)for(let j=i+1;j<ps.length;j++){const k=pair(ps[i].playerId,ps[j].playerId);s.rapport[k]=clamp((s.rapport[k]||0)+.3);}recover(s,'match');s.team.羁绊=bond(s,members(s,cards));
  const record={id,matchId,year:s.year,phase:s.phase,kind,win,cards:[...new Set(maps.flatMap(r=>r.roster))],maps:maps.map(r=>({id:r.id,mapId:r.mapId,roster:r.roster,players:r.players,win:r.win,roundCount:r.roundCount})),evaluation};if(!maps.length)record.cards=ps.map(p=>p.key);s.participation.push(record);s.ledger.push(id);record.growth=report(s,id,'match',before,{evaluation});return record;
 }
 function settleEvent(s,{id,phase,rank,total,played,playoffs=false,currentPlayers}){if(s.ledger.includes(id))return null;const before=snapshot(s),records=s.participation.filter(r=>r.year===s.year&&r.phase===phase&&r.eventParticipation!==false),maps=played?records.flatMap(r=>r.maps||[]):[],counts=new Map();for(const map of maps)for(const p of map.players)counts.set(p.key,{...p,count:(counts.get(p.key)?.count||0)+1});const grade=rank===1?2:rank===2?1.5:playoffs?1:.5,familiarGains={};for(const p of counts.values()){const gain=weight(phase)*grade*p.count/maps.length;s.familiarity[p.playerId]=(s.familiarity[p.playerId]||0)+gain;familiarGains[p.key]=gain;}
  if(currentPlayers)s.team.羁绊=bond(s,currentPlayers);const score=played&&rank<=total?clamp(100*(total-rank)/Math.max(1,total-1)):null;if(score!==null)s.coach.声望=clamp(s.coach.声望+clamp(.1*(score-s.coach.声望),-4,4));s.ledger.push(id);const row=report(s,id,'event',before,{evaluation:score,weight:weight(phase),familiarGains,participants:[...counts.keys()]});return row;
 }
 function settleYear(s,id){if(s.ledger.includes(id))return null;const before=snapshot(s),rows=s.stageRecords.filter(r=>Number.isFinite(r.growth?.evaluation)),score=rows.length?rows.reduce((n,r)=>n+r.growth.evaluation*weight(r.phase),0)/rows.reduce((n,r)=>n+weight(r.phase),0):null;if(score!==null)s.coach.声望=clamp(s.coach.声望+clamp(.1*(score-s.coach.声望),-4,4));s.ledger.push(id);return report(s,id,'year',before,{evaluation:score});}
 return {clamp,key,pair,familiar,ensure,members,bond,snapshot,resetYear,replace,recover,round,beginMap,window,settleMap,settleMatch,settleEvent,settleYear};
});
