(function(root,factory){const api=typeof module==='object'?factory(require('./tournament'),require('./round-outcome'),require('./team-style'),require('./map-veto'),require('./stage-feedback'),require('./content-defaults')):factory(root.TOURNAMENT,root.ROUND_OUTCOME,root.TEAM_STYLE,root.MAP_VETO,root.STAGE_FEEDBACK,root.CONTENT_DEFAULTS);if(typeof module==='object')module.exports=api;else root.SEASON_2026=api;})(typeof window==='object'?window:this,function(T,O,H,V,J,C){
 'use strict';
 const regions=['CN','AMER','EMEA','PAC'];
 const kickoffByes={AMER:['G2','NRG','SEN','MIBR'],EMEA:['FNC','GX','TH','TL'],PAC:['PRX','T1','RRQ','KRX']};
 const pointTables={0:[4,3,2,1],1:[6,4,3,2,1,1],3:[6,4,3,2],4:[8,6,5,4,3,3],6:[8,6,5,4]};
 const sources={"verifiedAt":"2026-10-05","rulebook":"https://cdn.sanity.io/files/dsfx7636/news_live/f600a428dbcb54cff5814750f4c4be2b699d7934.pdf","handbook":"https://valorantesports.com/en-US/season/115571062868511862/handbook/115571062868708471","cnKickoff":"https://www.vlr.gg/event/2685/vct-2026-china-kickoff/main-event","cnStage1":"https://valorantesports.com/en-US/tournament/115577067094183289/overview","cnStage1Seeding":"https://valorantesports.com/en-US/tournament/115577067094183289/stage/115984036205766731","cnStage2":"https://valorantesports.com/zh-TW/tournament/115581244954153335/overview","cnStage2Seeding":"https://valorantesports.com/zh-TW/tournament/115581244954153335/stage/115984205117785043","stage1Draw":"https://www.youtube.com/watch?v=MyKyqJnepOc","stage2Draw":"https://www.youtube.com/watch?v=RqUkiJpe1gg","championsDraw":"https://www.youtube.com/watch?v=eX0_2xKnu3E","championsFormat":"https://valorantesports.com/en-US/news/champions-shanghai-everything-you-need-to-know","pacificFormat":"https://valorantesports.com/en-PH/news/vct-pacific-2026-season-primer","americasStage2":"https://valorantesports.com/en-US/news/vct-americas-2026-stage-2-everything-you-need-to-know","emeaStage2":"https://valorantesports.com/en-GB/news/2026-vct-emea-stage-2","americasPlayinDiagram":"https://cmsassets.rgpub.io/sanity/images/dsfx7636/news_live/0edc3db3449e31f1e05e8b82eecb71f64a649fd6-1920x1080.jpg","emeaPlayinDiagram":"https://cmsassets.rgpub.io/sanity/images/dsfx7636/news_live/64b3d5bde163af0d944b9de8fb2199968c8d2e7b-1920x1080.png","championsPlayoffEvidence":"https://www.youtube.com/watch?v=qpJf2QdhtiM"};
 function legacyCreate(seed,rosters,cards,club){const teams=rosters.map(t=>({...t,id:t.teamId,players:t.players.map(p=>cards.find(c=>c.cardId===p.cardId)).filter(Boolean),missingPlayers:t.players.filter(p=>!cards.some(c=>c.cardId===p.cardId)).map(p=>p.name),team:{羁绊:40,状态:50,熟练:50},coach:{战术:50,临场:50,声望:50}}));for(const region of regions.filter(r=>r!=='CN'))for(let i=0;i<4;i++)teams.push({id:({AMER:['FX','BST','M80','2G'],EMEA:['EP','FF','JL','SGE'],PAC:['SP','XIP','ONG','QTD']})[region][i],teamId:({AMER:['FX','BST','M80','2G'],EMEA:['EP','FF','JL','SGE'],PAC:['SP','XIP','ONG','QTD']})[region][i],region,entryOnly:true,players:[],neutralPrior:65,contentStatus:'入围席位：阵容数据待补齐',team:{羁绊:40,状态:50,熟练:50},coach:{战术:50,临场:50,声望:50}});return {version:'2026-season-2',simulationPolicy:{homeRegion:'CN',otherRegional:'numeric-series',international:'round-model'},seed:String(seed),club,teams,stages:{},points:Object.fromEntries(teams.map(t=>[t.id,0])),qualification:{},dataGaps:teams.filter(t=>t.missingPlayers?.length||t.contentStatus).map(t=>({id:t.id,missing:t.missingPlayers||[],status:t.contentStatus||'卡库缺失'})),sources};}
 function ids(ctx,region,entry=false){return ctx.teams.filter(t=>t.region===region&&!!t.entryOnly===entry).map(t=>t.id);}
 const flatten=placements=>placements.flat();
 function groups(seeds){const a=[],b=[];seeds.forEach((id,i)=>([0,3].includes(i%4)?a:b).push(id));return [a,b];}
 function rank(result,id){let offset=1;for(const group of result?.placements||[]){if(group.includes(id))return offset;offset+=group.length;}return 999;}
 const currentRules=ctx=>ctx.version==='2026-season-2';
 // Every random stream is scoped to a draw, independent of match simulation.
 function pairedGroups(order,rng){const groups=[[],[]],pools=[];for(let i=0;i<order.length;i+=2){const pool=order.slice(i,i+2),pair=shuffle(pool,rng);pools.push(pool);groups[0].push(pair[0]);groups[1].push(pair[1]);}return {kind:'kickoff-pots',pools,groups};}
 function stageGroups(ctx,phase,region){const rng=O.random(ctx.seed+':groups:'+phase+':'+region);if(phase===2)return pairedGroups(flatten(ctx.stages[0].regions[region].placements),rng);
 const first=ctx.stages[2].regions[region],baseGroups=first.tables.map(table=>table.map(r=>r.id));
 // Re-seed within the old groups using the final Stage 1 performance,
 // including playoffs; tied finishes retain the original group standing.
 const playoffs=ctx.stages[3]?.regions[region];for(const group of baseGroups)group.sort((a,b)=>rank(playoffs,a)-rank(playoffs,b));
 const groups=baseGroups.map(g=>[...g]),swaps=[];for(const pair of [[5,6],[3,4],[1,2]]){const place=pair[Math.floor(rng()*2)];swaps.push(place);[groups[0][place-1],groups[1][place-1]]=[groups[1][place-1],groups[0][place-1]];}return {kind:'rank-swap',basis:'stage1-playoff-within-original-group',baseGroups,swaps,groups};}
 function deciders(event,count,play,prefix,rng){event.seedingGames=[];for(let i=0;i<count;i++){const a=event.tables[0][i].id,b=event.tables[1][i].id,node={id:prefix+'SEED:'+i,a,b,bestOf:3,higherSeed:rng()<.5?a:b,label:'种子排位赛'},r=play(node);T.validate(r,a,b,3);event.seedingGames.push({...node,...r});event.seeds.splice(i*2,2,r.winner,r.loser);}event.games.push(...event.seedingGames);}
 function permutations(items){if(!items.length)return [[]];return items.flatMap((item,i)=>permutations(items.filter((_,j)=>j!==i)).map(rest=>[item,...rest]));}
 function championsGroups(ctx,qualified){const pools=[0,1,2,3].map(i=>qualified.map(list=>list[i])),rng=O.random(ctx.seed+':champions:groups'),region=id=>ctx.teams.find(t=>t.id===id).region,first=shuffle(pools[0],rng),valid=[];
 function fill(rows){if(rows.length===4){valid.push(rows);return;}for(const row of permutations(pools[rows.length]))if(row.every((id,g)=>rows.every(previous=>region(previous[g])!==region(id))))fill([...rows,row]);}fill([first]);if(!valid.length)throw Error('冠军赛分组无合法解');const rows=valid[Math.floor(rng()*valid.length)];return {kind:'regional-seed-pots',pools,groups:[0,1,2,3].map(i=>rows.map(row=>row[i]))};}
 function championsPlayoffs(ctx,gsl){const winners=gsl.qualified.filter((_,i)=>i%2===0),runners=gsl.qualified.filter((_,i)=>i%2===1),group=id=>Math.floor(gsl.qualified.indexOf(id)/2),rng=O.random(ctx.seed+':champions:playoffs'),first=shuffle(winners,rng),valid=[];
 for(const opponents of permutations(runners)){if(opponents.some((id,i)=>group(id)===group(first[i])))continue;const halves=Object.fromEntries(first.map((id,i)=>[group(id),i<2?0:1]));if(opponents.some((id,i)=>halves[group(id)]===(i<2?0:1)))continue;valid.push(opponents);}if(!valid.length)throw Error('冠军赛淘汰赛无合法解');const second=valid[Math.floor(rng()*valid.length)],seeds=new Array(8);[0,3,1,2].forEach((slot,i)=>{seeds[slot]=first[i];seeds[[7,4,6,5][i]]=second[i];});return {kind:'group-winner-vs-runner',seeds,pairs:first.map((id,i)=>[id,second[i]]),sameGroupOppositeHalves:true};}
 function genericPlayin(t,entrants,play,prefix){const all=[...t,...entrants],n=[];for(let i=0;i<4;i++)n.push(['U0'+i,all[4+i],all[8+i]]);for(let i=0;i<4;i++)n.push(['U1'+i,all[i],T.w('U0'+i)]);n.push(['U2a',T.w('U10'),T.w('U11')],['U2b',T.w('U12'),T.w('U13')],['L0a',T.l('U00'),T.l('U01')],['L0b',T.l('U02'),T.l('U03')],['L1a',T.l('U10'),T.w('L0b')],['L1b',T.l('U11'),T.w('L0a')],['L2a',T.l('U12'),T.w('L1a')],['L2b',T.l('U13'),T.w('L1b')],['L3a',T.l('U2a'),T.w('L2a')],['L3b',T.l('U2b'),T.w('L2b')],['UF',T.w('U2a'),T.w('U2b')],['LF',T.w('L3a'),T.w('L3b')]);const out=T.graph(n,all,play,prefix),r=out.results;return {...out,qualified:[r.UF.winner,r.UF.loser,r.LF.winner,r.LF.loser],eliminated:[r.L3a.loser,r.L3b.loser,r.L2a.loser,r.L2b.loser,r.L1a.loser,r.L1b.loser,r.L0a.loser,r.L0b.loser]};}
 // Official Americas/EMEA play-in diagrams stop at four qualifiers; they do
 // not play artificial upper/lower finals. Pacific uses the same verified
 // bye/elimination constraints; its exact slot diagram is still provisional.
 function regionalPlayin(t,entrants,play,prefix,region,rng){const opponents=shuffle(entrants,rng),round2=region==='EMEA'?[t[0],t[3],t[2],t[1]]:[t[0],t[3],t[1],t[2]],n=[];
 [t[7],t[4],t[6],t[5]].forEach((id,i)=>n.push(['U0'+i,id,opponents[i]]));round2.forEach((id,i)=>n.push(['U1'+i,id,T.w('U0'+i)]));
 n.push(['L1a',T.l('U00'),T.l('U13')],['L1b',T.l('U01'),T.l('U12')],['L1c',T.l('U02'),T.l('U11')],['L1d',T.l('U03'),T.l('U10')],['L2a',T.w('L1a'),T.w('L1b')],['L2b',T.w('L1c'),T.w('L1d')],['U2a',T.w('U10'),T.w('U11')],['U2b',T.w('U12'),T.w('U13')],['L3a',T.l('U2a'),T.w('L2a')],['L3b',T.l('U2b'),T.w('L2b')]);
 const out=T.graph(n,[...t,...opponents],play,prefix),r=out.results,upper=[r.U2a.winner,r.U2b.winner],lower=[r.L3a.winner,r.L3b.winner];return {...out,qualified:[...shuffle(upper,rng),...shuffle(lower,rng)],eliminated:[r.L3a.loser,r.L3b.loser,r.L2a.loser,r.L2b.loser,r.L1a.loser,r.L1b.loser,r.L1c.loser,r.L1d.loser],draw:{kind:'challenger-slots',opponents,qualifierPools:[upper,lower],slotBasis:region==='PAC'?'public-constraints-provisional':'official-diagram'}};
 }
 // Regional winners choose from the actual Swiss survivors in a seeded draw
 // order. AI seeks the weakest available opponent; the player's automatic
 // delegate follows the agreed closest-strength preference without another UI step.
 function mastersDraw(ctx,direct,survivors,phase){if(ctx.playoffDrafts?.[phase])return ctx.playoffDrafts[phase];const order=shuffle(direct,O.random(ctx.seed+':draft:'+phase)),available=shuffle(survivors,O.random(ctx.seed+':survivors:'+phase)),seeds=new Array(8),draft=[];const strength=id=>O.strength(ctx.teams.find(t=>t.id===id));order.forEach((id,i)=>{available.sort((a,b)=>id===ctx.club?Math.abs(strength(id)-strength(a))-Math.abs(strength(id)-strength(b)):strength(a)-strength(b));const constraints=ctx.draftConstraints?.[phase]||{},forced=constraints[id],reserved=new Set(Object.entries(constraints).filter(([team])=>team!==id).map(([,opponent])=>opponent)),pick=forced?available.indexOf(forced):available.findIndex(t=>!reserved.has(t));if(pick<0)throw Error('已确认的大师赛对阵无法恢复');const opponent=available.splice(pick,1)[0],slot=[0,3,1,2][i],opponentSlot=[7,4,6,5][i];seeds[slot]=id;seeds[opponentSlot]=opponent;draft.push({order:i+1,team:id,opponent});});const result={seeds,draft};if(ctx.playoffDrafts)ctx.playoffDrafts[phase]=result;return result;}
 function runStage(ctx,phase,play){const out={phase,regions:{},games:[],placements:[]};const add=(region,event)=>{out.regions[region]=event;out.games.push(...event.games);};const prev=i=>ctx.stages[i];
  if(phase===0){for(const region of regions){let t=ids(ctx,region);if(t.length!==12)throw Error('赛区队伍数不正确：'+region);if(region==='CN'){const order=['BLG','DRG','XLG','EDG','AG','NOVA','JDG','TEC','TE','WOL','FPX','TYL'];t=order;}else{const rng=O.random(ctx.seed+':draw:'+region),byes=kickoffByes[region];if(byes.some(id=>!t.includes(id)))throw Error('启点赛轮空名单缺失：'+region);t=[...shuffle(byes,rng),...shuffle(t.filter(id=>!byes.includes(id)),rng)];}add(region,T.kickoff(t,play,`0:${region}:`));}}
  else if(phase===2||phase===5){for(const region of regions){let draw;if(currentRules(ctx))draw=stageGroups(ctx,phase,region);else{const prior=phase===2?flatten(prev(0).regions[region].placements):prev(2).regions[region].seeds;draw={groups:groups(phase===5?shuffle(prior,O.random(ctx.seed+':stage2:'+region)):prior)};}const event=T.regular(draw.groups,play,phase+':'+region+':');if(currentRules(ctx)){event.draw=draw;if(region==='CN')deciders(event,phase===2?4:6,play,phase+':'+region+':',O.random(ctx.seed+':deciders:'+phase));}if(phase===5){event.direct=event.seeds.slice(0,4);event.playin=region==='CN'?T.cnPlayin(event.seeds.slice(4),ids(ctx,region,true),play,'5:'+region+':PI:'):(currentRules(ctx)?regionalPlayin(event.seeds.slice(4),ids(ctx,region,true),play,'5:'+region+':PI:',region,O.random(ctx.seed+':playin:'+region)):genericPlayin(event.seeds.slice(4),ids(ctx,region,true),play,'5:'+region+':PI:'));event.games.push(...event.playin.games);}add(region,event);}}
  else if(phase===3||phase===6){for(const region of regions){const regular=prev(phase===3?2:5).regions[region],seeds=phase===3?regular.seeds.slice(0,8):[...regular.direct,...regular.playin.qualified];add(region,T.double(seeds,play,`${phase}:${region}:`,region!=='CN'));}}
  else if(phase===1||phase===4){const prior=prev(phase===1?0:3),direct=regions.map(region=>flatten(prior.regions[region].placements)[0]),swiss=regions.flatMap(region=>flatten(prior.regions[region].placements).slice(1,3)),metadata=Object.fromEntries(regions.flatMap(region=>flatten(prior.regions[region].placements).slice(1,3).map((id,i)=>[id,{region,seed:i+2}])));out.swiss=T.swiss(shuffle(swiss,O.random(ctx.seed+':world:'+phase)),play,`${phase}:world:`,(a,b)=>metadata[a].region!==metadata[b].region&&metadata[a].seed!==metadata[b].seed,currentRules(ctx)?{random:key=>O.random(ctx.seed+':swiss:'+phase+':'+key),higherSeed:(a,b,round)=>round===0?(metadata[a].seed<metadata[b].seed?a:b):null}:{});const draw=mastersDraw(ctx,direct,out.swiss.qualified,phase);out.playoffDraft=draw.draft;const playoff=T.double(draw.seeds,play,`${phase}:world:PO:`);out.games.push(...out.swiss.games,...playoff.games);out.placements=[...playoff.placements,out.swiss.eliminated.filter(t=>out.swiss.records[t].w===1),out.swiss.eliminated.filter(t=>out.swiss.records[t].w===0)];out.participants=[...direct,...swiss];}
  else if(phase===7){const qualificationTies=new Map();for(const region of regions)for(const row of pointStandings(ctx,region))for(const g of row.tieGames||[])qualificationTies.set(g.id,g);for(const game of qualificationTies.values()){const r=play(game);out.games.push({...game,...r});}const qualified=regions.map(region=>{const direct=flatten(prev(6).regions[region].placements).slice(0,2);return [...direct,...pointStandings(ctx,region).filter(t=>!direct.includes(t.id)).slice(0,2).map(t=>t.id)];});const groupDraw=currentRules(ctx)?championsGroups(ctx,qualified):{groups:[0,1,2,3].map(i=>regions.map((_,r)=>qualified[r][(i+r)%4]))};if(currentRules(ctx))out.groupDraw=groupDraw;out.gsl=T.gsl(groupDraw.groups,play,'7:world:');const playoffDraw=currentRules(ctx)?championsPlayoffs(ctx,out.gsl):{seeds:out.gsl.qualified};if(currentRules(ctx))out.playoffDraw=playoffDraw;const playoff=T.double(playoffDraw.seeds,play,'7:world:PO:');out.games.push(...out.gsl.games,...playoff.games);out.placements=[...playoff.placements,out.gsl.third,out.gsl.fourth];out.participants=qualified.flat();}
  else throw Error('未知阶段');return out;
 }
 function shuffle(list,rng){const a=[...list];for(let i=a.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
 function simulate(ctx,node,maps){const a=J?J.team(ctx,ctx.teams.find(t=>t.id===node.a)):ctx.teams.find(t=>t.id===node.a),b=J?J.team(ctx,ctx.teams.find(t=>t.id===node.b)):ctx.teams.find(t=>t.id===node.b);const result=O.series(ctx.seed+':'+node.id,a,b,node.bestOf,node.label==='同分加赛'?[ctx.activeMaps?.[0]||maps[0]||'ascent']:seriesMaps(ctx,node,maps));const foreignRegional=a.region===b.region&&a.region!=='CN'&&!node.id.includes(':world:');result.simulationMode=foreignRegional?'regional-numeric':'round-model';if(foreignRegional)for(const m of result.maps)delete m.rounds;return result;}
 function legacyPointStandings(ctx,region){if(ctx.qualificationStandings?.[region])return ctx.qualificationStandings[region];const idsInRegion=ids(ctx,region),positions=[6,4,3,1,0],regularGames=[2,5].flatMap(i=>ctx.stages[i]?.regions[region]?.games.filter(g=>g.label==='常规赛')||[]);const rows=idsInRegion.map(id=>({id,points:ctx.points[id]||0,places:positions.map(i=>rank(ctx.stages[i]?.regions?.[region]||ctx.stages[i],id)),...T.metrics(id,regularGames)}));const compare=(a,b)=>{if(a.points!==b.points)return b.points-a.points;for(let i=0;i<a.places.length;i++)if(a.places[i]!==b.places[i])return a.places[i]-b.places[i];return b.wins-a.wins||b.mapDifference-a.mapDifference||b.roundDifference-a.roundDifference;};rows.sort(compare);for(let i=0;i<rows.length;){let j=i+1;while(j<rows.length&&compare(rows[i],rows[j])===0)j++;const group=rows.slice(i,j);const allGames=Object.values(ctx.stages).flatMap(s=>s.games),headGames=allGames.filter(g=>group.some(t=>t.id===g.a)&&group.some(t=>t.id===g.b));let unresolved=true;if(group.length===2){const a=T.metrics(group[0].id,headGames),b=T.metrics(group[1].id,headGames),c=b.wins-a.wins||b.mapDifference-a.mapDifference||b.roundDifference-a.roundDifference;if(c){group.sort((x,y)=>x.id===a.id?c:-c);unresolved=false;}}if(group.length>1&&unresolved&&ctx.stages[6]){const fallback=[];const tiePlay=node=>{const r=O.series(ctx.seed+':'+node.id,ctx.teams.find(t=>t.id===node.a),ctx.teams.find(t=>t.id===node.b),1,[ctx.activeMaps?.[0]||'ascent']);fallback.push({...node,...r});return r;};const ranked=T.standings(group.map(t=>t.id),[],tiePlay,'points:'+region+':');group.sort((a,b)=>ranked.findIndex(t=>t.id===a.id)-ranked.findIndex(t=>t.id===b.id));group.forEach(r=>{r.tieMethod='BO1 同分加赛（后备游戏规则）';r.tieGames=fallback;});}rows.splice(i,j-i,...group);i=j;}if(ctx.qualificationStandings)ctx.qualificationStandings[region]=rows;return rows;}
 function leagueValues(ctx,phase,region,tied){const playoffs=ctx.stages[phase]?.regions[region],regular=ctx.stages[phase===3?2:5]?.regions[region],values=new Map();for(const id of tied){let place=rank(playoffs,id);if(place===999&&phase===6){const eliminated=regular?.playin?.eliminated||[];const i=eliminated.indexOf(id);if(i>=0)place=9+Math.floor(i/2)*2;}values.set(id,place);}
 // Resolve same finishing tier with group standing only when every remaining
 // team in that tier belongs to the same group; never compare unrelated groups.
 for(const place of new Set(values.values())){const subset=tied.filter(id=>values.get(id)===place);if(subset.length<2)continue;const table=regular?.tables?.find(t=>subset.every(id=>t.some(r=>r.id===id)));if(table)for(const id of subset)values.set(id,place+table.findIndex(r=>r.id===id)/100);}return values;}
 function pointStandings(ctx,region){if(!currentRules(ctx))return legacyPointStandings(ctx,region);if(ctx.qualificationStandings?.[region])return ctx.qualificationStandings[region];const regularGames=[2,5].flatMap(i=>ctx.stages[i]?.regions[region]?.games.filter(g=>g.label==='常规赛')||[]),allGames=Object.values(ctx.stages).flatMap(s=>s.games||[]),base=ids(ctx,region).map(id=>({id,points:ctx.points[id]||0,places:[6,4,3,1,0].map(i=>rank(ctx.stages[i]?.regions?.[region]||ctx.stages[i],id)),...T.metrics(id,regularGames)})),rows=new Map(base.map(r=>[r.id,r]));
 const criteria=['积分','第二赛段名次','第二次大师赛名次','第一赛段名次','第一次大师赛名次','启点赛名次','年度常规赛胜场','年度常规赛地图差','年度常规赛回合差','相互交手胜场','相互交手地图差','相互交手回合差'];
 function resolve(list,index=0){if(list.length<2)return list;let value;if(index===0)value=id=>-rows.get(id).points;else if(index===1||index===3){const values=leagueValues(ctx,index===1?6:3,region,list);value=id=>values.get(id);}else if([2,4,5].includes(index)){const event=ctx.stages[{2:4,4:1,5:0}[index]],r=event?.regions?.[region]||event;value=id=>rank(r,id);}else if(index<9)value=id=>-rows.get(id)[['wins','mapDifference','roundDifference'][index-6]];else if(index<12){if(list.length>2)return resolve(list,12);const head=allGames.filter(g=>list.includes(g.a)&&list.includes(g.b));value=id=>-T.metrics(id,head)[['wins','mapDifference','roundDifference'][index-9]];}else{if(!ctx.stages[6])return list;const tieGames=[],ranked=T.standings(list,[],node=>{const result=O.series(ctx.seed+':'+node.id,ctx.teams.find(t=>t.id===node.a),ctx.teams.find(t=>t.id===node.b),1,[ctx.activeMaps?.[0]||'ascent']);tieGames.push({...node,...result});return result;},'points:'+region+':');for(const id of list){rows.get(id).tieMethod='BO1 同分加赛（后备游戏规则）';rows.get(id).tieGames=tieGames;}return ranked.map(r=>r.id);}
 const groups=new Map();for(const id of list){const v=value(id);if(!groups.has(v))groups.set(v,[]);groups.get(v).push(id);}if(groups.size===1)return resolve(list,index+1);for(const ids of groups.values())for(const id of ids)(rows.get(id).tieCriteria||=[]).push(criteria[index]);return [...groups.entries()].sort((a,b)=>a[0]-b[0]).flatMap(([,ids])=>resolve(ids,0));}
 const result=resolve(base.map(r=>r.id)).map((id,i)=>({...rows.get(id),place:i+1}));if(ctx.qualificationStandings)ctx.qualificationStandings[region]=result;return result;}
 function commitStage(ctx,phase,result){if(ctx.stages[phase])return;if(ctx.styleVersion)for(const game of result.games)settleTeamResult(ctx,game,game);ctx.stages[phase]=result;const award=(event)=>{let place=1;for(const group of event.placements||[]){for(const id of group)ctx.points[id]=(ctx.points[id]||0)+(pointTables[phase]?.[place-1]||0);place+=group.length;}};if([2,5].includes(phase)){for(const g of result.games.filter(g=>g.label==='常规赛'))ctx.points[g.winner]=(ctx.points[g.winner]||0)+1;}else if(result.regions.CN){Object.values(result.regions).forEach(award);}else award(result);}
 function findFeatured(ctx,phase,maps){const preview=runStage(ctx,phase,node=>simulate(ctx,node,maps)),own=ctx.teams.find(t=>t.id===ctx.club),candidates=preview.games.filter(g=>(g.a===ctx.club||g.b===ctx.club)&&!g.grandFinal&&g.label!=='同分加赛'&&g.label!=='种子排位赛');candidates.sort((a,b)=>Math.abs(O.strength(own)-O.strength(ctx.teams.find(t=>t.id===(a.a===ctx.club?a.b:a.a))))-Math.abs(O.strength(own)-O.strength(ctx.teams.find(t=>t.id===(b.a===ctx.club?b.b:b.a)))));return candidates[0]?.id||null;}
 function remainingFeatured(ctx,session,maps){const forecast=runStage(ctx,session.phase,node=>{const saved=session.committed[node.id];if(saved){if(saved.node.a!==node.a||saved.node.b!==node.b)throw Error('正式节点预测与已提交签表不一致');return saved.result;}if(![1,4,7].includes(session.phase)&&ctx.teams.find(t=>t.id===node.a).region!==ctx.teams.find(t=>t.id===ctx.club).region){const score=(node.bestOf+1)/2;return {scoreA:score,scoreB:0,winner:node.a,loser:node.b,bestOf:node.bestOf,maps:[]};}return simulate(ctx,node,maps);}),own=ctx.teams.find(t=>t.id===ctx.club);return forecast.games.filter(g=>!session.committed[g.id]&&(g.a===ctx.club||g.b===ctx.club)&&!g.grandFinal&&g.label!=='同分加赛'&&g.label!=='种子排位赛').sort((a,b)=>Math.abs(O.strength(own)-O.strength(ctx.teams.find(t=>t.id===(a.a===ctx.club?a.b:a.a))))-Math.abs(O.strength(own)-O.strength(ctx.teams.find(t=>t.id===(b.a===ctx.club?b.b:b.a)))));}
 function prepare(ctx,phase,maps){J?.reset(ctx,phase);ctx.activeMaps=[...maps];return {phase,featuredId:findFeatured(ctx,phase,maps),committed:{},pending:null,complete:false};}
 function progress(ctx,session,maps){const STOP={},constraints={};for(const node of [...Object.values(session.committed).map(item=>item.node),session.pending].filter(Boolean))if([1,4].includes(session.phase)&&/:world:PO:U1[a-d]$/.test(node.id))(constraints[session.phase]||={})[node.a]=node.b;try{const result=runStage({...ctx,draftConstraints:constraints,playoffDrafts:session.playoffDrafts||=( {} ),...(session.phase===7?{qualificationStandings:session.qualificationStandings||={}}:{})},session.phase,node=>{if(session.committed[node.id]){const prior=session.committed[node.id];if(prior.node.a!==node.a||prior.node.b!==node.b)throw Error("已提交赛果与当前对阵不一致："+node.id+" "+prior.node.a+"/"+prior.node.b+" -> "+node.a+"/"+node.b);return prior.result;}const own=node.a===ctx.club||node.b===ctx.club;if(own&&ctx.matchSelectionVersion==='reachable-1'&&!Object.values(session.committed).some(i=>i.kind==='formal')){const eventCtx={...ctx,draftConstraints:constraints,playoffDrafts:session.playoffDrafts,...(session.phase===7?{qualificationStandings:session.qualificationStandings}:{})},remaining=remainingFeatured(eventCtx,session,maps);if(!remaining.some(g=>g.id===session.featuredId))session.featuredId=remaining[0]?.id||node.id;}if(own&&(node.id===session.featuredId||node.grandFinal)){session.pending={...node,playedBestOf:node.grandFinal?5:3,opponent:node.a===ctx.club?node.b:node.a};throw STOP;}const result=simulate(ctx,node,maps);session.committed[node.id]={node,result,kind:'quick'};settleTeamResult(ctx,node,result);return result;});session.complete=true;session.pending=null;commitStage(ctx,session.phase,result);if(session.phase===7)ctx.qualificationStandings=session.qualificationStandings;return result;}catch(e){if(e!==STOP)throw e;return null;}}
 function submit(session,result){const node=session.pending;if(!node)throw Error('没有待执教的正式比赛');T.validate(result,node.a,node.b,node.playedBestOf);session.committed[node.id]={node:{...node,bestOf:node.playedBestOf},result,kind:'formal'};session.pending=null;}
 function create(seed,rosters,cards,club,options={}){const ctx=legacyCreate(seed,rosters,cards,club);if(options.teamStyle===false||!H)return ctx;ctx.styleVersion=H.version;if(options.systemClosure!==false&&J&&C){ctx.closureVersion='system-closure-1';ctx.matchSelectionVersion='reachable-1';ctx.stageFeedbackVersion=J.version;ctx.stageFeedback=J.create();C.complete(ctx,cards);}const mapIds=options.mapIds||['ascent','haven','split','sunset','breeze','lotus','fracture','abyss','summit'];for(const t of ctx.teams){t.tacticalProfile=H.create(seed,t.id,{neutral:t.id===club});t.mapKnowledge=H.mapScores(seed,t.id,mapIds);t.mapKnowledgeOrigin='game-seeded';}return ctx;}
 function settleTeamResult(ctx,node,result){
  if(!ctx.styleVersion)return;if(ctx.styleVersion!==H.version)throw Error('未知赛年队伍风格版本');
  for(const [i,m]of result.maps.entries())for(const [id,home]of [[node.a,true],[node.b,false]]){
   const t=ctx.teams.find(t=>t.id===id),counts=m.tacticUsage?.[home?'home':'away']||H.usage(m.rounds,home),won=home?m.win:!m.win;
   if(H.settle(t.tacticalProfile,node.id+':map:'+i,counts,won)&&id!==ctx.club)t.mapKnowledge[m.mapId]=Math.max(0,Math.min(100,(t.mapKnowledge[m.mapId]??50)+(won?.8:-.6)));
  }
 }
 function seriesMaps(ctx,node,maps){const pool=shuffle(maps,O.random(ctx.seed+':maps:'+node.id));if(!ctx.styleVersion||pool.length!==7||node.bestOf===1)return pool.slice(0,node.bestOf);const a=ctx.teams.find(t=>t.id===node.a),b=ctx.teams.find(t=>t.id===node.b),v=V.create(pool,{bestOf:node.bestOf,grandFinal:!!node.grandFinal,playerUpper:node.upperTeam===node.a,canChoose:false});while(v.moves.length<7){V.auto(v,b.mapKnowledge);if(V.actor(v)==='player'){const st=V.sequence(v)[v.moves.length],available=pool.filter(id=>!v.moves.includes(id));available.sort((x,y)=>(st.kind==='ban'?1:-1)*((a.mapKnowledge[x]??50)-(a.mapKnowledge[y]??50))||pool.indexOf(x)-pool.indexOf(y));V.move(v,available[0]);}}return V.maps(v);}
 return {regions,kickoffByes,pointTables,sources,create,groups,rank,runStage,simulate,pointStandings,commitStage,findFeatured,prepare,progress,submit,settleTeamResult};
});
