/* Format engine: the callback supplies actual series results. Re-running with a
   committed prefix is safe; speculative simulations never write this prefix. */
(function(root,factory){const api=factory();if(typeof module==='object')module.exports=api;else root.TOURNAMENT=api;})(typeof window==='object'?window:this,function(){
 'use strict';
 const w=id=>'W:'+id,l=id=>'L:'+id;
 function graph(nodes,teams,play,prefix=''){const results={},games=[];const resolve=ref=>ref.startsWith('W:')?results[ref.slice(2)]?.winner:ref.startsWith('L:')?results[ref.slice(2)]?.loser:ref;for(const [id,aRef,bRef,bestOf=3,grandFinal=false] of nodes){const a=resolve(aRef),b=resolve(bRef);if(!a||!b||a===b)throw Error('签表引用不合法：'+id);const node={id:prefix+id,a,b,higherSeed:teams.indexOf(a)<=teams.indexOf(b)?a:b,bestOf,officialBestOf:bestOf,grandFinal,upperTeam:grandFinal?a:null,label:id};const result=play(node);validate(result,a,b,result.bestOf||bestOf);results[id]=result;games.push({...node,...result});}return {results,games};}
 function validate(r,a,b,bestOf){const target=(bestOf+1)/2;if(!r||![a,b].includes(r.winner)||![a,b].includes(r.loser)||r.winner===r.loser||!Number.isInteger(r.scoreA)||!Number.isInteger(r.scoreB)||Math.max(r.scoreA,r.scoreB)!==target||Math.min(r.scoreA,r.scoreB)<0||Math.min(r.scoreA,r.scoreB)>=target||r.winner!==(r.scoreA>r.scoreB?a:b))throw Error('系列赛结果不合法');}
 function doubleNodes(t,byes=false){if(t.length!==8)throw Error('双败赛需要八队');const n=[];if(byes){n.push(['U1a',t[2],t[5]],['U1b',t[3],t[4]],['U2a',t[0],w('U1b')],['U2b',t[1],w('U1a')],['L1a',l('U1a'),t[7]],['L1b',l('U1b'),t[6]]);}else{n.push(['U1a',t[0],t[7]],['U1b',t[3],t[4]],['U1c',t[1],t[6]],['U1d',t[2],t[5]],['U2a',w('U1a'),w('U1b')],['U2b',w('U1c'),w('U1d')],['L1a',l('U1a'),l('U1b')],['L1b',l('U1c'),l('U1d')]);}n.push(['L2a',l('U2b'),w('L1a')],['L2b',l('U2a'),w('L1b')],['UF',w('U2a'),w('U2b')],['L3',w('L2a'),w('L2b')],['LF',l('UF'),w('L3'),5],['GF',w('UF'),w('LF'),5,true]);return n;}
 function double(t,play,prefix='',byes=false){const out=graph(doubleNodes(t,byes),t,play,prefix),r=out.results;return {...out,placements:[[r.GF.winner],[r.GF.loser],[r.LF.loser],[r.L3.loser],[r.L2a.loser,r.L2b.loser],[r.L1a.loser,r.L1b.loser]]};}
 function kickoff(t,play,prefix=''){if(t.length!==12)throw Error('启点赛需要十二队');const n=[['U1a',t[4],t[5]],['U1b',t[6],t[7]],['U1c',t[8],t[9]],['U1d',t[10],t[11]],['U2a',t[0],w('U1a')],['U2b',t[1],w('U1b')],['U2c',t[2],w('U1c')],['U2d',t[3],w('U1d')],['M1a',l('U1a'),l('U2d')],['M1b',l('U1b'),l('U2c')],['M1c',l('U1c'),l('U2b')],['M1d',l('U1d'),l('U2a')],['M2a',w('M1a'),w('M1b')],['M2b',w('M1c'),w('M1d')],['U3a',w('U2a'),w('U2b')],['U3b',w('U2c'),w('U2d')],['L1a',l('M1a'),l('M1b')],['L1b',l('M1c'),l('M1d')],['M3a',l('U3a'),w('M2a')],['M3b',l('U3b'),w('M2b')],['L2a',l('M2b'),w('L1a')],['L2b',l('M2a'),w('L1b')],['L3a',l('M3a'),w('L2a')],['L3b',l('M3b'),w('L2b')],['M4',w('M3a'),w('M3b')],['L4',w('L3a'),w('L3b')],['UF',w('U3a'),w('U3b'),5],['L5',l('M4'),w('L4')],['MF',l('UF'),w('M4'),5],['LF',l('MF'),w('L5'),5]];const out=graph(n,t,play,prefix),r=out.results;return {...out,placements:[[r.UF.winner],[r.MF.winner],[r.LF.winner],[r.LF.loser],[r.L5.loser],[r.L4.loser],[r.L3a.loser,r.L3b.loser],[r.L2a.loser,r.L2b.loser],[r.L1a.loser,r.L1b.loser]]};}
 function metrics(t,games){const row={id:t,wins:0,losses:0,mapDifference:0,roundDifference:0};for(const g of games){if(g.a!==t&&g.b!==t)continue;const a=g.a===t;g.winner===t?row.wins++:row.losses++;row.mapDifference+=(a?1:-1)*(g.scoreA-g.scoreB);row.roundDifference+=(a?1:-1)*(g.maps||[]).reduce((n,m)=>n+m.home-m.away,0);}return row;}
 // Partition tied subgroups, then restart head-to-head criteria for each reduced
 // group. If all official criteria tie, use an explicit deterministic Bo1 playoff.
 function standings(teams,games,play,prefix='tie:'){const base=teams.map(id=>metrics(id,games));const tied=(ids,index=0)=>{if(ids.length<2)return ids;const subset=games.filter(g=>ids.includes(g.a)&&ids.includes(g.b));const value=id=>{const m=metrics(id,index<3?subset:games);return index===0?m.wins:index===1||index===3?m.mapDifference:m.roundDifference;};const partitions=new Map();for(const id of ids){const v=value(id);if(!partitions.has(v))partitions.set(v,[]);partitions.get(v).push(id);}const groups=[...partitions.entries()].sort((a,b)=>b[0]-a[0]);if(groups.length>1)return groups.flatMap(([,g])=>tied(g,0));if(index<4)return tied(ids,index+1);if(!play)return ids;const sorted=[...ids];for(let i=0;i<sorted.length;i++)for(let j=i+1;j<sorted.length;j++){const a=sorted[i],b=sorted[j],r=play({id:prefix+a+':'+b,a,b,bestOf:1,label:'同分加赛'});if(r.winner===b)[sorted[i],sorted[j]]=[sorted[j],sorted[i]];}return sorted;};const winGroups=new Map();for(const r of base){if(!winGroups.has(r.wins))winGroups.set(r.wins,[]);winGroups.get(r.wins).push(r.id);}return [...winGroups.entries()].sort((a,b)=>b[0]-a[0]).flatMap(([,ids])=>tied(ids)).map((id,i)=>({...base.find(r=>r.id===id),place:i+1}));}
 function regular(groups,play,prefix=''){const games=[],tables=[];groups.forEach((teams,g)=>{for(let i=0;i<teams.length;i++)for(let j=i+1;j<teams.length;j++){const node={id:prefix+`G${g}:${i}:${j}`,a:teams[i],b:teams[j],bestOf:3,higherSeed:teams[i],label:'常规赛'};const r=play(node);validate(r,node.a,node.b,3);games.push({...node,...r});}const tied=[];tables.push(standings(teams,games.filter(g=>g.label==='常规赛'),node=>{const r=play(node);tied.push({...node,...r});return r;},prefix+'tie:'));games.push(...tied);});const seeds=[];for(let i=0;i<groups[0].length;i++){seeds.push(tables[0][i].id,tables[1][i].id);}return {games,tables,seeds};}
 // Enumerate complete legal matchings. Selecting one avoids greedy dead ends
 // and does not privilege the first compatible opponent in the participant list.
 function matchings(list,legal=()=>true){if(!list.length)return [[]];const a=list[0],out=[];for(let i=1;i<list.length;i++){const b=list[i];if(!legal(a,b))continue;for(const rest of matchings(list.filter(t=>t!==a&&t!==b),legal))out.push([[a,b],...rest]);}return out;}
 function swiss(teams,play,prefix='',firstRoundLegal=()=>true,options={}){const records=Object.fromEntries(teams.map(id=>[id,{w:0,l:0}])),games=[],draws=[];for(let round=0;round<3;round++){const active=teams.filter(id=>records[id].w<2&&records[id].l<2);const buckets=new Map();for(const t of active){const k=records[t].w+':'+records[t].l;if(!buckets.has(k))buckets.set(k,[]);buckets.get(k).push(t);}for(const [bucket,ids]of buckets){const legal=(a,b)=>(round!==0||firstRoundLegal(a,b))&&!games.some(g=>(g.a===a&&g.b===b)||(g.a===b&&g.b===a));const candidates=matchings(ids,legal);if(!candidates.length)throw Error('瑞士轮无合法配对');const rng=options.random?.('S'+round+':'+bucket),pairs=rng?candidates[Math.floor(rng()*candidates.length)]:candidates[0];if(rng)draws.push({round:round+1,bucket,teams:[...ids],pairs});for(let i=0;i<pairs.length;i++){const [a,b]=pairs[i],node={id:prefix+'S'+round+':'+bucket+':'+i,a,b,bestOf:3,label:'瑞士 '+bucket,...(rng?{higherSeed:options.higherSeed?.(a,b,round)|| (rng()<.5?a:b)}:{})};const r=play(node);validate(r,a,b,3);records[r.winner].w++;records[r.loser].l++;games.push({...node,...r});}}}return {games,records,qualified:teams.filter(t=>records[t].w===2),eliminated:teams.filter(t=>records[t].l===2),...(options.random?{draws}:{})};}
 function gsl(groups,play,prefix=''){const games=[],qualified=[],eliminated=[],third=[],fourth=[];groups.forEach((t,i)=>{const out=graph([['A',t[0],t[3]],['B',t[1],t[2]],['W',w('A'),w('B')],['L',l('A'),l('B')],['D',l('W'),w('L')]],t,play,prefix+'GSL'+i+':');games.push(...out.games);qualified.push(out.results.W.winner,out.results.D.winner);third.push(out.results.D.loser);fourth.push(out.results.L.loser);eliminated.push(out.results.D.loser,out.results.L.loser);});return {games,qualified,eliminated,third,fourth};}
 function cnPlayin(t,entrants,play,prefix=''){const n=[['U0a',t[6],entrants[1]],['U0b',t[7],entrants[0]],['U1a',t[1],w('U0a')],['U1b',t[2],t[4]],['U1c',t[0],w('U0b')],['U1d',t[3],t[5]],['U2a',w('U1a'),w('U1b')],['U2b',w('U1c'),w('U1d')],['L1a',l('U0a'),l('U1d')],['L1b',l('U0b'),l('U1b')],['L2a',l('U1c'),w('L1a')],['L2b',l('U1a'),w('L1b')],['L3a',l('U2a'),w('L2a')],['L3b',l('U2b'),w('L2b')],['UF',w('U2a'),w('U2b')],['LF',w('L3a'),w('L3b')]];const out=graph(n,[...t,...entrants],play,prefix),r=out.results;return {...out,qualified:[r.UF.winner,r.UF.loser,r.LF.winner,r.LF.loser],eliminated:[r.L3a.loser,r.L3b.loser,r.L2a.loser,r.L2b.loser,r.L1a.loser,r.L1b.loser]};}
 return {w,l,graph,validate,doubleNodes,double,kickoff,metrics,standings,regular,swiss,gsl,cnPlayin,matchings};
});
