(() => {
 const D=DEMO,F=FLOW_UI,esc=F.esc,asset=F.asset,card=k=>D.cards.find(p=>D.key(p)===k);
 const record=(year,place,club='EDG')=>`<button class="season-record" data-season="${year}"><span>${String(year).padStart(2,'0')}</span><div><strong>第 ${year} 赛年</strong><small>${club} · ${place}</small></div><b>→</b></button>`;
 const seasons=s=>s.seasons||[];
 const members=s=>[...new Set(seasons(s).flatMap(y=>y.roster).map(k=>card(k)?.name).filter(Boolean))].map(name=>D.cards.find(p=>p.name===name));
 function career(s){return {title:'档案',body:`${tabs('career')}<div class="career"><button class="coach-entry" data-go="archive/coach"><div class="coach-symbol"><span>VM</span></div><div><h3>${esc(s.coachName)}</h3><p>${s.history?'已完成 '+seasons(s).length+' 个赛年':'第一个赛年'}</p></div><span>资料 →</span></button>${s.run!=='none'&&s.run!=='finished'?`<div class="career-run"><span>${String(s.year).padStart(2,'0')}</span><div><strong>当前征战</strong><small>${D.phases[s.phase]}</small></div><button data-go="campaign">继续 →</button></div>`:''}<div class="overview-title"><h3>赛年记录</h3></div>${s.history?seasons(s).slice().reverse().map(y=>record(y.year,y.place,y.club)).join(''):`<div class="career-empty"><strong>尚无完成的赛年</strong><p>完成征战后，可以在这里回顾。</p></div>`}<div class="overview-title"><h3>执教积累</h3></div><button class="career-link" data-go="archive/relationships">选手关系<span>→</span></button><button class="career-link" data-go="archive/honors">荣誉记录<span>→</span></button><button class="career-link" data-go="archive/settings">设置<span>→</span></button></div>`};}
 function tabs(current){return `<div class="archive-switch" role="group" aria-label="档案内容"><button data-go="archive/album" aria-pressed="${current==='album'}">图鉴</button><button data-go="archive/career" aria-pressed="${current==='career'}">生涯</button></div>`;}
 function album(s){return {title:'档案',body:`${tabs('album')}<form class="archive-tools" role="search"><div class="archive-search-row"><label class="players-search"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M21 21l-5-5 M10.5 17a6.5 6.5 0 1 0 0-13 6.5 6.5 0 0 0 0 13"/></svg><input id="album-query" type="search" autocomplete="off" placeholder="搜索选手或队伍" aria-label="搜索选手或队伍" value="${esc(s.query)}"></label><button type="button" id="filter-entry" class="filter-entry" aria-haspopup="dialog">筛选 <span id="filter-count"></span></button></div><div class="archive-filter-summary"><span id="result-count" aria-live="polite"></span><div id="filter-tags" class="filter-tags"></div></div></form><div class="players-grid" id="album-results"></div><div class="page-pad"><details class="plain-details"><summary>未解锁 · 3 张</summary><div class="locked-grid">${['赛事珍藏','选手卡','选手卡'].map((t,i)=>`<button data-locked="${i}"><b>◇</b><span>${t}</span><small>未解锁</small></button>`).join('')}</div></details></div>`};}
 function team(s){if(!s.roster.length||s.run==='none')return {title:'战队',body:F.empty('还没有本次阵容','开始征战，抽选你的五位队员。')+'<div class="page-pad"><button class="blue-button full" data-go="campaign/start">去组队 →</button></div>'};return {title:'战队',body:`<div class="team-summary"><button class="team-profile-entry" data-go="team/overview"><img src="${asset('队伍logo/'+s.club+'.png')}" alt=""><div><h3>${s.club}</h3><small>第 ${s.year} 赛年</small></div><span>资料 →</span></button><span id="team-count">5 名选手</span></div><form class="players-tools" role="search"><label class="players-search"><input id="team-query" type="search" placeholder="搜索选手" aria-label="搜索选手" value="${esc(s.teamQuery)}"></label><label class="players-sort"><select id="team-sort" aria-label="阵容排序">${[['default','默认排序'],['rating','总评 ↓'],['AIM','枪法 ↓'],['SYN','协同 ↓'],['SEN','意识 ↓']].map(([v,l])=>`<option value="${v}" ${s.teamSort===v?'selected':''}>${l}</option>`).join('')}</select></label></form><div class="players-grid" id="team-results"></div><div class="page-pad"><button class="quiet-button full" data-go="team/maps">地图资料 →</button></div>`};}
 function overview(s){return {title:'战队资料',body:NAV_PROFILE_UI.team(F.lineup(s)).replaceAll('EDG','__OUR__').replaceAll('BLG',F.opponent(s)).replaceAll('__OUR__',s.club).replace('第 01 赛年','第 '+String(s.year).padStart(2,'0')+' 赛年'),dock:'进入备战 →',go:'campaign/prepare'};}
 function maps(s){return {title:'地图资料',body:`<div class="page-pad"><div class="flow-kicker"><span>当前地图池</span><b>07</b></div><h3 class="page-heading">熟悉每一张战场。</h3><div class="map-grid">${D.maps.map(m=>`<button data-map-detail="${m.id}">${D.art(m)}<strong>${m.name}</strong><small>地图分 ${m.score}</small></button>`).join('')}</div><details class="plain-details"><summary>关于地图分</summary><p>表示这张地图上的准备与适应，包括教练积累与当前阵容磨合。</p></details></div>`};}
 function mapDetail(id){const m=D.maps.find(m=>m.id===id)||D.maps[0];return {title:m.name,body:`<div class="page-pad">${D.art(m)}<div class="map-detail-score"><span>地图分</span><b>${m.score}</b></div><div class="year-highlights"><div><b>${m.index%2?4:6}</b><span>胜场</span></div><div><b>${m.index%3+2}</b><span>负场</span></div><div><b>+2</b><span>最近变化</span></div></div><div class="section-caption">最近比赛</div><div class="change-rows"><div><span>对 BLG · 13 : 9</span><b>+1</b></div><div><span>对 FPX · 13 : 11</span><b>+1</b></div></div><details class="plain-details"><summary>积累与磨合</summary><p>教练积累跨赛年保留，当前五人的磨合随换人调整。</p></details></div>`};}
 function coach(s){return {title:'教练资料',body:`<div class="page-pad"><div class="coach-profile"><div class="coach-symbol">VM</div><h3>${esc(s.coachName)}</h3><button class="text-action" data-action="rename">编辑昵称</button></div><div class="team-state-metrics">${[['战术',72],['临场',68],['声望',65]].map(([label,n])=>`<div><b>${n}</b><span>${label}</span></div>`).join('')}</div><div class="section-caption">执教足迹</div><div class="year-highlights"><div><b>${String(seasons(s).length).padStart(2,'0')}</b><span>完成赛年</span></div><div><b>${String(members(s).length).padStart(2,'0')}</b><span>共事选手</span></div><div><b>${String(seasons(s).length).padStart(2,'0')}</b><span>赛事荣誉</span></div></div><details class="plain-details"><summary>能力与积累</summary><dl class="explain-list"><dt>战术</dt><dd>阵容与战术的赛前布置</dd><dt>临场</dt><dd>比赛中的读局与调整</dd><dt>声望</dt><dd>执教表现的长期认可</dd></dl></details><button class="career-link" data-go="archive/relationships">选手关系<span>→</span></button><button class="career-link" data-go="archive/honors">荣誉记录<span>→</span></button></div>`};}
 function relationships(s){if(!s.history)return {title:'选手关系',body:NAV_PROFILE_UI.records('relationships')};const people=members(s);return {title:'选手关系',body:`<div class="page-pad"><div class="flow-kicker"><span>共同走过的赛年</span><b>${people.length} 位</b></div><div class="relationship-list">${people.map((p,i)=>`<button data-go="archive/relation/${D.key(p)}"><img src="${F.photo(p)}" alt=""><div><strong>${p.name}</strong><small>共事 ${seasons(s).filter(y=>y.roster.some(k=>card(k).name===p.name)).length} 个赛年</small></div><span><b>${42-i*3}</b><small>熟识</small></span></button>`).join('')}</div><details class="plain-details"><summary>熟识与版本</summary><p>同一选手各卡版本共享熟识，荣誉按实际参赛版本记录。</p></details></div>`};}
 function relation(s,k){const p=card(k)||D.cards[0],records=seasons(s).filter(y=>y.roster.some(k=>card(k).name===p.name)),versions=[...new Set(records.flatMap(y=>y.roster).filter(k=>card(k).name===p.name))];return {title:'共事记录',body:`<div class="page-pad"><div class="relation-person"><img src="${F.photo(p)}" alt=""><div><h3>${p.name}</h3><span>熟识 <b>${Math.max(0,42-members(s).findIndex(c=>c.name===p.name)*3)}</b></span></div></div><div class="section-caption">共事赛年</div>${records.map(y=>record(y.year,y.place,y.club)).join('')}<div class="section-caption">实际参赛版本</div>${versions.map(k=>`<button class="version-record" data-go="archive/player/${k}"><strong>${card(k).tier}卡</strong><span>参赛版本</span><b>→</b></button>`).join('')}<details class="plain-details"><summary>记录归属</summary><p>熟识跨版本共享，此处参赛与荣誉只归属记录中的卡版本。</p></details></div>`};}
 function honors(s){if(!s.history)return {title:'荣誉记录',body:NAV_PROFILE_UI.records('honors')};return {title:'荣誉记录',body:`<div class="page-pad">${seasons(s).slice().reverse().map(y=>`<section class="honor-card"><span class="honor-cup">${F.medal('trophy')}</span><div><small>第 ${String(y.year).padStart(2,'0')} 赛年</small><h3>${y.place}</h3><span>${y.club} · ${y.roster.length} 位参赛选手</span></div></section><details class="plain-details"><summary>查看参赛卡</summary><div class="mini-list honor-participants">${y.roster.map(k=>F.mini(card(k),'data-go="archive/player/'+k+'"')).join('')}</div></details>`).join('')}</div>`};}
 function season(s,n){const y=seasons(s).find(y=>y.year===Number(n))||D.seed().seasons[0];return {title:'第 '+y.year+' 赛年',body:`<div class="page-pad"><div class="result-hero"><span>执教记录 · ${y.club}</span><div class="result-medal">${F.medal('trophy')}</div><h3>${y.place}</h3><p>与这五人，一起走过。</p></div><div class="team-profile-roster">${y.roster.map(k=>{const p=(y.cardSnapshot||D.cards).find(p=>D.key(p)===k);return `<button data-go="archive/player/${k}"><img src="${F.photo(p)}" alt=""><span>${p.name}</span></button>`;}).join('')}</div><div class="section-caption">阶段回顾</div><div class="season-timeline">${D.phases.map((name,i)=>`<details><summary><span>${String(i+1).padStart(2,'0')}</span><strong>${name}</strong><small>${i===1&&y.place==='大师赛亚军'?'亚军':i===7?'四强':'已完成'}</small></summary><p>${i===1?'赛事成绩与实际参赛卡已收录。':'阶段比赛与成长已收录。'}</p></details>`).join('')}</div></div>`};}
 function settings(s){return {title:'设置',body:`<div class="page-pad"><div class="setting-group"><h3>显示与操作</h3><label class="setting-toggle"><span>减少动画</span><input id="reduced-motion" type="checkbox" ${s.reducedMotion?'checked':''}></label><label class="setting-toggle"><span>放大文字</span><input id="large-text" type="checkbox" ${s.largeText?'checked':''}></label></div><div class="setting-group"><h3>应用</h3><button class="setting-row" data-action="install"><span>安装到主屏幕</span><b>→</b></button><button class="setting-row" data-action="check-update"><span>检查原型更新</span><b>→</b></button><div class="setting-info"><span>离线浏览</span><small id="offline-setting">准备中</small></div></div><div class="setting-group"><h3>征战存档</h3><button class="setting-row" data-action="export-save"><span>导出备份</span><b>→</b></button><button class="setting-row" data-action="import-save"><span>导入备份</span><b>→</b></button><button class="setting-row" data-action="recover-save"><span>恢复上个有效存档</span><b>→</b></button><p class="muted">自动保存；升级后进行中的赛年保留原卡牌数值。</p></div><div class="setting-group"><h3>演示状态</h3><button class="setting-row" data-action="scene-menu"><span>切换预览章节</span><b>→</b></button><button class="setting-row" data-action="reset-demo"><span>重置本机演示</span><b>→</b></button></div><p class="muted center">VAL MANAGER · UI 原型 01</p></div>`};}
 function player(s,k){const p=card(k)||D.cards[0];let body=NAV_PROFILE_UI.player(p,D.cards.filter(c=>c.name===p.name));const shared=seasons(s).filter(y=>y.roster.some(v=>card(v).name===p.name)),honors=seasons(s).filter(y=>y.roster.includes(k));if(shared.length)body=body.replace('尚无已结算的共事记录','已共事 '+shared.length+' 个赛年 · 熟识 '+Math.max(0,42-members(s).findIndex(c=>c.name===p.name)*3));body=body.replace('暂无荣誉',honors.length?honors.map(y=>'第 '+y.year+' 赛年 · '+y.place).join(' / '):'本版本尚无参赛荣誉');return {title:'选手资料',body,dock:'查看卡面',action:'card-face'};}
 function state(kind){return {title:kind==='loading'?'加载中':kind==='error'?'暂时无法载入':'离线浏览',body:`<div class="page-pad">${kind==='loading'?'<div class="loading-skeleton"><i></i><i></i><i></i></div><p class="muted center" role="status">正在准备资料…</p>':F.empty(kind==='error'?'资料暂时没有载入':'暂时离线',kind==='error'?'已有的浏览条件已保留。':'已缓存的页面与演示仍可继续。')}</div>`,dock:kind==='error'?'重试':kind==='loading'?'继续预览':'继续浏览',action:'recover'};}
 const settingsView=settings;
 function settingsWithExit(s){const v=settingsView(s);if(!['none','finished'].includes(s.run))v.body=v.body.replace('<p class="muted center">VAL MANAGER', '<button class="quiet-button full" data-action="abandon-run">结束当前征战</button><p class="muted center">VAL MANAGER');return v;}
 window.ARCHIVE_UI={career,album,team,overview,maps,mapDetail,coach,relationships,relation,honors,season,settings:settingsWithExit,player,state};
})();
