// Publish a read-only snapshot and the SAME draw function used by the game.
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '../../..');
const catalog = require(path.join(root, '游戏/catalog'));
const config = require(path.join(root, '游戏/content/packs.json'));
const rosters = require(path.join(root, '游戏/content/rosters/2026-production-v1.json'));
const mapSideData = require(path.join(root, '游戏/content/map-side-stats-2026-10-07.json'));
const diamondLabels={
 '23东京:ZmjjKK':{trait:'首杀机器',moment:'冥驹审判'},
 '24首尔:ZmjjKK':{trait:'大场面先生',moment:'降维打击'},
 '25曼谷:CHICHOO':{trait:'残局大师',moment:'一人成军'},
 '25多伦多:Spring':{trait:'黏合剂',moment:'黑马之蹄'},
 '23洛杉矶:whzy':{trait:'首杀机器',moment:'无情判官'}
};
const cards = catalog.cards.filter(p => p.region === 'CN').map(p => ({
  name:p.name, playerId:p.playerId, cardId:p.cardId, tier:p.tier, team:p.team, region:p.region,
  AIM:p.AIM, SYN:p.SYN, SEN:p.SEN, rating:p.rating, agents:p.agents, cut:p.cut,
  photo:p.cut ? `切面海报/${p.cut}_${p.name}.png` : `选手半身像/${p.name}.png`,
  event:p.cut || '',
  ...diamondLabels[p.cut+':'+p.name],
  agentAssets:Object.fromEntries(p.agents.map(a => {const file=(a==='K/O'?'KO':a)+(fs.existsSync(path.join(root,'素材库/英雄头像',(a==='K/O'?'KO':a)+'.png'))?'.png':'.jpg');return [a,'英雄头像/'+file];}))
}));
const globalCards=catalog.cards.filter(p=>p.tier!=='钻').map(p=>({cardId:p.cardId,playerId:p.playerId,name:p.name,team:p.team,region:p.region,tier:p.tier,AIM:p.AIM,SYN:p.SYN,SEN:p.SEN,rating:p.rating,agents:p.agents}));
const sampler = require(path.join(root, '游戏/packs')).drawPack.toString();
const agents=fs.readdirSync(path.join(root,'素材库/英雄头像')).filter(f=>/\.(png|jpg)$/.test(f)).map(f=>f.slice(0,-4)==='KO'?'K/O':f.slice(0,-4));
fs.writeFileSync(path.join(__dirname,'content-snapshot.js'), '// Generated by build-content.cjs; existing card abilities remain unchanged.\nwindow.CN_CONTENT='+JSON.stringify({cards,globalCards,mapSideData,competitionProvenance:require(path.join(root,'游戏/content/competition-provenance-2026.json')),rosters:rosters.teams,config,agents,clubs:rosters.teams.filter(t=>t.region==='CN'&&t.selectable).map(t=>t.teamId)})+';\nwindow.CN_DRAW='+sampler.replace('config = packConfig','config = window.CN_CONTENT.config').replace('poolCards = catalog.cards','poolCards = window.CN_CONTENT.cards')+';\n');
console.log(`CN snapshot: ${cards.length} card versions; ${rosters.teams.filter(t=>t.region==='CN'&&t.selectable).length} clubs`);
