(() => {
 const D=DEMO,R=PROTOTYPE_RULES,F=FLOW_UI,A=ARCHIVE_UI,card=k=>D.cards.find(p=>D.key(p)===k),esc=F.esc;
 const note=t=>`<p class="rule-note">${t}</p>`,section=(t,b)=>`<section class="page-pad"><h3 class="page-heading">${t}</h3>${b}</section>`;
 const thumb=(p,k)=>`<button class="card-thumb" data-player="${esc(k)}" data-tier="${p.tier}" aria-label="查看 ${esc(p.name)}，${p.tier}卡，总评 ${p.rating}"><img src="${F.asset(p.photo||'选手半身像/'+p.name+'.png','thumb')}" alt="${esc(p.name)}" loading="lazy" decoding="async" width="240" height="360"><b>${p.rating}</b></button>`;
 window.renderNavThumb=thumb;
 const grid=(pack,count=10)=>`<div class="thumb-grid pack-thumb-grid">${pack.map((k,i)=>i<count?thumb(card(k),k):`<span class="sealed-card" aria-label="第 ${i+1} 张尚未揭晓">◇</span>`).join('')}</div>`;
 F.packs=s=>{const n=s.opened[s.pack],done=s.opened.every(v=>v===10);return {title:'开启初始卡包',body:section('初始卡包',note('每包10张，揭晓三包后选一包组队。钻5% · 金15% · 银30% · 铜50%。')+`<div class="pack-tabs">${s.packs.map((_,i)=>`<button data-pack="${i}" aria-pressed="${s.pack===i}">卡包 ${i+1}<small>${s.opened[i]} / 10</small></button>`).join('')}</div>${n===0?`<button class="paper-pack-demo" data-action="open-pack"><div class="paper-seal">PLAYER SERIES <span>✦</span></div><b>CN</b><span>选手卡包 ${s.pack+1}</span><small>点击开启 · 十张待揭晓</small></button>`:grid(s.packs[s.pack],n)}`),dock:done?'比较三个包 →':n===10?'开启下一个卡包 →':n===0?'开启本包 →':'继续揭晓 →',action:done?'compare-packs':n===10?'next-pack':'open-pack'};};
 F.revealEffect=(p,html)=>{const tiers={'铜':['bronze','铜卡 · 初遇',3],'银':['silver','银卡 · 锋芒',6],'金':['gold','金卡 · 闪耀',10],'钻':['diamond','钻卡 · 明星时刻',12]},[type,label,n]=tiers[p.tier];return '<div class="quality-reveal reveal-stage tier-'+type+'" data-reveal-tier="'+p.tier+'"><div class="reveal-aura" aria-hidden="true"><i class="reveal-ring"></i><i class="reveal-ring second"></i>'+Array.from({length:n},(_,i)=>'<i class="reveal-spark" style="--angle:'+i*360/n+'deg;--distance:'+(68+(i%3)*18)+'px"></i>').join('')+'</div><div class="reveal-prelude" aria-hidden="true"><span class="reveal-seal">'+(p.tier==='钻'?'◇':'✦')+'</span><b>'+label+'</b></div><div class="reveal-card">'+html+'</div><button class="reveal-skip" data-reveal-skip>跳过动效</button></div>';};
 F.reveal=s=>{const n=s.opened[s.pack],k=s.packs[s.pack][Math.max(0,Math.min(n-1,9))],p=card(k);return {title:'揭晓选手',body:section('卡包 '+(s.pack+1)+' · 第 '+Math.max(1,Math.min(n,10))+' 张',F.revealEffect(p,'<div class="players-grid detail-card-wrap">'+renderNavCard(p,k)+'</div>')+'<p class="muted center">'+(p.tier==='钻'?'明星时刻 · '+esc(p.cut):p.tier+'卡')+'</p>'),dock:n>=10?'收下，查看本包 →':'收下，揭晓下一张 →',action:'next-card'};};
 F.compare=s=>({title:'选择一个整包',body:section('三包全览',note('只选一包。点海报查看完整卡牌。'))+s.packs.map((p,i)=>`<section class="pack-section"><div class="pack-section-heading"><h3>卡包 ${i+1}</h3><button data-pack="${i}" aria-pressed="${s.pack===i}">${s.pack===i?'已选中':'选择此包'}</button></div>${grid(p,s.opened[i])}</section>`).join(''),dock:'选择卡包 '+(s.pack+1)+'，组成五人 →',action:'choose-pack',disabled:!s.opened.every(v=>v===10)});
 F.pick=s=>({title:'组成五人队',body:section('从卡包 '+(s.pack+1)+' 选择五人',`<div class="selection-counter"><h3>出战名单</h3><b>${s.lineup.length} / 5</b></div>${note('5人首发，不设替补；同一选手不可重复，最多一钻。')}<div class="thumb-grid pack-thumb-grid">${s.packs[s.chosenPack].map(k=>`<div class="thumb-select ${s.lineup.includes(k)?'selected':''}">${thumb(card(k),k)}<button class="thumb-pick" data-pick="${k}" aria-label="${s.lineup.includes(k)?'取消':'选择'} ${esc(card(k).name)}" aria-pressed="${s.lineup.includes(k)}">${s.lineup.includes(k)?'✓ 已选':'＋ 选择'}</button></div>`).join('')}</div><button class="quiet-button full" data-action="reselect-pack">重新选择整包</button>`),dock:'确认阵容 · '+s.lineup.length+' / 5',action:'confirm-lineup',disabled:s.lineup.length!==5});
 const oldAlbum=A.album;A.album=s=>{const v=oldAlbum(s);v.body=v.body.replace(/class="[^"]*" id="album-results"/,'class="thumb-grid album-thumb-grid" id="album-results"');return v;};
 const oldReinforce=F.reinforce;F.reinforce=s=>{if((s.reinforcementOpened??0)<10)return {title:'开启补强卡包',body:section('补强卡包',note('仅一个包。钻 / 金 / 银 / 铜：'+(s.phase===1?'7.5 / 22.5 / 45 / 25%':'10 / 30 / 60 / 0%'))+grid(s.reinforcementPack,s.reinforcementOpened??0)),dock:'揭晓第 '+((s.reinforcementOpened??0)+1)+' 张 →',action:'reveal-reinforcement'};const v=oldReinforce(s);v.body=v.body.replaceAll('class="players-grid','class="thumb-grid pack-thumb-grid').replaceAll(/<button class="balance-card"[\s\S]*?<\/button>/g,html=>{const k=html.match(/data-player="([^"]+)"/)?.[1];return k?thumb(card(k),k):html;});return v;};
 F.agents=s=>{const m=F.matchMap(s),selected=s.agents[s.map]||{},members=F.lineup(s);return {title:'选择特工',body:section(`图 ${s.map+1} / ${s.bestOf||3} · ${m.name}`,`<div class="selection-counter"><h3>五人特工阵容</h3><b>${Object.keys(selected).length} / 5</b></div><button class="blue-button full" data-action="auto-agents">快速搭配特工</button>${note('★ 为招牌特工；快速搭配后仍可手动调整。')}<div class="agent-assignment">${members.map(p=>`<section><div class="assignment-person"><img src="${F.photo(p)}" alt=""><strong>${esc(p.name)}</strong><span>${esc(selected[D.key(p)]||'待选择')}</span></div><div class="agent-options">${p.agents.map(a=>`<button data-agent-player="${D.key(p)}" data-agent="${esc(a)}" aria-pressed="${selected[D.key(p)]===a}" ${AGENT_SELECTION.signature(p)===a?'class="signature-agent"':''}><img src="${F.asset(p.agentAssets[a])}" alt=""><span>${esc(a)}${AGENT_SELECTION.signature(p)===a?' <b class="signature-label">★ 招牌</b>':''}</span></button>`).join('')}</div><details class="all-agent-picker"><summary>全部特工</summary><div class="agent-options full-agent-list">${CN_CONTENT.agents.map(a=>`<button data-agent-player="${D.key(p)}" data-agent="${esc(a)}" aria-pressed="${selected[D.key(p)]===a}">${esc(a)}</button>`).join('')}</div></details></section>`).join('')}</div>`),dock:'确认特工 · '+Object.keys(selected).length+' / 5 →',action:'agents-confirm',disabled:Object.keys(selected).length!==5};};
})();
