/* Interaction contract only. Results, qualification and growth are labelled UI fixtures.
   No reads/writes to the actual game save or competition engine. */
(function(root,factory){const api=factory();if(typeof module==='object')module.exports=api;else root.PROTOTYPE_RULES=api;})(typeof window==='object'?window:this,function(){
 'use strict';
 const clamp=n=>Math.max(0,Math.min(100,Number.isFinite(n)?n:0));
 const familiar=u=>100*Math.max(0,u||0)/(Math.max(0,u||0)+40);
 const key=p=>p.name+'-'+p.tier+(p.tier==='钻'?'-'+p.cut:'');
 const pair=(a,b)=>JSON.stringify([a,b].sort());
 const mapCatalog=[['ascent','亚海悬城','#dbecf4'],['sunset','日落之城','#f3e3d8'],['split','霓虹町','#e4e5f1'],['haven','隐世修所','#dbece3'],['lotus','莲华古城','#e1ead7'],['breeze','微风岛屿','#dceaf0'],['summit','天枢云巅','#e1edf4'],['abyss','幽邃地窟','#d9e9f0'],['fracture','裂变峡谷','#ebe5d8']].map(([id,name,color],index)=>({id,name,color,index,score:50}));
 const shuffled=(list,rng)=>{const a=[...list];for(let i=a.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;};
 function init(s){s.version=2;s.coach??={战术:50,临场:50,声望:50};s.team??={羁绊:20,状态:50,熟练:50};s.familiarity??={};s.rapport??={};s.mapKnowledge??=Object.fromEntries(mapCatalog.map(m=>[m.id,50]));s.mapRecords??=[];s.participation??=[];s.honorRecords??=[];s.stageRecords??=[];s.rotations??=[];s.activeMaps??=mapCatalog.slice(0,7).map(m=>m.id);s.timeouts??={player:{reg:0,ot:0},opponent:{reg:0,ot:0}};s.ledger??=[];s.scenario??='normal';s.reviewMap??=null;return s;}
 function bond(s,cards){let same=0,rapport=0;for(let i=0;i<cards.length;i++)for(let j=i+1;j<cards.length;j++){if(cards[i].team===cards[j].team)same++;rapport+=clamp(s.rapport[pair(cards[i].playerId,cards[j].playerId)]||0);}return clamp(20+.15*cards.reduce((n,p)=>n+familiar(s.familiarity[p.playerId]),0)/5+20*same/10+.45*rapport/10);}
 function register(s,list,cards){const by=new Map(cards.map(p=>[key(p),p]));const chosen=list.map(k=>by.get(k)),previous=s.roster.map(k=>by.get(k)).filter(Boolean);const error=validate(list,cards);if(error)throw Error(error);const retained=previous.filter(p=>chosen.some(c=>c.playerId===p.playerId)).length;const base=40+.2*s.coach.战术;const old=s.team.熟练;s.team={羁绊:bond(s,chosen),状态:s.team.状态,熟练:clamp(base+(previous.length?retained/5*(old-base):0))};s.roster=[...list];s.rosterRevision=(s.rosterRevision||0)+1;}
 function validate(list,cards,allowed){if(!Array.isArray(list)||list.length!==5)return '请选择五位队员';const by=new Map(cards.map(p=>[key(p),p]));const a=list.map(k=>by.get(k));if(a.some(p=>!p||p.region!=='CN'))return '仅允许本次 CN 选手池';if(allowed&&list.some(k=>!allowed.includes(k)))return '只能从本次候选卡中选择';if(new Set(a.map(p=>p.playerId)).size!==5)return '同一选手只能选择一个版本';if(a.filter(p=>p.tier==='钻').length>1)return '阵容最多一张钻卡';return '';}
 function rotate(s,phase,rng){if(![2,5].includes(phase)||s.rotations.some(r=>r.phase===phase))return;const old=[...s.activeMaps],removed=shuffled(old,rng).slice(0,2),available=(s.contentSnapshot?.mapCatalog||mapCatalog).filter(m=>!old.includes(m.id)).map(m=>m.id),added=available.length>2?shuffled(available,rng).slice(0,2):available;if(added.length!==2)throw Error("地图池不足两张轮换候选");s.activeMaps=shuffled([...old.filter(id=>!removed.includes(id)),...added],rng);s.rotations.push({phase,removed,added});}
 function eligible(s,phase=s.phase){return s.qualificationOverrides?.[phase]!==false&&!(s.scenario==='miss-world'&&[1,4,7].includes(phase))&&!(s.scenario==='miss-playoffs'&&[3,4,6,7].includes(phase));}
 function resetMap(s){s.round=0;s.halftimeSeen=false;s.timeouts={player:{reg:0,ot:0},opponent:{reg:0,ot:0}};s.adjusting='';s.adjustBackup=null;s.coachWindow='';s.aiPaused=false;s.reviewMap=null;s.playing=false;}
 function resetMatch(s){s.run='active';s.bp=[];s.bpRole='A';s.sideChosen=[false,false,false];s.pendingMap='';s.map=0;s.agents={};s.completedMatch=false;resetMap(s);}
 function bpActor(s,index=s.bp.length){return ((index%2===0)===(s.bpRole!=='B'))?'player':'opponent';}
 function fillOpponentBP(s){while(s.bp.length<6&&bpActor(s)==='opponent')s.bp.push(s.activeMaps.find(id=>!s.bp.includes(id)));if(s.bp.length===6)s.bp.push(s.activeMaps.find(id=>!s.bp.includes(id)));}
 function pendingSide(s){s.sideChosen??=[false,!!s.side2Chosen,!!s.side3Chosen];const needed=s.bpRole==='B'?[0]:[1,2];return needed.find(i=>s.bp.length>=[3,4,7][i]&&!s.sideChosen[i]);}
 function newRun(s,content,draw,rng){init(s);s.run='draft';s.phase=0;s.pack=0;s.chosenPack=null;s.lineup=[];s.roster=[];s.reinforce=[];s.reinforcementPack=[];s.opened=[0,0,0];s.resultMode='normal';s.scenario='normal';s.qualificationOverrides={};s.year=Math.max(s.year||0,...s.seasons.map(y=>y.year))+1;s.stageRecords=[];s.rotations=[];s.rapport={};s.ledger=[];s.team={羁绊:20,状态:50,熟练:40+.2*s.coach.战术};s.activeMaps=shuffled(s.contentSnapshot?.mapCatalog||mapCatalog,rng).slice(0,7).map(m=>m.id);s.packs=Array.from({length:3},()=>draw({region:'CN',tier:'starter',rng,minimumDistinct:5}).map(key));resetMatch(s);s.run='draft';}
 function openReinforcement(s,draw,rng){s.run='reinforce';s.reinforce=[...s.roster];if(!s.reinforcementPack?.length||s.reinforcementAt!==s.phase){s.reinforcementPack=draw({region:'CN',tier:s.phase===1?'enhanced':'summit',rng}).map(key);s.reinforcementAt=s.phase;s.reinforcementOpened=0;}}
 function reveal(s,reinforcement=false,all=false){const pack=reinforcement?s.reinforcementPack:s.packs[s.pack],count=reinforcement?(s.reinforcementOpened||0):s.opened[s.pack];if(s.run!==(reinforcement?'reinforce':'draft')||!pack?.length)return null;const next=all?10:Math.min(10,count+1);if(reinforcement)s.reinforcementOpened=next;else s.opened[s.pack]=next;s.unlocked=[...new Set([...s.unlocked,...pack.slice(0,next)])];return pack[next-1];}
 function results(s){if(s.resultMode==='loss')return [{home:9,away:13,win:false},{home:10,away:13,win:false}];if(s.resultMode==='sweep')return [{home:13,away:7,win:true},{home:13,away:9,win:true}];return [{home:s.scenario==='overtime'?16:13,away:s.scenario==='overtime'?14:9,win:true},{home:8,away:13,win:false},{home:13,away:11,win:true}];}
 // Never put the deciding winning round before the last round of a fixed sample.
 function rounds(s){return results(s).map((r,map)=>{if(r.home===16){return [...Array.from({length:24},(_,i)=>i%2===0),true,false,false,true,true,true];}let h=r.home-(r.win?1:0),a=r.away-(r.win?0:1);const out=[];while(h+a){const win=h>0&&(a===0||(out.length+map)%5<3);out.push(win);win?h--:a--;}out.push(r.win);return out;});}
 function score(s){const seq=rounds(s)[s.map].slice(0,s.round);return [seq.filter(Boolean).length,seq.filter(x=>!x).length];}
 function timeoutLeft(s,party='player'){return s.round>=24?1-s.timeouts[party].ot:2-s.timeouts[party].reg;}
 function chargeTimeout(s,party='player'){if(s.round===0||s.round>=rounds(s)[s.map].length||timeoutLeft(s,party)<=0)return false;const bucket=s.round>=24?'ot':'reg';s.timeouts[party][bucket]++;s.coachWindow=party==='player'?'timeout':'opponent';return true;}
 function roundGrowth(s,win,cards){s.team.状态=clamp(s.team.状态+(win?.6:-.7));s.team.熟练=clamp(s.team.熟练+.04);const ps=s.roster.map(k=>cards.find(p=>key(p)===k));for(let i=0;i<5;i++)for(let j=i+1;j<5;j++){const id=pair(ps[i].playerId,ps[j].playerId);s.rapport[id]=clamp((s.rapport[id]||0)+.025);}s.team.羁绊=bond(s,ps);}
 function settleMap(s,cards){const id=`${s.year}:${s.phase}:map:${s.map}`;if(s.ledger.includes(id)||s.round<rounds(s)[s.map].length)return false;const r=results(s)[s.map],mapId=[s.bp[2],s.bp[3],s.bp[6]][s.map];s.mapKnowledge[mapId]=clamp(s.mapKnowledge[mapId]+(r.win?1:-1));s.mapRecords.push({id,year:s.year,phase:s.phase,mapId,...r});s.ledger.push(id);return true;}
 function matchGrowth(s,cards,kind,win,number){const id=`${s.year}:${s.phase}:${kind}:${number}`;if(s.ledger.includes(id))return;const participants=[...s.roster];s.participation.push({id,year:s.year,phase:s.phase,kind,win,cards:participants});for(const k of participants){const p=cards.find(c=>key(c)===k);s.familiarity[p.playerId]=(s.familiarity[p.playerId]||0)+1+.01*s.coach.声望;}s.coach.战术=clamp(s.coach.战术+.25);s.coach.临场=clamp(s.coach.临场+(kind==='formal'?.5:.15));s.coach.声望=clamp(s.coach.声望+(win?.5:-.4));s.team.熟练=clamp(s.team.熟练+.7);s.team.状态=clamp(s.team.状态+(win?1:-1));s.team.羁绊=bond(s,participants.map(k=>cards.find(c=>key(c)===k)));s.ledger.push(id);}
 function settleStage(s,cards){const id=`${s.year}:${s.phase}:stage`;if(s.ledger.includes(id))return;const played=eligible(s);if(played&&!s.completedMatch)return;const win=results(s).filter(r=>r.win).length===2;if(played){matchGrowth(s,cards,'formal',win,0);matchGrowth(s,cards,'quick',true,1);matchGrowth(s,cards,'quick',false,2);}const place=!played?'未晋级':win?'示例阶段第 2':'示例本阶段止步';s.stageRecords.push({phase:s.phase,played,place,formal:played?1:0,quick:played?2:0,roster:played?[...s.roster]:[]});if(played&&win&&[1,4].includes(s.phase))s.honorRecords.push({id,year:s.year,phase:s.phase,title:s.phase===1?'大师赛① · 亚军（示例）':'大师赛② · 亚军（示例）',cards:[...s.roster]});s.ledger.push(id);s.history=true;}
 function finish(s){if(s.phase!==7||!s.ledger.includes(`${s.year}:7:stage`))return false;if(!s.seasons.some(y=>y.year===s.year)){const all=s.participation.filter(p=>p.year===s.year);s.seasons.push({year:s.year,club:s.club,place:eligible(s,7)?'冠军赛 · 示例阶段成绩':'未晋级冠军赛',roster:[...new Set(all.flatMap(p=>p.cards))],stages:JSON.parse(JSON.stringify(s.stageRecords)),coach:{...s.coach}});}s.run='finished';return true;}
 return {clamp,familiar,key,mapCatalog,init,bond,register,validate,rotate,eligible,resetMap,resetMatch,bpActor,fillOpponentBP,pendingSide,newRun,openReinforcement,reveal,results,rounds,score,timeoutLeft,chargeTimeout,roundGrowth,settleMap,matchGrowth,settleStage,finish};
});
