(() => {
 const D=DEMO,R=PROTOTYPE_RULES,F=FLOW_UI,A=ARCHIVE_UI,S=SEASON_2026,V=MAP_VETO,O=ROUND_OUTCOME;
 const note=t=>`<p class="rule-note">${t}</p>`,section=(t,b)=>`<section class="page-pad"><h3 class="page-heading">${t}</h3>${b}</section>`,metrics=o=>`<div class="team-state-metrics">${Object.entries(o).map(([k,v])=>`<div><b>${Math.round(v)}</b><span>${k}</span></div>`).join('')}</div>`;
 const use=(name,fn)=>{const prior=F[name];F[name]=s=>s.simulation==='live'?fn(s):prior(s);};
 const esc=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const drawArchive=ctx=>{const records=Object.values(ctx.stages).map(stage=>{const event=stage.regions?.CN,draw=event?.draw,parts=[];
 if(draw){if(draw.kind==='kickoff-pots')parts.push(note('按启点赛顺位两队一档，每档各一队进入两组。'));else parts.push(note('按第一赛段最终表现重排原组，交换第 '+draw.swaps.map(esc).join('、')+' 顺位。'));parts.push(draw.groups.map((ids,i)=>'<p><b>'+['Alpha','Omega'][i]+'</b> · '+ids.map(esc).join(' / ')+'</p>').join(''));}
 if(event?.seedingGames?.length)parts.push('<h4>CN 种子排位赛 · BO3</h4><div class="change-rows">'+event.seedingGames.map(g=>'<div><span>'+esc(g.a)+' / '+esc(g.b)+'</span><b>'+g.scoreA+' : '+g.scoreB+'</b></div>').join('')+'</div>'+note('同名次跨组对阵，胜者获得较高顺位；自动结算并计出场成长，不额外发冠军积分。'));
 if(stage.swiss?.draws?.length)parts.push(stage.swiss.draws.map(d=>'<p>瑞士第 '+d.round+' 轮 · '+esc(d.bucket.replace(':','胜 / '))+'负</p><div class="change-rows">'+d.pairs.map(pair=>'<div><span>'+pair.map(esc).join(' / ')+'</span></div>').join('')+'</div>').join(''));
 if(stage.playoffDraft?.length)parts.push('<h4>大师赛首轮选对手</h4>'+stage.playoffDraft.map(d=>'<p>'+d.order+'. '+esc(d.team)+' → '+esc(d.opponent)+'</p>').join(''));
 if(stage.groupDraw)parts.push(note('四个种子档，每组各一档、各一赛区；首轮一号对四号、二号对三号。')+stage.groupDraw.groups.map((ids,i)=>'<p><b>小组 '+String.fromCharCode(65+i)+'</b> · '+ids.map(esc).join(' / ')+'</p>').join(''));
 if(stage.playoffDraw)parts.push(note('小组第一对第二；同组队伍分在上下半区。')+stage.playoffDraw.pairs.map(pair=>'<p>'+pair.map(esc).join(' / ')+'</p>').join(''));
 return parts.length?'<details class="plain-details"><summary>'+esc(D.phases[stage.phase])+'</summary>'+parts.join('')+'</details>':'';
 }).join('');return '<details class="plain-details"><summary>抽签与种子记录</summary>'+note(ctx.version==='2026-season-2'?'只展示已完成阶段的实际签表；后续对阵随真实赛果生成。':'此赛年保留原签表规则；新征战采用更新后的抽签。')+(records||note('暂无已完成阶段的抽签记录。'))+'</details>';};
 const map=id=>D.allMaps.find(m=>m.id===id),FLOW_HOME_BASE=F.home;
 const oldOpponent=F.opponent;F.opponent=s=>s.simulation==='live'?s.opponentId||'待定':oldOpponent(s);
 const oldMatchMap=F.matchMap;F.matchMap=s=>s.simulation==='live'?map(R.mapsFor(s)[s.map])||D.maps[0]:oldMatchMap(s);
 use('home',s=>{if(['none','draft','reinforce','finished'].includes(s.run)){const v=FLOW_HOME_BASE(s);if(s.run==='finished')v.body=v.body.replace('冠军赛四强',s.seasons.find(y=>y.year===s.year)?.place||'赛年完成');return v;}const stage=s.stageRecords.find(r=>r.phase===s.phase),pending=s.stageSession?.pending,participating=R.eligible(s),resume=window.VM_NAV?.resume(s)||'campaign/prepare';return {title:'征战',body:section(`第 ${s.year} 赛年 · ${D.phases[s.phase]}`,`${stage?note(stage.place):pending?`<div class="match-panel"><span class="phase-label">${pending.grandFinal?'晋级总决赛':'本阶段比赛'}</span><h3>${s.club} <span>VS</span> ${F.opponent(s)}</h3><span class="match-format">BO${s.bestOf}</span>${pending.grandFinal?note('决赛三胜夺冠。'+(s.playerUpper?'胜者组优势：两次禁图并选择 A/B。':'对手为胜者组队伍，拥有两次禁图和顺位选择权。')):note('')}</div>`:note(participating?'本阶段快速比赛已完成。':'本阶段未晋级，其他队伍仍正常完成赛事。')}<button class="blue-button full" ${stage?'data-go="campaign/stage-result"':s.run==='match'&&!s.completedMatch?'data-go="'+resume+'"':pending?'data-go="'+resume+'"':'data-action="settle-skipped"'}>${stage?'查看阶段结算':s.run==='match'&&!s.completedMatch?(resume==='campaign/match'?'继续比赛':'继续准备 →'):pending?'继续备战 →':'结算并继续赛年 →'}</button><div class="stage-track">${D.phases.map((p,i)=>`<span title="${p}" class="${i<s.phase?'done':i===s.phase?'current':''}"></span>`).join('')}</div>${metrics(s.team)}<div class="home-shortcuts"><button data-go="campaign/calendar">赛历 →</button><button data-go="campaign/standings">赛事与积分 →</button><button data-go="team/maps">地图池 →</button></div>`)};});
 function scoutCard(s){const info=R.opponentScout(s);if(info.origin==='unavailable')return note('本赛年尚无对手风格档案，可以通过比赛观察其执行倾向。');const labels=(side,title)=>`<div class="opponent-style-row"><b>${title}</b><div>${info[side].map(t=>`<span class="style-tag ${side}">${esc(t)}</span>`).join('')}</div></div>`;return `<section class="opponent-style" aria-label="对手队伍风格"><h4>对手擅长</h4>${labels('attack','进攻')}${labels('defense','防守')}<p>偏好地图：${info.maps.map(id=>esc(R.mapCatalog.find(m=>m.id===id)?.name||id)).join('、')}</p><small>赛年随机风格。擅长方向会在暂停后调整。</small></section>`;}
 use('prepare',s=>({title:'赛前备战',body:section(D.phases[s.phase],`<div class="versus"><strong>${s.club}</strong><span>VS</span><strong>${F.opponent(s)}</strong></div>${metrics(s.team)}${scoutCard(s)}${s.seasonEngine.teams.find(t=>t.id===s.opponentId)?.players.some(p=>p.proxy)?note("对手有待定队员，暂用明确标记的游戏代理数值；不代表真实选手评分。"):""}${note(`BO${s.bestOf} · 地图 BP → 特工 → 战术。比赛中可在暂停或中场调整。`)}${s.grandFinal?note('总决赛：胜者组两禁并选择 A/B，随后交替选四图，剩余为图五。'):''}`),dock:'开始地图 BP →',go:'campaign/bp'}));
 use('bp',s=>{const v=s.veto,steps=V.sequence(v),i=v.moves.length,own=a=>a===v.playerRole?'我方':'对方',title=i>=7?'本场地图':own(steps[i].actor)+(steps[i].kind==='ban'?'禁用':'选择图 '+(steps[i].map+1));return {title:'地图 BP',body:section(title,`<div class="flow-kicker"><span>BO${s.bestOf} · 我方 ${v.playerRole}</span><b>${Math.min(i+1,7)} / 7</b></div>${v.canChoose&&i===0?`<div class="segmented"><button data-bp-role="A" aria-pressed="${v.playerRole==='A'}">先选图</button><button data-bp-role="B" aria-pressed="${v.playerRole==='B'}">后选图</button></div>`:note(s.grandFinal?'胜者组拥有两次禁图和顺位选择权。':'较高种子选择先后手。')}${i>=7?`<div class="chosen-maps">${R.mapsFor(s).map((id,j)=>`<div class="chosen-map">${D.art(map(id))}<div><small>图 ${j+1}</small><strong>${map(id).name}</strong><span>${s.sideChosen[j]?'我方'+(s.sides[j]==='attack'?'进攻':'防守')+'开局':'待选择开局攻防'}</span></div></div>`).join('')}</div>`:`<div class="map-grid">${D.maps.map(m=>`<button data-map="${m.id}" aria-pressed="${s.pendingMap===m.id}" ${v.moves.includes(m.id)?'disabled':''}>${D.art(m)}<strong>${m.name}</strong><small>${v.moves.includes(m.id)?(()=>{const n=v.moves.indexOf(m.id),step=steps[n];return step.kind==='ban'?own(step.actor)+'禁用':'图 '+(step.map+1)+' · '+own(step.actor)+'选择';})():'我方地图分 '+Math.round(m.score)}</small></button>`).join('')}</div>`}<details class="plain-details"><summary>已完成的禁选步骤</summary><ol class="bp-history">${v.moves.map((id,n)=>`<li><span>${steps[n].kind==='decider'?'决胜图':own(steps[n].actor)+(steps[n].kind==='ban'?'禁用':'选择')}</span><strong>${map(id).name}</strong></li>`).join('')}</ol></details><details class="plain-details"><summary>禁选规则</summary>${note(s.bestOf===5?s.grandFinal?'胜者组禁两张；A / B / A / B 选四图；图五 B 选边。':'A、B 各禁一张；交替选四图；图五 B 选边。':'A、B 各禁一张；交替选图；再各禁一张；图三 A 选边。')}</details>`),dock:i>=7?(R.pendingSide(s)!==undefined?'图 '+(R.pendingSide(s)+1)+' · 选择攻防 →':'图一 · 选择特工 →'):s.pendingMap?'确认'+(steps[i].kind==='ban'?'禁用':'选图'):'先选择一张地图',action:i>=7?'bp-complete':'bp-confirm',disabled:i<7&&!s.pendingMap};});
 use('match',s=>{const m=s.liveMaps[s.map],round=m?.rounds.at(-1),over=R.mapOver(s),[h,a]=R.score(s),current=F.matchMap(s),presentation=window.ROUND_PRESENTATION?.mode(s)||{},brief=window.ROUND_PRESENTATION?.brief(m)||{headline:round?.win?'赢下回合':'丢掉回合',facts:round?[round.reason]:[]},pauseBlocked=over||!s.round||s.coachWindow||R.timeoutLeft(s)<=0||m?.spatial&&m.spatial.boundary?.canRequestTimeout===false;return {title:'比赛',body:section('',`<div class="match-context"><strong>${current.name}</strong><span>图 ${s.map+1} / BO${s.bestOf}</span></div><div class="live-score"><span>${s.club}</span><b>${h}<i>:</i>${a}</b><span>${F.opponent(s)}</span></div><div class="round-report ${round?.win?'round-win':'round-loss'}" aria-live="polite"><span>${round?'第 '+round.number+' 分 · '+(round.side==='attack'?'进攻':'防守')+(presentation.key?' · '+presentation.key:''):'准备开赛'}</span><h3>${round?(round.win?'赢下这一分':'丢掉这一分')+(['赢下回合','丢掉回合'].includes(brief.headline)?'':' · '+brief.headline):'双方准备就绪'}</h3>${brief.facts.map(text=>'<p>'+esc(text)+'</p>').join('')}${round?`<small>我方 ${round.ownTactic}<br>对方 ${round.opponentTactic}</small>`:''}</div>${m?.spatial?'':D.plan(current)}<div class="match-team-state" aria-label="队伍状态">${Object.entries(s.team).map(([k,n])=>'<span>'+k+' <b>'+Math.round(n)+'</b></span>').join('')}</div>${s.coachWindow?`<section class="coach-window"><b>${s.coachWindow==='opponent'?'对方暂停 · 双方可调整':s.coachWindow==='half'?'中场 · 交换攻防':'我方战术暂停'}</b><p>${s.coachWindow==='opponent'?'不扣我方暂停次数。':s.coachWindow==='half'?'可免费调整攻防优先级。':'调整影响后续回合。'}</p><button class="quiet-button full" data-action="resume-window">保留战术，继续</button></section>`:''}<div class="match-controls"><button data-action="play-toggle" aria-pressed="${!!s.playing}" ${over||s.coachWindow?'disabled':''}>${s.playing?'暂停自动推进':'自动推进'}</button><button data-action="timeout" ${pauseBlocked?'disabled':''}>${s.round>=24?'加时':'战术'}暂停 · ${Math.max(0,R.timeoutLeft(s))}</button><button data-action="skip-map" ${over||s.coachWindow?'disabled':''}>快进到结算</button><button data-action="save-exit">保存并退出</button></div><details class="plain-details"><summary>回合记录 · ${s.round} 分</summary><ol class="round-log">${(m?.rounds||[]).slice().reverse().map(r=>`<li><span>${r.number}</span><b class="${r.win?'won':'lost'}">${r.home} : ${r.away}</b><small>${r.reason}</small></li>`).join('')}</ol></details>`),dock:over?'查看本图结算 →':s.coachWindow?'调整战术 →':'下一回合 · 直接看比分 →',...(over?{go:'campaign/map-result'}:{action:s.coachWindow?'adjust-window':'next-round'})};});
 use('mapResult',s=>{const index=s.reviewMap??s.map,m=s.liveMaps[index],win=m.home>m.away;return {title:'单图结算',body:section(map(m.mapId).name,`<div class="result-hero"><span>图 ${index+1}</span><h3>${win?'拿下这张图':'本图失利'}</h3><strong>${m.home} <i>:</i> ${m.away}</strong></div>${metrics(s.team)}${note('实际地图结果已记入地图分和队伍成长。'+(R.seriesOver(s)?'系列赛已分出胜负。':'下一张图沿用战术，仅需确认特工。'))}`),dock:s.reviewMap!==null?'返回系列赛结果 →':R.seriesOver(s)?'查看系列赛结果 →':'下一图 · 选择特工 →',...(s.reviewMap!==null?{go:'campaign/series-result'}:{action:'next-map'})};});
 use('series',s=>{const rows=R.results(s),wins=rows.filter(r=>r.win).length;return {title:'系列赛结算',body:section('本场 BO'+s.bestOf,`<div class="result-hero ${s.grandFinal&&wins>rows.length-wins?'champion-result':''}">${s.grandFinal&&wins>rows.length-wins?`<span class="champion-trophy">${F.medal('trophy')}</span>`:''}<span>${D.phases[s.phase]}${s.grandFinal?' · 总决赛':''}</span><h3>${wins>(rows.length-wins)?s.grandFinal?'捧起冠军奖杯':'赢下系列赛':'本场失利'}</h3><strong>${wins} <i>:</i> ${rows.length-wins}</strong></div><div class="series-maps">${rows.map((r,i)=>`<button data-result-map="${i}"><span>图 ${i+1}</span><strong>${map(r.mapId).name}</strong><b>${r.home} : ${r.away}</b></button>`).join('')}</div>${note('只记录实际进行的地图。正式赛果将改变签表之后的对阵、晋级与积分；双败首败可能落入败者组，出局后不再参加该赛事。')}`),dock:'结算本阶段其余比赛 →',action:'settle-stage'};});
 use('calendar',s=>({title:'赛年赛历',body:section('2026 征战',`<ol class="full-calendar">${D.phases.map((name,i)=>{const rec=s.stageRecords.find(r=>r.phase===i);return `<li class="${s.phase===i?'current':''}"><span>${i+1}</span><div><strong>${name}</strong><small>${rec?.place||(!R.eligible(s,i)?'未晋级':i===s.phase?'当前阶段':'等待赛果')}${[1,4].includes(i)?' · 结束后补强':''}</small></div></li>`;}).join('')}</ol>${note('常规赛与签表其余对局快速模拟，每阶段执教一场；若实际晋级总决赛，追加正式 BO5。第二赛段常规赛包含后台入围赛，界面仍保留八大阶段。')}`),dock:'返回征战',go:'campaign'}));
 use('standings',s=>{if(!s.seasonEngine)return {title:'赛事与积分',body:section('尚未开始赛年',note('完成开包组队后生成赛事签表与积分。')),dock:'返回征战',go:'campaign'};const points=S.pointStandings(s.seasonEngine,'CN'),games=Object.values(s.stageSession?.committed||{}).map(i=>({...i.node,...i.result,kind:i.kind}));return {title:'赛事与积分',body:section('CN 冠军赛积分',`<div class="change-rows">${points.map(t=>`<div><span>${t.id===s.club?'★ ':''}${t.id}</span><b>${t.points} 分</b></div>`).join('')}</div>${note('冠军赛：第二赛段前二直通，剩余队伍取积分前二。同分先比较第二赛段、大师赛②、第一赛段、大师赛①、启点赛等成绩。')}<h4>当前阶段已进行的对局</h4><div class="change-rows">${games.map(g=>`<div><span>${g.a} / ${g.b}<small> · ${g.kind==='formal'?'正式':'快速'} BO${g.bestOf}</small></span><b>${g.scoreA} : ${g.scoreB}</b></div>`).join('')}</div>${drawArchive(s.seasonEngine)}`),dock:'返回征战',go:'campaign'};});
 use('stage',s=>{const r=s.stageRecords.find(r=>r.phase===s.phase);return {title:'阶段结算',body:section(D.phases[s.phase],`<div class="result-hero"><h3>${r?.place||'等待结算'}</h3><p>${r?.formal||0} 场正式 · ${r?.quick||0} 场快速</p></div>${metrics(s.team)}${note('CN 冠军赛积分：'+(s.seasonEngine.points[s.club]||0)+'。资格由赛事结果决定，不由单场胜负直接指定。')}${[1,4].includes(s.phase)?note('大师赛已结束，无论是否参赛，都获得一个补强包。'):''}`),dock:s.phase===7?'查看赛年收获 →':[1,4].includes(s.phase)?'开启本次补强包 →':'进入下一阶段 →',action:'advance-stage'};});
})();
