const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
// Keep these historical numerical UI regressions independent of the published model.
function load(){const sandbox={structuredClone,console,Math};sandbox.window=sandbox;vm.createContext(sandbox);for(const name of ['../art-direction-01/players.js','../art-direction-03/pack-samples.js','../art-direction-03/collection-samples.js','../art-direction-03/card-renderer.js','trait-snapshot.js','card-view.js','profile-view.js','cn-snapshot.js','demo-data.js','content-snapshot.js','../../../游戏/agent-selection.js','../../../游戏/map-veto.js','spatial-engine.js','../../../游戏/team-style.js','../../../游戏/map-baseline.js','../../../游戏/stage-feedback.js','../../../游戏/content-defaults.js','../../../游戏/round-outcome.js','../../../游戏/tournament.js','../../../游戏/season-2026.js','../../../游戏/progression.js','prototype-rules.js','aligned-data.js','runtime-model.js','flow-view.js','archive-view.js','aligned-views.js','followup-views.js','runtime-views.js','progression-views.js','runtime-fixtures.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,name),'utf8'),sandbox,{filename:name});sandbox.SPATIAL_MATCH.campaignPolicy=()=>null;return sandbox;}
function begin(x){const {DEMO:D,PROTOTYPE_RULES:R}=x,s=D.seed();R.newRun(s,x.CN_CONTENT,x.CN_DRAW,()=>.73);s.opened=[10,10,10];s.chosenPack=0;s.unlocked=[...new Set(s.packs.flat())];R.register(s,D.demoRoster(),D.cards);s.unlocked=[...new Set([...s.unlocked,...s.roster])];R.prepareSeason(s);R.resetMatch(s);D.sync(s);return s;}
function bp(x,s){const R=x.PROTOTYPE_RULES;while(s.bp.length<7)R.bpMove(s,s.activeMaps.find(m=>!s.bp.includes(m)));let i;while((i=R.pendingSide(s))!==undefined)R.setSide(s,i,'attack');}
test('live templates and compact pack/album templates render with no invented future results',()=>{
 const x=load(),{DEMO:D,PROTOTYPE_RULES:R,FLOW_UI:F,ARCHIVE_UI:A}=x,s=begin(x);
 assert.equal(s.spatialEnabled,false,'legacy numerical UI fixture preserves its model');
 for(const name of ['home','prepare','bp','calendar','standings']){const v=F[name](s);assert(!v.body.includes('undefined'),name);}
 assert(F.home({...s,run:'draft'}).body);assert(F.packs(s).body.includes('pack-thumb-grid'));assert(!F.packs(s).body.includes('finish-pack'));assert(!F.reveal(s).body.includes('finish-pack'));assert(A.album(s).body.includes('class="thumb-grid album-thumb-grid" id="album-results"'));
 bp(x,s);s.agents={0:Object.fromEntries(s.roster.map((k,i)=>[k,x.AGENT_SELECTION.recommend(F.lineup(s),x.CN_CONTENT.agents,F.matchMap(s).id).agents[i]]))};R.startMap(s);assert.equal(R.results(s).length,0);assert(F.match(s).body.includes('准备开赛'));assert(F.agents(s).body.includes('★ 招牌'));assert(F.match(s).body.includes('data-map-plan'));assert.equal(F.match(s).action,'next-round');
});
test('entire live campaign persists actual map/participation facts and stays idempotent across refresh and GF',()=>{
 const x=load(),{DEMO:D,PROTOTYPE_RULES:R,FLOW_UI:F}=x;let s=begin(x);let formal=0;
 for(let phase=0;phase<8;phase++){s.phase=phase;R.rotate(s,phase,()=>.73);R.prepareStage(s);R.resetMatch(s);let guard=0;
 while(s.stageSession.pending){assert(++guard<4);bp(x,s);s.run='match';for(;;){s.agents[s.map]=Object.fromEntries(s.roster.map((k,i)=>[k,x.AGENT_SELECTION.recommend(F.lineup(s),x.CN_CONTENT.agents,F.matchMap(s).id).agents[i]]));R.startMap(s);let n=0;while(!R.mapOver(s)){assert(++n<500);R.stepRound(s);if(s.round===8||s.round===12)R.adaptOpponent(s);if(s.round===3){const old=JSON.stringify(s.liveMaps[s.map].rounds);R.compact(s);s=JSON.parse(JSON.stringify(s));R.init(s);assert.equal(JSON.stringify(s.liveMaps[s.map].rounds),old);}}
 const snapshot=JSON.stringify([s.mapRecords,s.mapKnowledge,s.familiarity]);R.settleMap(s,D.cards);assert.equal(JSON.stringify([s.mapRecords,s.mapKnowledge,s.familiarity]),snapshot);assert(!F.mapResult(s).body.includes('undefined'));
 if(R.seriesOver(s)){s.completedMatch=true;R.submitFormal(s);formal++;assert(!F.series(s).body.includes('undefined'));break;}s.map++;R.resetMap(s);}
 const ended=R.settleStage(s,D.cards);if(ended)break;}
 if(!s.stageRecords.some(r=>r.phase===phase))assert(R.settleStage(s,D.cards));const count=s.participation.length,values=JSON.stringify(s.familiarity);assert(R.settleStage(s,D.cards));assert.equal(s.participation.length,count);assert.equal(JSON.stringify(s.familiarity),values);
 }
 R.compact(s);assert(Buffer.byteLength(JSON.stringify(s))<2_000_000,'full campaign exceeds browser save budget');assert.equal(s.stageRecords.length,8);assert(R.finish(s));assert(R.finish(s));assert.equal(s.seasons.length,1);assert.equal(s.participation.filter(p=>p.kind==='formal').length,formal);assert.equal(new Set(s.mapRecords.map(r=>r.id)).size,s.mapRecords.length);for(const value of Object.values(s.team))assert(value>=0&&value<=100);
});
test('fixture chapter preview retains its old sample behavior and live start is explicitly separate',()=>{const x=load(),s=begin(x);s.simulation='fixture';s.scenario='miss-world';s.phase=1;s.run='active';assert(!x.PROTOTYPE_RULES.eligible(s));assert(x.FLOW_UI.home(s).body.includes('未晋级'));});
test('nine real map posters and layouts match their recorded Riot URLs and content hashes',()=>{const crypto=require('node:crypto'),base=path.resolve(__dirname,'../../../素材库/地图官方'),manifest=JSON.parse(fs.readFileSync(path.join(base,'sources.json')));assert.equal(Object.keys(manifest).length,9);for(const [id,m] of Object.entries(manifest)){assert(m.source.startsWith('https://playvalorant.com/'));for(const [file,url,hash] of [[id+'.webp',m.posterUrl,m.sha256],[id+'-plan.webp',m.planUrl,m.planSha256],[id+'-poster.webp',m.bpPosterUrl,m.bpPosterSha256]]){assert(url.startsWith('https://cmsassets.rgpub.io/'));assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.join(base,file))).digest('hex'),hash);}assert.equal(m.geometryStatus,'not-validated');assert.equal(m.bpPosterKind,'official-gameplay-gallery');assert.equal(m.bpPoster,'地图官方/'+id+'-poster.webp');}});
test('quick-win streak state stays bounded near neutral and tie-only participants are not Champions entrants',()=>{const x=load(),s=begin(x),R=x.PROTOTYPE_RULES;for(let i=0;i<500;i++)R.roundGrowth(s,true,x.DEMO.cards);assert(s.team.状态<70);s.phase=7;s.seasonEngine.stages[7]={participants:['AG','XLG']};assert(!R.eligible(s,7));s.seasonEngine.stages[7].participants.push(s.club);assert(R.eligible(s,7));});
test('real seeded review finals exercise upper and lower BO5 authority, five maps and trophy settlement',()=>{for(const lower of [false,true]){const x=load(),s=begin(x),{PROTOTYPE_RULES:R,FLOW_UI:F,DEMO:D}=x;x.SEASON_REVIEW.final(s,lower);assert.equal(s.bestOf,5);assert.equal(s.playerUpper,!lower);assert.equal(s.veto.canChoose,!lower);assert(F.home(s).body.includes('BO5'));assert(F.bp(s).body.includes('图五'));bp(x,s);assert.equal(R.mapsFor(s).length,5);for(let i=0;i<3;i++){s.map=i;const m=x.ROUND_OUTCOME.create('win'+i,R.mapsFor(s)[i]);m.home=13;m.away=7;s.liveMaps[i]=m;R.settleMap(s,D.cards);}assert(R.seriesOver(s));assert.equal(R.results(s).length,3);s.completedMatch=true;R.submitFormal(s);assert(F.series(s).body.includes('捧起冠军奖杯'));assert(R.settleStage(s,D.cards));assert.equal(s.stageRecords.at(-1).place,'第 1 名');assert(s.honorRecords.at(-1).title.includes('冠军'));}});
test('Ascent review follows a real legal matchup, fixed hero picks and fine-engine timeout budgets',()=>{
 const x=load(),s=begin(x),R=x.PROTOTYPE_RULES;x.SEASON_REVIEW.spatial(s);
 assert.equal(R.mapsFor(s)[0],'ascent');assert.equal(s.liveMaps[0].rounds[0].engine,'spatial-ascent-v1');
 assert(R.chargeTimeout(s));assert(!R.chargeTimeout(s));const snapshot=JSON.parse(JSON.stringify(s));
 s.coachWindow='';snapshot.coachWindow='';assert.deepEqual(JSON.parse(JSON.stringify(R.stepRound(s))),JSON.parse(JSON.stringify(R.stepRound(snapshot))));assert.equal(R.timeoutLeft(s),1);
 while(!R.mapOver(s))R.stepRound(s);assert(s.round<100);assert(R.mapOver(s));assert(!R.chargeTimeout(s));assert.equal(s.mapRecords.length,1);
 assert(Buffer.byteLength(JSON.stringify(s))<2_000_000);
});

test('draw archive renders only completed stages and reading does not change scores or growth',()=>{const x=load(),s=begin(x),F=x.FLOW_UI,R=x.PROTOTYPE_RULES;const before=JSON.stringify(s);assert(F.standings(s).body.includes('暂无已完成阶段'));assert.equal(JSON.stringify(s),before);x.SEASON_REVIEW.final(s,false);const snapshot=JSON.stringify(s),body=F.standings(s).body;assert(body.includes('抽签与种子记录'));assert(body.includes('CN 种子排位赛'));assert(body.includes('Alpha'));assert(!body.includes('undefined'));assert(!body.includes('小组 A'));assert.equal(JSON.stringify(s),snapshot);const count=s.participation.length;R.prepareStage(s);assert.equal(s.participation.length,count);});
