/* Adapter: chapters keep isolated examples; new campaigns use the season and
   live round models. Facts are committed once and survive refresh. */
(() => {
 const R=PROTOTYPE_RULES,S=SEASON_2026,O=ROUND_OUTCOME,V=MAP_VETO,D=DEMO;
 const H=TEAM_STYLE,G=PROGRESSION,old={...R},key=R.key,live=s=>s.simulation==='live';
 R.init=s=>{old.init(s);if(s.playbackDefaultsVersion==null){if(s.speed===1||![.5,1,2,4].includes(s.speed))s.speed=2;s.playbackDefaultsVersion=1;}if(![.5,1,2,4].includes(s.speed))s.speed=2;if(live(s))G.ensure(s,R.mapCatalog.map(m=>m.id));return s;};
 R.register=(s,list,cards)=>{if(!live(s))return old.register(s,list,cards);G.ensure(s,R.mapCatalog.map(m=>m.id));const previous=ownCards(s).map(p=>p.playerId),before=G.snapshot(s);old.register(s,list,cards);G.replace(s,ownCards(s).filter(p=>previous.includes(p.playerId)).length,cards);if(s.tacticalProfile)H.recruit(s.tacticalProfile,ownCards(s).filter(p=>previous.includes(p.playerId)).length);s.replacementGrowth={before,after:G.snapshot(s)};};
 R.roundGrowth=(s,win,cards)=>live(s)?G.round(s,win,cards):old.roundGrowth(s,win,cards);
 R.compact=s=>{if(!live(s))return;for(const item of Object.values(s.stageSession?.committed||{})){const own=item.node.a===s.club||item.node.b===s.club;if(!own||s.ledger.includes(`${s.year}:season:${item.node.id}`))for(const map of item.result.maps){delete map.rounds;if(!own&&s.seasonEngine.styleVersion){delete map.tacticUsage;delete map.predictions;delete map.coachSnapshots;}}}for(const stage of Object.values(s.seasonEngine?.stages||{}))for(const game of stage.games)for(const map of game.maps||[]){delete map.rounds;if(s.seasonEngine.styleVersion&&game.a!==s.club&&game.b!==s.club){delete map.tacticUsage;delete map.predictions;delete map.coachSnapshots;}}};
 const ownCards=s=>s.roster.map(k=>D.cards.find(p=>key(p)===k));
 const playerTeam=s=>({id:s.club,players:ownCards(s),team:s.team,coach:s.coach,...(s.tacticalProfile?{tacticalProfile:s.tacticalProfile,tacticPriorities:priority(s)}:{})});
 const priority=s=>Object.fromEntries(['attack','defense'].map(side=>[side,s[side].map(t=>O.names[side].indexOf(t))]));
 R.preflightNewRun=()=>window.SPATIAL_MATCH.campaignPolicy?.()??null;
 R.newRun=(s,...args)=>{const release=R.preflightNewRun();old.newRun(s,...args);s.simulation='live';s.spatialCampaignPolicy=release;s.spatialEnabled=!!s.spatialCampaignPolicy;s.spatialVersion=s.spatialCampaignPolicy?6:null;s.spatialPreviewBehaviorVersion=null;s.seasonEngine=null;s.stageSession=null;s.liveMaps=[];s.matchToken=null;s.bestOf=3;s.grandFinal=false;s.fastForward=false;s.annualGrowth=null;s.tacticalProfile=H.create('new-year',s.club,{neutral:true});G.resetYear(s,R.mapCatalog.map(m=>m.id));};
 function updateHome(s){const t=s.seasonEngine.teams.find(t=>t.id===s.club);t.players=structuredClone(ownCards(s));t.team={...s.team};t.coach={...s.coach};t.mapKnowledge={...s.mapKnowledge};if(s.seasonEngine.styleVersion){t.tacticalProfile=structuredClone(s.tacticalProfile);t.tacticPriorities=priority(s);}}
 function ingest(s){for(const [id,item]of Object.entries(s.stageSession.committed)){
  if(item.node.a!==s.club&&item.node.b!==s.club)continue;const token=`${s.year}:season:${id}`;if(s.ledger.includes(token))continue;const home=item.node.a===s.club,win=item.result.winner===s.club;
  if(item.kind==='quick')for(const [i,map]of item.result.maps.entries()){
   const m={mapId:map.mapId,home:home?map.home:map.away,away:home?map.away:map.home,rounds:(map.rounds||[]).map(r=>({...r,win:home?r.win:!r.win,probability:Number.isFinite(r.probability)?home?r.probability:1-r.probability:undefined}))};
   const pred=map.predictions,convert=p=>home?p:1-p,standard=pred?.standards?.[home?'home':'away']??(home?pred?.standard:undefined);
   G.beginMap(s,m,D.cards,{kind:'quick',expected:pred?convert(pred.expected):.5,plannedExpected:pred?convert(pred.expected):undefined,standardExpected:Number.isFinite(standard)?convert(standard):undefined,coach:{声望:map.coachSnapshots?.[home?'home':'away']??s.coach.声望}});
   const r=G.settleMap(s,m,D.cards,token+':map:'+i,{quick:true});if(r)r.matchId=id;
  }
  const record=G.settleMatch(s,D.cards,{id:`${s.year}:${s.phase}:${item.kind}:${id}`,matchId:id,kind:item.kind,win,mapRecords:s.mapRecords.filter(r=>r.year===s.year&&r.matchId===id&&r.players)});
  if(record){record.bestOf=item.result.bestOf;record.eventParticipation=!(s.phase===7&&item.node.label==='同分加赛');}if(s.seasonEngine.styleVersion&&item.kind==='quick')s.tacticalProfile=structuredClone(s.seasonEngine.teams.find(t=>t.id===s.club).tacticalProfile);s.ledger.push(token);
 }}
 R.prepareSeason=s=>{if(!live(s))return;if(!s.seasonEngine)s.seasonEngine=S.create(Math.floor(Math.random()*2**32),CN_CONTENT.rosters,CN_CONTENT.globalCards,s.club);if(s.seasonEngine.closureVersion&&!s.seasonEngine.ruleVerification)s.seasonEngine.ruleVerification=structuredClone(CN_CONTENT.competitionProvenance);R.prepareStage(s);};
 R.prepareStage=s=>{if(!live(s))return;updateHome(s);if(!s.stageSession||s.stageSession.phase!==s.phase){s.stageSession=S.prepare(s.seasonEngine,s.phase,s.activeMaps);S.progress(s.seasonEngine,s.stageSession,s.activeMaps);ingest(s);}const node=s.stageSession.pending;s.bestOf=node?.playedBestOf||3;s.grandFinal=!!node?.grandFinal;s.playerUpper=node?.upperTeam===s.club;s.opponentId=node?.opponent||null;s.priorityAuthority=node?node.grandFinal?s.playerUpper:(node.higherSeed||node.a)===s.club:true;};
 R.eligible=(s,phase=s.phase)=>{if(!live(s))return old.eligible(s,phase);if(phase===7&&s.seasonEngine?.stages[7])return s.seasonEngine.stages[7].participants.includes(s.club);if(phase===s.phase&&s.stageSession)return !!s.stageSession.pending||Object.values(s.stageSession.committed).some(i=>i.node.a===s.club||i.node.b===s.club);const ctx=s.seasonEngine;if(!ctx)return true;if([0,2,5].includes(phase))return true;if([1,4].includes(phase)){const prior=ctx.stages[phase===1?0:3];return !prior||prior.regions.CN.placements.flat().slice(0,3).includes(s.club);}if(phase===3)return !ctx.stages[2]||ctx.stages[2].regions.CN.seeds.slice(0,8).includes(s.club);if(phase===6)return !ctx.stages[5]||[...ctx.stages[5].regions.CN.direct,...ctx.stages[5].regions.CN.playin.qualified].includes(s.club);if(phase===7){if(!ctx.stages[6])return true;const direct=ctx.stages[6].regions.CN.placements.flat().slice(0,2);return [...direct,...S.pointStandings(ctx,'CN').filter(t=>!direct.includes(t.id)).slice(0,2).map(t=>t.id)].includes(s.club);}return false;};
 R.resetMatch=s=>{old.resetMatch(s);if(live(s)){s.liveMaps=[];s.bestOf=s.stageSession?.pending?.playedBestOf||3;s.matchToken=s.stageSession?.pending?.id||null;s.sides=Array(s.bestOf).fill('attack');s.veto=V.create(s.activeMaps,{bestOf:s.bestOf,grandFinal:s.grandFinal,playerUpper:s.playerUpper,playerRole:s.priorityAuthority?'A':'B',canChoose:s.priorityAuthority});s.bpRole=s.veto.playerRole;s.sideChosen=Array(s.bestOf).fill(false);V.auto(s.veto,s.seasonEngine.teams.find(t=>t.id===s.opponentId)?.mapKnowledge);syncBP(s);}};
 function syncBP(s){s.bp=[...s.veto.moves];s.bpRole=s.veto.playerRole;s.sides=s.veto.sides.map(v=>v||'attack');s.sideChosen=s.veto.sides.map(Boolean);}
 R.chooseBPRole=(s,role)=>{if(!live(s))return;V.chooseRole(s.veto,role);V.auto(s.veto,s.seasonEngine.teams.find(t=>t.id===s.opponentId)?.mapKnowledge);syncBP(s);};
 R.bpActor=s=>live(s)&&s.veto?V.actor(s.veto):old.bpActor(s);
 R.fillOpponentBP=s=>{if(live(s)&&s.veto){V.auto(s.veto,s.seasonEngine.teams.find(t=>t.id===s.opponentId)?.mapKnowledge);syncBP(s);}else old.fillOpponentBP(s);};
 R.bpMove=(s,id)=>{if(V.actor(s.veto)!=='player')return;V.move(s.veto,id);V.auto(s.veto,s.seasonEngine.teams.find(t=>t.id===s.opponentId)?.mapKnowledge);syncBP(s);};
 R.pendingSide=s=>live(s)&&s.veto?V.pendingSide(s.veto):old.pendingSide(s);
 R.setSide=(s,map,side)=>{V.setSide(s.veto,map,side);syncBP(s);};
 R.mapsFor=s=>live(s)&&s.veto?V.maps(s.veto):[s.bp[2],s.bp[3],s.bp[6]];
 R.mapOver=s=>live(s)?!!s.liveMaps[s.map]&&O.ended(s.liveMaps[s.map].home,s.liveMaps[s.map].away):s.round>=old.rounds(s)[s.map].length;
 R.seriesOver=s=>{if(!live(s))return s.map>=old.results(s).length-1&&R.mapOver(s);const done=s.liveMaps.filter(m=>O.ended(m.home,m.away)),target=(s.bestOf+1)/2;return done.filter(m=>m.home>m.away).length>=target||done.filter(m=>m.away>m.home).length>=target;};
 R.startMap=s=>{if(!live(s))return;if(!s.liveMaps[s.map])s.liveMaps[s.map]=O.create(s.seasonEngine.seed+':'+s.matchToken+':map:'+s.map,R.mapsFor(s)[s.map],s.sides[s.map],s.seasonEngine.styleVersion?{model:H.version}:{});const m=s.liveMaps[s.map];if(!m.progression){const home={...playerTeam(s),mapKnowledge:s.mapKnowledge},rival=s.seasonEngine.teams.find(t=>t.id===s.opponentId),agents=s.agents[s.map]||{},ps=ownCards(s),fit=ps.reduce((n,p)=>n+AGENT_SELECTION.fit(p,agents[key(p)],m.mapId),0)/5;const expected=O.expected(home,rival,m.mapId,(fit-85)*.06),standardExpected=O.expected({...home,mapKnowledge:{}},rival,m.mapId);G.beginMap(s,m,D.cards,{expected,plannedExpected:expected,standardExpected,roundsSettled:m.rounds.length,legacy:m.rounds.length>0});}};
 R.results=s=>live(s)?s.liveMaps.filter(m=>O.ended(m.home,m.away)).map(m=>({home:m.home,away:m.away,win:m.home>m.away,mapId:m.mapId})):old.results(s);
 R.rounds=s=>live(s)?s.liveMaps.map(m=>m.rounds.map(r=>r.win)):old.rounds(s);
 R.score=s=>live(s)?[s.liveMaps[s.map]?.home||0,s.liveMaps[s.map]?.away||0]:old.score(s);
 R.spatialMap=s=>s.liveMaps?.[s.map]?.spatial;
 R.stepRound=s=>{R.startMap(s);const m=s.liveMaps[s.map],rival=s.seasonEngine.teams.find(t=>t.id===s.opponentId),members=ownCards(s),agents=s.agents[s.map]||{},home={...playerTeam(s),mapKnowledge:s.mapKnowledge};const fit=members.reduce((n,p)=>n+AGENT_SELECTION.fit(p,agents[key(p)],m.mapId),0)/5;if(!m.spatial&&s.spatialCampaignPolicy&&!s.spatialCampaignPolicy.versions?.[m.mapId])throw Error('赛年空间引擎缺少当前地图版本');const fine=m.spatial||(s.spatialEnabled&&!m.rounds.length&&SPATIAL_MATCH.available(m,home,rival)&&(s.spatialVersion===6||m.mapId==='ascent'));if(fine&&!m.spatial&&[3,4,5,6].includes(s.spatialVersion))SPATIAL_MATCH.initialize(m,home,rival,priority(s),agents,{version:s.spatialVersion===6&&m.mapId==='ascent'?5:s.spatialVersion,behaviorVersion:s.spatialCampaignPolicy?s.spatialCampaignPolicy.versions[m.mapId]:s.spatialEnabled?s.spatialPreviewBehaviorVersion:undefined});const round=fine?SPATIAL_MATCH.step(m,home,rival,priority(s),agents):O.step(m,home,rival,priority(s),(fit-85)*.06);s.round=m.rounds.length;if(fine){const b=m.spatial.boundary;for(const [party,k]of [['player','A'],['opponent','B']]){s.timeouts[party].reg=2-b.regulationTimeoutsLeft[k];s.timeouts[party].ot=b.isOvertime?1-b.overtimeTimeoutsLeft[k]:0;}s.coachWindow=b.matchOver?'':b.isHalftime?'half':b.timeoutCaller?'opponent':'';if(b.isHalftime)s.halftimeSeen=true;}R.roundGrowth(s,round.win,D.cards);m.progression.roundsSettled=m.rounds.length;if(s.round===12)G.window(s,m,'half',s.matchToken+':half:'+s.map);if(fine&&s.coachWindow==='opponent')G.window(s,m,'timeout',s.matchToken+':ai-timeout:'+s.map+':'+s.round);R.settleMap(s,D.cards);return round;};
 R.opponentScout=s=>{const t=s.seasonEngine?.teams.find(t=>t.id===s.opponentId);return H.scout(t?.tacticalProfile,t?.mapKnowledge);};
 R.adaptOpponent=s=>{if(live(s)&&s.liveMaps[s.map]&&!R.spatialMap(s))O.adapt(s.liveMaps[s.map]);};
 R.shouldOpponentTimeout=s=>{
  if(!live(s)||!s.seasonEngine?.styleVersion)return s.round===8&&!s.aiPaused||s.round===18&&R.score(s)[1]<R.score(s)[0]||s.round===26;
  const m=s.liveMaps[s.map];if(!m||R.mapOver(s)||s.coachWindow||R.timeoutLeft(s,'opponent')<=0||s.round-(m.opponentTimeoutAt??-99)<4)return false;
  const recent=m.rounds.slice(-6);let losing=0;for(let i=recent.length-1;i>=0&&recent[i].win;i--)losing++;
  return losing>=(s.round>=24?2:3)||recent.length===6&&recent.filter(r=>r.win).length>=4&&m.home>m.away;
 };
 R.chargeTimeout=(s,party='player')=>{if(!live(s))return old.chargeTimeout(s,party);if(R.spatialMap(s)){if(party!=='player'||!SPATIAL_MATCH.requestTimeout(s.liveMaps[s.map]))return false;s.timeouts.player[s.round>=24?'ot':'reg']++;s.coachWindow='timeout';G.window(s,s.liveMaps[s.map],'timeout',s.matchToken+':timeout:'+s.map+':'+s.round+':'+party);return true;}if(s.coachWindow||s.round===0||R.mapOver(s)||old.timeoutLeft(s,party)<=0)return false;s.timeouts[party][s.round>=24?'ot':'reg']++;s.coachWindow=party==='player'?'timeout':'opponent';if(party==='opponent'&&s.seasonEngine.styleVersion)s.liveMaps[s.map].opponentTimeoutAt=s.round;R.adaptOpponent(s);G.window(s,s.liveMaps[s.map],'timeout',s.matchToken+':timeout:'+s.map+':'+s.round+':'+party);return true;};
 R.settleMap=(s,cards)=>{if(!live(s))return old.settleMap(s,cards);if(!R.mapOver(s))return false;const id=`${s.year}:${s.matchToken}:map:${s.map}`,m=s.liveMaps[s.map],r=G.settleMap(s,m,cards,id);if(r){r.matchId=s.matchToken;if(s.tacticalProfile&&s.seasonEngine.styleVersion)H.settle(s.tacticalProfile,s.matchToken+':map:'+s.map,H.usage(m.rounds),m.home>m.away);}return !!r;};
 R.submitFormal=s=>{if(!live(s)||!R.seriesOver(s))return;const node=s.stageSession.pending;if(!node)return;const maps=s.liveMaps.map(m=>({mapId:m.mapId,home:m.home,away:m.away,win:m.home>m.away,rounds:m.rounds,...(s.seasonEngine.stageFeedbackVersion?{predictions:{expected:m.progression?.expected}}:{}),...(s.seasonEngine.styleVersion?{tacticUsage:{home:H.usage(m.rounds,true),away:H.usage(m.rounds,false)}}:{})})),ownWins=maps.filter(m=>m.win).length,oppWins=maps.length-ownWins,home=node.a===s.club;const result={scoreA:home?ownWins:oppWins,scoreB:home?oppWins:ownWins,winner:ownWins>oppWins?s.club:s.opponentId,loser:ownWins>oppWins?s.opponentId:s.club,bestOf:s.bestOf,maps:home?maps:maps.map(m=>({...m,home:m.away,away:m.home,win:!m.win,...(m.predictions?{predictions:{expected:1-m.predictions.expected}}:{}),...(m.tacticUsage?{tacticUsage:{home:m.tacticUsage.away,away:m.tacticUsage.home}}:{}),rounds:m.rounds.map(r=>s.seasonEngine.styleVersion?O.reverseRound(r):({...r,home:r.away,away:r.home,win:!r.win}))}))};S.submit(s.stageSession,result);updateHome(s);S.settleTeamResult(s.seasonEngine,node,result);window.STAGE_FEEDBACK?.settle(s.seasonEngine,node,result);ingest(s);};
 R.settleStage=(s,cards)=>{if(!live(s))return old.settleStage(s,cards);if(s.stageRecords.some(r=>r.phase===s.phase))return true;if(s.stageSession.pending&&!s.completedMatch)return false;updateHome(s);S.progress(s.seasonEngine,s.stageSession,s.activeMaps);ingest(s);if(s.stageSession.pending){R.prepareStage(s);R.resetMatch(s);return false;}const event=s.seasonEngine.stages[s.phase],regional=event.regions.CN,ownGames=event.games.filter(g=>g.a===s.club||g.b===s.club),facts=Object.values(s.stageSession.committed).filter(i=>i.node.a===s.club||i.node.b===s.club),placeIndex=S.rank(regional||event,s.club);const place=placeIndex===999?'未晋级':'第 '+placeIndex+' 名';s.stageRecords.push({phase:s.phase,played:([1,4,7].includes(s.phase)?event.participants.includes(s.club):ownGames.length>0),place:[2,5].includes(s.phase)?'常规赛第 '+(regional.seeds.indexOf(s.club)+1)+' 名':place,formal:facts.filter(i=>i.kind==='formal').length,quick:facts.filter(i=>i.kind==='quick').length,roster:ownGames.length?[...s.roster]:[],points:s.seasonEngine.points[s.club]||0});if(placeIndex<=3&&![2,5].includes(s.phase)){const participants=[...new Set(s.participation.filter(p=>p.year===s.year&&p.phase===s.phase&&p.eventParticipation!==false).flatMap(p=>p.cards))];s.honorRecords.push({id:`${s.year}:${s.phase}:honor`,year:s.year,phase:s.phase,title:D.phases[s.phase]+' · '+(['冠军','亚军','季军'][placeIndex-1]),cards:participants});}const growth=G.settleEvent(s,{id:`${s.year}:${s.phase}:stage`,phase:s.phase,rank:[2,5].includes(s.phase)?regional.seeds.indexOf(s.club)+1:placeIndex,total:regional?([2,5].includes(s.phase)?regional.seeds.length:regional.placements.flat().length):event.participants.length,played:([1,4,7].includes(s.phase)?event.participants.includes(s.club):ownGames.length>0),playoffs:[1,3,4,6,7].includes(s.phase),currentPlayers:G.members(s,cards)});s.stageRecords.at(-1).growth=growth;if(s.seasonEngine.stageFeedbackVersion){s.stageRecords.at(-1).stageFeedback=structuredClone(s.seasonEngine.stageFeedback);STAGE_FEEDBACK.reset(s.seasonEngine,null);}s.history=true;return true;};
 R.finish=s=>{if(!live(s))return old.finish(s);if(!s.stageRecords.some(r=>r.phase===7))return false;s.annualGrowth=G.settleYear(s,`${s.year}:annual-growth`)||s.annualGrowth;if(!s.seasons.some(y=>y.year===s.year))s.seasons.push({year:s.year,club:s.club,place:s.stageRecords.find(r=>r.phase===7).place,roster:[...new Set(s.participation.filter(p=>p.year===s.year).flatMap(p=>p.cards))],stages:structuredClone(s.stageRecords),coach:{...s.coach},points:s.seasonEngine.points[s.club]||0,growth:s.annualGrowth});s.run='finished';return true;};
})();
