const test=require('node:test'),assert=require('node:assert/strict'),{RoundSim}=require('../round'),{GameMap}=require('../gamemap'),{buildIntent}=require('../tactics'),{mulberry32}=require('../rng'),abilities=require('../abilities');
function round(){const base=new GameMap(require('../maps/ascent-combat-v5.json'),require('../maps/ascent-geometry-v5.json')),map=Object.create(base);map.data={...base.data,externalEffectsVersion:null,objectiveModel:'defuse-v2',behaviorModel:'ascent-balance-v1'};const units=side=>Array.from({length:5},(_,i)=>({id:side+':'+i,name:side+i,side,sideIdx:i,aim:70,sen:70,syn:70,gun:2,utils:0,armor:'heavy',mentality:0})),rng=mulberry32(42),events=[];const r=new RoundSim({map,atkUnits:units('atk'),defUnits:units('def'),atkFamily:'rush',defFamily:'hold',atkIntent:buildIntent(map,'atk','rush',rng),defIntent:buildIntent(map,'def','hold',rng),rng,hooks:{onRoundStart:[],beforeDecision:[],beforeKillRoll:[],onKill:[]},logger:e=>events.push(e)});return {r,events};}
function pair(first){const units=['atk','def'].map(side=>({id:side,side,name:side,alive:true,position:{x:side==='atk'?10:30,y:20},node:'site',skills:{},utils:1,aim:70,sen:70,syn:70,stun:0,gun:2,holdTicks:2})),events=[];const r={units:first==='atk'?units:units.slice().reverse(),t:0,map:{data:{strictSpatial:true,spatialFire:'shared-los',behaviorModel:'ascent-balance-v1'},engagements:{query:()=>({visible:1})}},lastFlashTick:{atk:-99,def:-99},stats:{utilsAtk:0,utilsDef:0,utilsByType:{flash:0}},rng:()=>0,thinkUse:()=>true,synFactor:()=>1,emit:(type,data)=>events.push({type,...data})};r.visibleEnemiesAt=u=>units.filter(e=>require('../observation').canObserve(r,u,e));require('../combat').resolveTimedFire.call(r);return {units,events};}
test('simultaneous contact starts both reaction clocks and both flashes regardless of side iteration',()=>{for(const first of ['atk','def']){const {units,events}=pair(first);assert.deepEqual(events.filter(e=>e.type==='contact').map(e=>e.side).sort(),['atk','def']);assert(units.every(u=>u.fireReadyAt!=null&&u.stun>0));}});
test('a planted objective cannot be picked back up by an attacker',()=>{const {r}=round(),u=r.atk[0];r.planted=true;r.plantSite='A';r.spike={carrier:null,node:'a_site',position:{...u.position}};u.node='a_site';r.doPickup(u);assert.equal(r.spike.carrier,null);assert.equal(r.spike.node,'a_site');assert(!r.atkCandidates(u).some(c=>c.action==='pickup'));});
test('defuse cover smoke is a physical occluder even after releasing the stance',()=>{const {r,events}=round(),u=r.def[0];u.node='a_site';u.position={x:184,y:610};u.post=null;r.spike.position={...u.position};u.skills={smoke:{left:1,def:{key:'q',name:'test smoke',archetype:'smoke',params:{}}}};r.rng=()=>.5;abilities.onDefuseSmoke(r,u);assert(r.geometrySmokes.some(s=>Math.hypot(s.x-u.position.x,s.y-u.position.y)<1));assert(events.some(e=>e.type==='smoke'&&e.cover));});
test('contact does not cancel a deliberate physical retreat into cover',()=>{
 const {r}=round(),u=r.def[0],a=r.atk[0];for(const v of r.units)if(v!==u&&v!==a)v.alive=false;u.node='a_site';u.position={x:184,y:610};a.node='a_lobby';a.position={x:180,y:570};u.moving={from:'a_site',to:'a_site',dest:'a_site',left:1,total:1,mode:'walk',post:null,purpose:'withdraw',route:[{...u.position},{x:185,y:610}]};r.resolveTimedFire();assert(u.moving);r.updateMovement();assert(u.position.x>184);assert(r.map.geometry.contains(u.position,{doors:r.doors}));
});
test('cover smoke blocks actual observation of the unanchored defuser',()=>{
 const {r}=round(),u=r.def[0],a=r.atk[0];u.node='a_site';u.position={x:184,y:610};u.post=null;a.position={x:180,y:570};a.post=null;r.spike.position={...u.position};u.skills={smoke:{left:1,def:{key:'q',name:'test smoke',archetype:'smoke',params:{}}}};r.rng=()=>.5;assert(require('../observation').canObserve(r,a,u));abilities.onDefuseSmoke(r,u);assert(!require('../observation').canObserve(r,a,u));
});
test('half defuse progress survives damage interruption and can be finished by a teammate',()=>{
 const {r,events}=round(),u=r.def[0],other=r.def[1];for(const a of r.atk)a.alive=false;r.planted=true;r.plantSite='A';r.spike={carrier:null,node:'a_site',position:{x:184,y:610}};u.position={...r.spike.position};u.node='a_site';r.execAction(u,{action:'defuse'});assert.equal(u.defusing,7);r.updatePlantDefuse();assert.equal(u.defusing,7);
 for(let i=1;i<=14;i++){r.t=i*.25;r.updatePlantDefuse();}assert.equal(r.spike.defuseProgress,3.5);u.hp--;r.t=3.75;r.updatePlantDefuse();assert.equal(u.defusing,0);
 other.node=u.node;other.position={...u.position};r.execAction(other,{action:'defuse'});assert.equal(other.defusing,3.5);for(let i=1;i<=14;i++){r.t=3.75+i*.25;r.updatePlantDefuse();}assert.equal(r.result.reason,'defuse');assert(events.some(e=>e.type==='defuse_checkpoint'));
});
test('defenders actively use area skills against cross-node contacts and damage stays local',()=>{
 const {r,events}=round();r.map.data.behaviorModel='ascent-balance-v2';const d=r.def[0],a=r.atk[0],far=r.atk[1];d.position={x:184,y:610};d.node='a_site';d.post=null;a.position={x:180,y:570};a.node='a_lobby';a.post=null;far.position={x:270,y:499};far.node='a_lobby';far.post=null;d.skills={grenade:{left:1,def:{key:'e',name:'area',archetype:'molly',params:{}}}};r.rng=()=>.5;
 const c=abilities.candidates(r,d).find(c=>c.skill.def.archetype==='molly');assert(c);abilities.exec(r,d,c.skill);assert.equal(r.damageZones.length,1);assert(events.some(e=>e.type==='molly_zone'&&e.side==='def'));assert(d.abilityBusyUntil>r.t);const old=far.hp;r.t=r.damageZones[0].activeAt+.5;require('../ascent-behavior').updateHazards(r);assert(a.hp<100);assert.equal(far.hp,old);assert(require('../ascent-behavior').hazardCandidate(r,a));
});
test('expired or wall-separated area effects do not damage a whole macro node',()=>{
 const {r}=round();r.map.data.behaviorModel='ascent-balance-v2';const owner=r.def[0],u=r.atk[0];u.position={x:180,y:570};u.node='a_lobby';r.damageZones=[{owner,position:{x:180,y:570},radius:28,until:.25,lastDamageAt:0,power:1}];r.t=.5;require('../ascent-behavior').updateHazards(r);assert.equal(u.hp,100);assert.equal(r.damageZones.length,0);
 u.position={x:590,y:663};u.node='market';r.doors['b-market-door']='closed';r.damageZones=[{owner,position:{x:542,y:663},radius:80,until:10,lastDamageAt:0,power:1}];assert(!r.map.geometry.canObserve(u.position,r.damageZones[0].position,{doors:r.doors}));require('../ascent-behavior').updateHazards(r);assert.equal(u.hp,100);
});
