const test=require('node:test'),assert=require('node:assert/strict'),{RoundSim}=require('../round'),{buildIntent}=require('../tactics'),registry=require('../maps/combat-registry'),{mulberry32}=require('../rng');
function planted(id='lotus',seconds=35){
 const base=id==='ascent'?new (require('../gamemap').GameMap)(require('../maps/ascent-combat-v5.json'),require('../maps/ascent-geometry-v5.json')):registry.get(id),map=Object.create(base);map.data={...base.data,externalEffectsVersion:null,objectiveModel:'defuse-v2'};
 const units=(side,key)=>Array.from({length:5},(_,i)=>({id:key+':'+i,name:key+i,side,sideIdx:i,aim:70,syn:70,sen:70,gun:2,utils:0,armor:'heavy',mentality:0}));
 const atk=units('atk','A'),def=units('def','B'),rng=mulberry32(42),events=[];
 const r=new RoundSim({map,atkUnits:atk,defUnits:def,atkFamily:'rush',defFamily:'hold',atkIntent:buildIntent(map,'atk','rush',rng),defIntent:buildIntent(map,'def','hold',rng),rng,hooks:{onRoundStart:[],beforeDecision:[],beforeKillRoll:[],onKill:[]},logger:e=>events.push(e)});
 r.start();for(const u of atk){u.alive=false;r.occ[u.node].delete(u);r.releasePost(u);}for(const u of def.slice(1)){u.alive=false;r.occ[u.node].delete(u);r.releasePost(u);}const u=def[0],node=map.siteNode('A');r.occ[u.node].delete(u);r.releasePost(u);u.node=node;const post=Object.values(map.posts).filter(p=>p.node===node).sort((a,b)=>Math.hypot(b.x-map.nodes[node].x,b.y-map.nodes[node].y)-Math.hypot(a.x-map.nodes[node].x,a.y-map.nodes[node].y))[0];u.position={x:post.x,y:post.y};r.occ[node].add(u);
 r.planted=true;r.spikeLeft=seconds;r.plantSite='A';r.spike={carrier:null,node,position:{x:map.nodes[node].x,y:map.nodes[node].y}};return {r,u,atk,def,events};
}
for(const id of registry.ids)test(id+' cleared site reaches the fixed spike and performs a timed defuse',()=>{const {r,events}=planted(id),position={...r.spike.position},result=r.run();assert.equal(result.reason,'defuse');const start=events.find(e=>e.type==='defuse_start'),end=events.find(e=>e.type==='defuse');assert(start&&end);assert(Math.hypot(start.x-position.x,start.y-position.y)<=10);assert(end.t-start.t>=7);});
test('Ascent v5 new behavior also follows wall corners to a real seven-second defuse',()=>{const {r,events}=planted('ascent');assert.equal(r.run().reason,'defuse');assert(events.find(e=>e.type==='defuse').t-events.find(e=>e.type==='defuse_start').t>=7);});
test('objective move records do not depend on rich-node metadata already held in route caches',()=>{const {r,u,events}=planted('breeze');r.map.geometry.route(u.position,r.map.nodes[u.node],{doors:r.doors});r.moveToPosition(u,{x:r.map.nodes[u.node].x,y:r.map.nodes[u.node].y});const event=events.filter(e=>e.type==='move').at(-1);assert(event);for(const p of event.route)assert.deepEqual(Object.keys(p).sort(),['x','y']);});
test('the planted spike does not move or drop when its former carrier dies',()=>{const {r,atk,def,events}=planted();const carrier=atk[0];carrier.alive=true;carrier.isCarrier=true;carrier.node=r.map.siteNode('A');carrier.position={...r.spike.position};r.spike.carrier=carrier;r.planted=false;carrier.planting=.25;r.updatePlantDefuse();const fixed={...r.spike.position};carrier.position={...r.map.nodes.a_lobby};r.applyKill(def[0],carrier);assert.deepEqual(r.spike.position,fixed);assert.equal(events.filter(e=>e.type==='spike_drop').length,0);assert.equal(carrier.isCarrier,false);});
test('a saved defender returns to the cleared spike when time remains',()=>{const {r,u,events}=planted();u.saved=true;assert.equal(r.run().reason,'defuse');assert(events.some(e=>e.type==='save_cancel'));});
test('a saved defender outside the site cancels its retreat and travels back before defusing',()=>{const {r,u,events}=planted('lotus',45),old=u.node,node=r.map.data.staging.A;r.occ[old].delete(u);u.node=node;u.position={x:r.map.nodes[node].x,y:r.map.nodes[node].y};r.occ[node].add(u);u.saved=true;assert.equal(r.run().reason,'defuse');assert(events.some(e=>e.type==='move'&&e.to===old));});
test('cleared-site urgency uses the physical shortest route without stopping at combat stances',()=>{const {r,u}=planted(),old=u.node,node='a_top';r.occ[old].delete(u);u.node=node;u.position={x:r.map.nodes[node].x,y:r.map.nodes[node].y};r.occ[node].add(u);const route=r.map.geometry.route(u.position,r.spike.position,{doors:r.doors}),travel=route.slice(1).reduce((s,p,i)=>s+Math.hypot(p.x-route[i].x,p.y-route[i].y),0)/32;r.spikeLeft=travel+8.5;assert.equal(r.run().reason,'defuse');});
test('a second defender protects the active defuser instead of starting another defuse',()=>{const {r,u,def,events}=planted();r.flags.siteCleared=true;u.position={...r.spike.position};r.execAction(u,{action:'defuse'});const other=def[1];other.alive=true;other.node=u.node;other.position={...u.position};const c=r.defCandidates(other);assert(c[0].guardSpike);r.execAction(other,c[0]);assert.equal(events.filter(e=>e.type==='defuse_start').length,1);assert.equal(other.defusing,0);});
test('a lingering molly still prevents an immediate defuse even after elimination',()=>{const {r,u,events}=planted();r.mollyZone={node:u.node,deny:true,until:3};r.flags.siteCleared=true;r.execAction(u,r.defCandidates(u)[0]);assert.equal(u.defusing,0);assert(!events.some(e=>e.type==='defuse_start'));assert.equal(r.run().reason,'defuse');});
test('clearing the attackers with less than seven seconds does not award a free defuse',()=>{const {r,events}=planted('lotus',5);assert.equal(r.run().reason,'explosion');assert(!events.some(e=>e.type==='defuse'));});
