// UI-only collection shell. Session state contains filters and scroll positions only.
(() => {
 const $=id=>document.getElementById(id),app=$('mobile-app'),content=$('page-content'),scroll=$('mobile-scroll'),packHost=$('pack-host');
 const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const asset=s=>'../../../素材库/'+encodeURI(s),key=p=>p.name+'-'+p.tier;
 const cards=[...VISUAL_PLAYERS,...PACK_EXTRA,cardSampleDiamond(),...COLLECTION_EXTRA];
 const regions={CN:'中国',AMER:'美洲',EMEA:'欧洲中东非',PAC:'太平洋'};
 const icons={home:'<path d="m3 10 9-7 9 7v10H3zM9 20v-7h6v7"/>',players:'<circle cx="9" cy="7" r="3"/><path d="M3 21v-4a6 6 0 0 1 12 0v4M17 4a3 3 0 0 1 0 6M18 13a5 5 0 0 1 3 4v4"/>',album:'<rect x="8" y="3" width="12" height="17" rx="3"/><path d="m5 6-2 1 2 14a2 2 0 0 0 2 1l8-1M12 8h4M12 12h4"/>'};
 const navMarkup=active=>[['home','俱乐部'],['players','选手'],['album','卡册']].map(([view,label])=>`<a href="#${view}" ${active===view?'aria-current="page"':''}><svg viewBox="0 0 24 24" aria-hidden="true">${icons[view]}</svg>${label}</a>`).join('');
 const defaults={query:'',playerQuery:'',tier:'all',region:'all',sort:'default',positions:{}};
 let state={...defaults},route='',draft,packReady=false,packRequest,packApi;
 try{const saved=JSON.parse(sessionStorage.getItem('vm-visual-collection')||'null');if(saved){state.query=typeof saved.query==='string'?saved.query:'';state.playerQuery=typeof saved.playerQuery==='string'?saved.playerQuery:'';for(const [field,allowed] of Object.entries({tier:['all','铜','银','金','钻'],region:['all',...Object.keys(regions)],sort:['default','rating','name']}))if(allowed.includes(saved[field]))state[field]=saved[field];state.positions=saved.positions&&typeof saved.positions==='object'?saved.positions:{}}}catch{}
 function save(){try{sessionStorage.setItem('vm-visual-collection',JSON.stringify(state))}catch{}}
 function remember(){if(route&&route!=='pack'){state.positions[route]=scroll.scrollTop;save()}}
 scroll.addEventListener('scroll',remember,{passive:true});
 function filtered(filters=state){const q=state.query.trim().toLowerCase();let result=cards.filter(p=>(filters.tier==='all'||p.tier===filters.tier)&&(filters.region==='all'||p.region===filters.region)&&(!q||p.name.toLowerCase().includes(q)||p.team.toLowerCase().includes(q)));if(filters.sort==='rating')result.sort((a,b)=>b.rating-a.rating);if(filters.sort==='name')result.sort((a,b)=>a.name.localeCompare(b.name));return result}
 function tile(p){return `<a class="album-tile" data-tier="${p.tier}" data-card-key="${esc(key(p))}" href="#card/${encodeURIComponent(key(p))}" aria-label="${esc(p.name)}，${p.tier}卡，能力 ${p.rating}"><div class="tile-image"><img src="${asset(p.photo||'选手半身像/'+p.name+'.png')}" alt="" draggable="false"><span class="tile-rating">${p.rating}</span></div><div class="tile-info"><strong>${esc(p.name)}</strong><div class="tile-meta"><span>${esc(p.team)} · ${p.region}</span><span class="tile-tier">${p.tier}卡</span></div>${p.tier==='钻'?'<span class="tile-edition">2023 · 东京大师赛</span>':''}</div></a>`}
 const search=(value,placeholder)=>`<label class="album-search"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="10" cy="10" r="6"/><path d="m15 15 5 5"/></svg><input id="collection-query" type="search" value="${esc(value)}" placeholder="${placeholder}" aria-label="${placeholder}" autocomplete="off"><button class="clear-search" type="button" id="clear-collection-query" aria-label="清除搜索" ${value?'':'hidden'}>×</button></label>`;
 function album(){content.innerHTML=`<div class="album-top"><div class="album-summary"><h2>我的卡册</h2><small>${cards.length} 张</small></div>${search(state.query,'搜索选手或队伍')}<div class="album-tools"><span id="visible-count"></span><button class="soft-button filter-key" id="collection-filter">筛选与排序</button></div><div class="filter-tags" id="active-filters"></div></div><div id="album-results"></div>`;updateAlbum();bindSearch(false);$('collection-filter').onclick=openFilters}
 function updateAlbum(){const result=filtered();$('visible-count').textContent=`显示 ${result.length} 张`;const tags=[];if(state.tier!=='all')tags.push(['tier',state.tier+'卡']);if(state.region!=='all')tags.push(['region',regions[state.region]]);if(state.sort!=='default')tags.push(['sort',state.sort==='rating'?'能力优先':'姓名排序']);$('active-filters').innerHTML=tags.map(([field,label])=>`<button data-clear-filter="${field}" aria-label="移除${label}">${label} ×</button>`).join('');$('collection-filter').innerHTML='筛选与排序'+(tags.length?` <b>${tags.length}</b>`:'');$('album-results').innerHTML=result.length?`<div class="album-grid">${result.map(tile).join('')}</div>`:'<div class="empty-list"><span aria-hidden="true">⌕</span><h2>无匹配卡牌</h2><p>调整搜索或筛选条件</p><button class="soft-button" id="clear-all-filters">清除条件</button></div>';if($('clear-all-filters'))$('clear-all-filters').onclick=()=>{state.query='';state.tier='all';state.region='all';state.sort='default';save();album()};$('active-filters').querySelectorAll('button').forEach(b=>b.onclick=()=>{state[b.dataset.clearFilter]=b.dataset.clearFilter==='sort'?'default':'all';save();updateAlbum()})}
 function bindSearch(isPlayers){const field=isPlayers?'playerQuery':'query';$('collection-query').oninput=e=>{state[field]=e.target.value;$('clear-collection-query').hidden=!e.target.value;save();if(isPlayers)updatePlayers();else updateAlbum()};$('clear-collection-query').onclick=()=>{state[field]='';$('collection-query').value='';$('clear-collection-query').hidden=true;if(isPlayers)updatePlayers();else updateAlbum();save();$('collection-query').focus()}}
 function playersPage(){content.innerHTML=`<div class="album-top"><div class="album-summary"><h2>选手名单</h2><small>${VISUAL_PLAYERS.length} 位</small></div>${search(state.playerQuery,'搜索选手')}</div><div id="players-results"></div>`;updatePlayers();bindSearch(true)}
 function updatePlayers(){const q=state.playerQuery.toLowerCase().trim(),list=VISUAL_PLAYERS.filter(p=>p.name.toLowerCase().includes(q));$('players-results').innerHTML=list.length?`<div class="players-list">${list.map(p=>`<a class="roster-link" href="#card/${encodeURIComponent(key(p))}"><img src="${asset('选手半身像/'+p.name+'.png')}" alt=""><span><strong>${esc(p.name)}</strong><small>${p.agents.slice(0,2).map(esc).join(' / ')}</small></span><b>${p.rating}</b></a>`).join('')}</div>`:'<div class="empty-list"><h2>无匹配选手</h2><p>试试其他姓名</p></div>'}
 function home(){content.innerHTML=`<div class="home-body"><div class="album-summary"><h2>我的俱乐部</h2><small>EDG · CN</small></div><div class="club-hero"><img src="${asset('选手半身像/CHICHOO.png')}" alt="CHICHOO"><img src="${asset('选手半身像/ZmjjKK.png')}" alt="ZmjjKK"><span>EDG</span></div><div class="home-metrics"><div><small>选手</small><b>${VISUAL_PLAYERS.length}</b></div><div><small>平均能力</small><b>${(VISUAL_PLAYERS.reduce((a,p)=>a+p.rating,0)/VISUAL_PLAYERS.length).toFixed(1)}</b></div><div><small>卡册</small><b>${cards.length}</b></div></div><a class="blue-button home-main" href="#players">查看选手 →</a><div class="home-links"><a class="soft-button" href="#album">我的卡册<small>${cards.length} 张</small></a><a class="soft-button" href="#pack">开包<small>中国赛区</small></a></div></div>`}
 function detail(p){const versions=cards.filter(c=>c.name===p.name);content.innerHTML=`<div class="detail-body"><div class="detail-meta"><div><h2>${esc(p.name)}</h2><p>${esc(p.team)} · ${regions[p.region]}</p></div><span>${p.tier}卡</span></div><div class="detail-card-bed">${renderCollectible(p)}</div>${versions.length>1?`<div class="edition-switch">${versions.map(v=>`<a href="#card/${encodeURIComponent(key(v))}" data-edition-nav class="${v===p?'active':''}" ${v===p?'aria-current="true"':''}>${v.tier==='钻'?'东京 · 珍藏':'常规卡面'}</a>`).join('')}</div>`:''}<section class="detail-section"><h3>能力</h3>${[['枪法','AIM'],['协同','SYN'],['意识','SEN']].map(([label,k])=>`<div class="stat-line"><span>${label}</span><div class="stat-track"><i style="width:${p[k]}%"></i></div><b>${p[k]}</b></div>`).join('')}</section><section class="detail-section"><h3>擅长特工</h3><div class="detail-agents">${p.agents.slice(0,3).map(a=>`<span><img src="${asset(p.agentAssets?.[a]||'英雄头像/'+a+'.png')}" alt="">${esc(a)}</span>`).join('')}</div></section></div>`}
 const sheet=$('album-filters');
 function syncDraft(){const groups={tier:[['all','全部'],['铜','铜卡'],['银','银卡'],['金','金卡'],['钻','钻卡']],region:[['all','全部'],...Object.entries(regions)],sort:[['default','默认'],['rating','能力优先'],['name','姓名']]};for(const [field,options]of Object.entries(groups))$(field+'-options').innerHTML=options.map(([value,label])=>`<button type="button" data-field="${field}" data-value="${value}" aria-pressed="${draft[field]===value}">${label}</button>`).join('');$('apply-filters').textContent=`显示 ${filtered({...state,...draft}).length} 张`}
 function openFilters(){draft={tier:state.tier,region:state.region,sort:state.sort};syncDraft();sheet.showModal()}
 sheet.addEventListener('click',e=>{const b=e.target.closest('[data-field]');if(b){draft[b.dataset.field]=b.dataset.value;syncDraft();sheet.querySelector(`[data-field="${b.dataset.field}"][data-value="${b.dataset.value}"]`).focus()}if(e.target===sheet){const r=sheet.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)sheet.close()}});
 $('reset-draft').onclick=()=>{draft={tier:'all',region:'all',sort:'default'};syncDraft()};$('apply-filters').onclick=()=>{Object.assign(state,draft);state.positions.album=0;save();sheet.close();updateAlbum();scroll.scrollTop=0;$('collection-filter').focus()};
 async function ensurePack(){if(packReady)return;if(packRequest)return packRequest;packRequest=(async()=>{const response=await fetch('pack.html');if(!response.ok)throw Error('pack load failed');const doc=new DOMParser().parseFromString(await response.text(),'text/html');packHost.replaceChildren(...['.pack-phone','#result-dialog','#live-status'].map(s=>doc.querySelector(s)));const footer=packHost.querySelector('.pack-bottom');footer.innerHTML='<nav class="mobile-nav" aria-label="主导航">'+navMarkup('album')+'</nav>';packHost.querySelector('.pack-header>a').href='#album';packApi=window.mountPack(packHost,{onExit:()=>go('album'),onInspect:p=>go('card/'+encodeURIComponent(key(p)))});packReady=true})().catch(()=>{packRequest=null;packHost.innerHTML='<div class="empty-list"><h2>暂时无法加载开包</h2><button class="soft-button" id="retry-pack">重试</button><p><a href="#album">返回卡册</a></p></div>';$('retry-pack').onclick=()=>ensurePack()});return packRequest}
 function go(next,{replace=false}={}){if(next===route)return;if(next==='pack'&&!route.startsWith('card/'))packApi?.reset();remember();const from=route;history[replace?'replaceState':'pushState'](replace?history.state:{vm:true,from},'','#'+next);renderRoute()}
 function renderRoute(){
  if(sheet.open)sheet.close();route=location.hash.slice(1)||'album';const isDetail=route.startsWith('card/');let p;if(isDetail){try{p=cards.find(c=>key(c)===decodeURIComponent(route.slice(5)))}catch{}if(!p){route='album';history.replaceState({vm:true},'','#album')}}
  if(!['home','players','album','pack'].includes(route)&&!p){route='album';history.replaceState({vm:true},'','#album')}
  app.classList.toggle('in-pack',route==='pack');content.hidden=route==='pack';packHost.hidden=route!=='pack';$('page-back').hidden=!p;$('page-mark').hidden=!!p;$('header-pack').hidden=!!p;$('page-title').textContent=p?'选手卡':({home:'俱乐部',players:'选手',album:'卡册',pack:'开包'}[route]);$('mobile-nav').innerHTML=navMarkup(p?(history.state?.from==='players'?'players':'album'):route);
  if(route==='pack')ensurePack();else{if(p)detail(p);else if(route==='home')home();else if(route==='players')playersPage();else album();scroll.scrollTop=Number(state.positions[route])||0}
 }
 $('page-back').onclick=()=>{if(history.state?.vm&&history.state.from)history.back();else go('album',{replace:true})};
 document.addEventListener('click',e=>{const a=e.target.closest('a[href^="#"]');if(!a||e.ctrlKey||e.metaKey||e.shiftKey||e.altKey)return;e.preventDefault();const next=a.getAttribute('href').slice(1);go(next,{replace:a.hasAttribute('data-edition-nav')})});
 window.addEventListener('popstate',()=>{remember();renderRoute()});window.addEventListener('pagehide',remember);
 if(!history.state?.vm)history.replaceState({vm:true},'','#'+(location.hash.slice(1)||'album'));renderRoute();
})();
