// Presentation-only components; no game state or persistence.
(() => {
 const inApp=typeof players!=='undefined' && document.getElementById('player-list');
 const state={tier:'all',sort:'default',query:''};
 let draft={...state};let focusOrigin;
 const icon='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 6h16M7 12h10M10 18h4"/></svg>';
 document.body.insertAdjacentHTML('beforeend',`<dialog id="filter-sheet" class="ui-sheet" aria-labelledby="filter-title"><div class="sheet-grip"></div><div class="sheet-top"><div><h2 id="filter-title">筛选选手</h2></div><button class="sheet-close" data-sheet-close aria-label="关闭筛选">×</button></div><fieldset class="filter-group"><legend>卡牌品质</legend><div class="choice-grid" data-choice-group="tier"><button class="choice-key" data-value="all" aria-pressed="true">全部</button><button class="choice-key" data-value="金" aria-pressed="false">金卡</button><button class="choice-key" data-value="银" aria-pressed="false">银卡</button><button class="choice-key" data-value="铜" aria-pressed="false">铜卡</button></div></fieldset><fieldset class="filter-group"><legend>显示顺序</legend><div class="choice-grid two" data-choice-group="sort"><button class="choice-key" data-value="default" aria-pressed="true">默认顺序</button><button class="choice-key" data-value="rating" aria-pressed="false">能力优先</button></div></fieldset><div class="sheet-actions"><button class="secondary-button" id="filter-reset">重置</button><button class="primary-button" id="filter-apply">显示全部选手</button></div></dialog><dialog id="confirm-sheet" class="ui-sheet" aria-labelledby="confirm-title"><div class="sheet-grip"></div><div class="confirm-body"><div class="confirm-symbol" aria-hidden="true">↺</div><h2 id="confirm-title">恢复默认显示？</h2><p>清除筛选和排序。</p></div><div class="confirm-actions"><button class="secondary-button" data-confirm-cancel>取消</button><button class="primary-button" id="confirm-reset">恢复默认</button></div></dialog>`);
 const sheet=document.getElementById('filter-sheet'),confirm=document.getElementById('confirm-sheet');
 const searchMatches=p=>!state.query||p.name.toLowerCase().includes(state.query)||p.agents.some(a=>a.includes(state.query));
 function count(tier){return inApp?players.filter(p=>(tier==='all'||p.tier===tier)&&searchMatches(p)).length:({all:5,金:3,银:1,铜:1}[tier]);}
 function syncDraft(){sheet.querySelectorAll('[data-choice-group]').forEach(group=>group.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.value===draft[group.dataset.choiceGroup]))));document.getElementById('filter-apply').textContent=`显示 ${count(draft.tier)} 位选手`;}
 function openSheet(dialog){focusOrigin=document.activeElement;dialog.showModal();}
 function openFilter(){draft={...state};syncDraft();openSheet(sheet);}
 [sheet,confirm].forEach(d=>{d.addEventListener('close',()=>focusOrigin?.focus({preventScroll:true}));d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}});});
 function decorate(){if(!inApp)return;const list=document.getElementById('player-list');let visible=0;list.querySelectorAll('.player-row').forEach(row=>{const p=players.find(p=>p.name===row.dataset.player);row.dataset.tier=p.tier;row.hidden=!(searchMatches(p)&&(state.tier==='all'||p.tier===state.tier));if(!row.hidden)visible++;row.classList.toggle('is-selected',row.dataset.player===selectedPlayer.name);row.setAttribute('aria-current',row.dataset.player===selectedPlayer.name?'true':'false');row.querySelector('.selection-tick')?.remove();if(row.dataset.player===selectedPlayer.name)row.insertAdjacentHTML('beforeend','<span class="selection-tick" aria-hidden="true">✓</span>');});document.getElementById('filter-empty').hidden=visible!==0;document.querySelector('.list-column-head>span').textContent=`选手 / ${visible} 位`;const filter=document.getElementById('open-filter');filter.classList.toggle('active',state.tier!=='all');filter.innerHTML=icon+'筛选'+(state.tier!=='all'?'<span class="filter-count">1</span>':'');}
 function resetAll(){state.tier='all';state.query='';state.sort='default';if(inApp){sorted=false;document.getElementById('roster-query').value='';document.getElementById('clear-query').hidden=true;document.getElementById('sort-button').innerHTML='默认顺序 <svg><use href="#sort"/></svg>';renderPlayers();}else flash('已恢复默认显示');}
 if(inApp){
  document.querySelector('.roster-tools').insertAdjacentHTML('beforebegin','<label class="roster-search"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="10" cy="10" r="6"/><path d="m15 15 5 5"/></svg><input id="roster-query" type="search" placeholder="搜索选手或特工" aria-label="搜索选手或特工" autocomplete="off"><button id="clear-query" type="button" aria-label="清除搜索" hidden>×</button></label>');
  document.querySelector('.roster-tools').insertAdjacentHTML('beforeend',`<button class="filter-button" id="open-filter">${icon}筛选</button>`);
  document.getElementById('player-list').insertAdjacentHTML('afterend','<div class="ui-empty" id="filter-empty" hidden><div class="empty-icon" aria-hidden="true">⌕</div><h3>无匹配选手</h3><p>试试其他姓名、特工或卡牌品质。</p><button class="secondary-button" data-reset-all>清除筛选</button></div>');
  const original=renderPlayers;renderPlayers=function(){original();decorate();};decorate();
  document.getElementById('roster-query').addEventListener('input',e=>{state.query=e.target.value.trim().toLowerCase();document.getElementById('clear-query').hidden=!e.target.value;decorate();});
  document.getElementById('clear-query').addEventListener('click',()=>{state.query='';document.getElementById('roster-query').value='';document.getElementById('clear-query').hidden=true;decorate();document.getElementById('roster-query').focus();});
  document.getElementById('open-filter').addEventListener('click',()=>{state.sort=sorted?'rating':'default';openFilter();});
 }
 sheet.querySelectorAll('[data-choice-group] button').forEach(b=>b.addEventListener('click',()=>{draft[b.parentElement.dataset.choiceGroup]=b.dataset.value;syncDraft();}));
 document.getElementById('filter-reset').addEventListener('click',()=>{draft.tier='all';draft.sort='default';syncDraft();});
 document.getElementById('filter-apply').addEventListener('click',()=>{state.tier=draft.tier;state.sort=draft.sort;if(inApp){sorted=state.sort==='rating';document.getElementById('sort-button').innerHTML=(sorted?'能力优先':'默认顺序')+' <svg><use href="#sort"/></svg>';renderPlayers();}sheet.close();if(!inApp)flash('已应用筛选 · 组件演示');});
 document.getElementById('confirm-reset').addEventListener('click',()=>{resetAll();confirm.close();});
 document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-sheet-close'))sheet.close();if(b.hasAttribute('data-confirm-cancel'))confirm.close();if(b.hasAttribute('data-open-filter'))openFilter();if(b.hasAttribute('data-open-confirm'))openSheet(confirm);if(b.hasAttribute('data-reset-all'))resetAll();if(b.dataset.action==='player')decorate();if(b.hasAttribute('data-toast-demo'))flash('已加入关注 · 演示反馈');});
 let toastTimer;
 function flash(text){let toast=document.getElementById('kit-toast');if(!toast){document.body.insertAdjacentHTML('beforeend','<div id="kit-toast" class="showcase-toast" role="status" hidden></div>');toast=document.getElementById('kit-toast');}toast.textContent=text;toast.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.hidden=true,2200);}
 document.querySelectorAll('[data-busy-demo]').forEach(b=>b.addEventListener('click',()=>{const before=b.innerHTML;b.disabled=true;b.setAttribute('aria-busy','true');b.innerHTML='<span class="spinner" aria-hidden="true"></span> 正在确认';setTimeout(()=>{b.removeAttribute('aria-busy');b.disabled=false;b.innerHTML=before;flash('已确认 · 按钮状态演示');},1000);}));
})();
