const test=require('node:test'),assert=require('node:assert/strict');
const C=require('../career-store'),{load,begin}=require('./helpers/live-ui.cjs');
function state(){const x=load('store-frozen'),b=C.contentBridge(x.DEMO,x.PROTOTYPE_RULES,x.CN_CONTENT),s=begin(x);b.freeze(s);return {x,b,s};}
test('career export preserves frozen card values, staged input and rejects tampering',()=>{const {s}=state(),e=C.pack(s,12),copy=C.unpack(e);assert.deepEqual(copy,JSON.parse(JSON.stringify(s)));e.state.coachName='changed';assert.throws(()=>C.unpack(e),/校验/);});
test('unknown cards or future models never silently disappear or restart',()=>{const {s}=state();s.roster[0]='removed-player-金';assert.throws(()=>C.pack(s),/未知选手/);s.roster=[];s.liveMaps=[{model:'future-model'}];assert.throws(()=>C.pack(s),/不支持/);});
test('content upgrade applies only to next year and maintains historical cards',()=>{const {s}=state(),x=load('new-client'),old=s.contentSnapshot.uiCards[0].AIM;x.CN_CONTENT.cards[0].AIM=1;x.DEMO.cards[0].AIM=1;const b=C.contentBridge(x.DEMO,x.PROTOTYPE_RULES,x.CN_CONTENT);b.bind(s);assert.equal(x.DEMO.cards[0].AIM,old);const historical=JSON.parse(JSON.stringify(s.contentSnapshot.uiCards));s.seasons.push({year:1,cardSnapshot:historical,roster:s.roster});x.PROTOTYPE_RULES.newRun(s,x.CN_CONTENT,x.CN_DRAW,x.Math.random);assert.equal(s.contentSnapshot.uiCards[0].AIM,1);assert.equal(s.seasons[0].cardSnapshot[0].AIM,old);assert.equal(s.packs.length,3);});
test('test store fails closed on production database names',()=>{assert.throws(()=>C.create({databaseName:C.DATABASE,test:true}),/唯一临时/);});
test('a running year rotates exactly two maps from its frozen pool even after a catalog update',()=>{const {x,s}=state(),old=new Set(s.contentSnapshot.mapCatalog.map(m=>m.id)),before=[...s.activeMaps];x.PROTOTYPE_RULES.mapCatalog.push({id:'new-map',name:'新图'});x.PROTOTYPE_RULES.rotate(s,2,x.Math.random);assert.equal(s.activeMaps.length,7);assert(s.activeMaps.every(id=>old.has(id)));assert.equal(s.activeMaps.filter(id=>!before.includes(id)).length,2);assert.equal(s.rotations.at(-1).removed.length,2);});
test('browser map baseline follows the loaded frozen season, not a newer bundled data object',()=>{const {s}=state(),x=load('baseline-upgrade');x.CN_CONTENT.mapSideData.status='verified';x.CN_CONTENT.mapSideData.columnOrder='attack-defense';const b=C.contentBridge(x.DEMO,x.PROTOTYPE_RULES,x.CN_CONTENT);assert(Math.abs(x.MAP_BASELINE.attackRate('ascent')-.463)<1e-12);b.bind(s);assert.equal(x.MAP_BASELINE.attackRate('ascent'),.5);x.PROTOTYPE_RULES.newRun(s,x.CN_CONTENT,x.CN_DRAW,x.Math.random);assert(Math.abs(x.MAP_BASELINE.attackRate('ascent')-.463)<1e-12);});

test('import rejects HTML resource injection and future tournament versions before promotion',()=>{const {s}=state();s.contentSnapshot.uiCards[0].photo='x\" onerror=\"alert(1)';assert.throws(()=>C.pack(s),/展示字符/);s.contentSnapshot.uiCards[0].photo='选手半身像/test.png';s.seasonEngine.version='future-rules';assert.throws(()=>C.pack(s),/赛制版本/);});
