const test=require('node:test'),assert=require('node:assert/strict'),C=require('../commentary');
test('a committed retake flank is announced once without showing future kills',()=>{const events=[{type:'retake_route',t:20,unitId:'B:0',unit:'b',site:'A'},{type:'retake_route',t:21,unitId:'B:0',unit:'b',site:'A'},{type:'kill',t:26,killer:'b',killerId:'B:0',victim:'a',victimId:'A:0'}],lines=C.timeline({round:1,events},{nodes:{}});assert.equal(C.at(lines,19).length,0);assert.equal(C.at(lines,25).length,1);assert(C.at(lines,25)[0].text.includes('侧翼加入 A 点回防'));assert(!C.at(lines,25).some(l=>l.kind==='kill'));});
test('commentary reports key tactics, kills, support and doors without exposing future outcomes',()=>{
 const record={round:1,events:[{type:'round_meta',t:-1,atkTeam:'A',defTeam:'B',atkFamily:'fake',defFamily:'hold'},{type:'round_start',t:0,units:[{id:'A:0',side:'atk'},{id:'B:0',side:'def'}]},{type:'door',t:4,unit:'a',name:'市场机械门',state:'closed'},{type:'support_call',t:6,unit:'b',site:'B',reason:'casualty'},{type:'kill',t:10,killer:'a',killerId:'A:0',victim:'b',victimId:'B:0'},{type:'star_moment',t:11,unit:'a',name:'降维打击'},{type:'round_end',t:20,winner:'atk',reason:'elimination'}]},lines=C.timeline(record,{nodes:{}});
 assert(C.at(lines,0).every(e=>e.kind==='tactic'));assert(!C.at(lines,9).some(e=>e.kind==='kill'||e.kind==='result'));assert(C.at(lines,10).some(e=>e.text.includes('首杀')));assert(C.at(lines,11).some(e=>e.kind==='star'));assert.equal(JSON.stringify(lines),JSON.stringify(C.timeline(record,{nodes:{}})));
});
test('routine contacts, skill casts, blocked routes and gold traits stay out of commentary',()=>{const events=['contact','smoke','move_stop','door_operation','card_trait','plant_start','support_call','fake_noise'].map((type,i)=>({type,t:i+1,unit:'a',unitId:'A:0',site:'B',reason:'blocked-door-or-wall',name:'首杀机器'}));assert.deepEqual(C.timeline({round:1,events},{nodes:{}}),[]);});
test('repeated support and defuse events are coalesced and successful defuse has one result',()=>{const events=[{type:'support_move',t:1,unit:'a',site:'B'},{type:'support_move',t:2,unit:'b',site:'B'},{type:'defuse_start',t:10,unit:'a'},{type:'defuse_start',t:11,unit:'a'},{type:'defuse',t:17,unit:'a'},{type:'round_end',t:17,reason:'defuse',winner:'def'}],lines=C.timeline({round:1,events},{nodes:{}});assert.equal(lines.length,3);assert.equal(C.at(lines,10).length,2);assert.equal(lines.filter(e=>e.kind==='result').length,1);});
test('mirror rosters are distinguished by team and revival updates the announced alive count',()=>{const record={round:1,events:[{type:'round_meta',t:-1,atkTeam:'EDG',defTeam:'TYL',atkFamily:'rush',defFamily:'hold'},{type:'round_start',t:0,units:[{id:'A:0',side:'atk',name:'same'},{id:'B:0',side:'def',name:'same'}]},{type:'kill',t:1,killerId:'A:0',killer:'same',victimId:'B:0',victim:'same'},{type:'ability',t:2,archetype:'revive',done:true,unitId:'B:0'},{type:'kill',t:3,killerId:'B:0',killer:'same',victimId:'A:0',victim:'same'}]},lines=C.timeline(record,{nodes:{}});assert(lines.some(e=>e.text.includes('EDG的same 击杀 TYL的same')));assert(lines.some(e=>e.text.includes('重新回到场上')));assert(lines.at(-1).text.includes('0 名进攻、1 名防守'));});
test('commentary distinguishes destroyed objects and omits automatic proximity door chatter',()=>{
 const events=[{type:'door',t:1,doorId:'auto',unit:'a',name:'感应门',state:'open'},{type:'door',t:2,doorId:'break',unit:'b',name:'市场门',state:'destroyed'},{type:'door',t:3,doorId:'drop',unit:'c',name:'落墙',state:'closed'}];
 const lines=C.timeline({round:1,events},{doorDefinitions:[{id:'auto',kind:'proximity'},{id:'break',kind:'breakable'},{id:'drop',kind:'drop-wall'}]});
 assert.equal(lines.length,2);assert.equal(lines[0].text,'b 击碎市场门。');assert.equal(lines[1].text,'c 关闭落墙。');assert.equal(C.at(lines,1).length,0);
});
test('eliminated attackers with only four seconds left are explained without claiming a surviving postplant hold',()=>{const events=[{type:'round_start',t:0,units:[{id:'A:0',side:'atk'},{id:'B:0',side:'def'}]},{type:'plant',t:48,unit:'a',site:'A',spikeTicks:45},{type:'kill',t:89,killerId:'B:0',killer:'b',victimId:'A:0',victim:'a'},{type:'site_cleared',t:89,site:'A'},{type:'round_end',t:93,reason:'explosion',winner:'atk'}],lines=C.timeline({round:1,events},{roundRules:{defuseTicks:7}});assert(lines.some(e=>e.text.includes('4.0 秒，来不及完成拆包')));assert.equal(lines.at(-1).text,'拆包时间耗尽，爆能器引爆。');assert(!C.at(lines,88).some(e=>e.text.includes('来不及')));});
test('checkpoint commentary preserves partial progress and does not call four remaining seconds impossible',()=>{const events=[{type:'round_start',t:0,units:[{id:'B:0',name:'b',side:'def'}]},{type:'plant',t:0,site:'A',spikeTicks:45},{type:'defuse_start',t:10,unit:'b',unitId:'B:0',seconds:7},{type:'defuse_checkpoint',t:13.5,unit:'b',unitId:'B:0',seconds:3.5},{type:'defuse_abort',t:14,unit:'b'},{type:'site_cleared',t:41,site:'A'},{type:'defuse_start',t:41,unit:'b',unitId:'B:0',seconds:3.5}],lines=C.timeline({round:1,events},{roundRules:{defuseTicks:7}});assert(lines.some(e=>e.text.includes('拆包已过半')));assert(lines.some(e=>e.text.includes('中断拆包')));assert(lines.some(e=>e.text.includes('接着完成剩余拆包')));assert(!lines.some(e=>e.text.includes('来不及')));assert(!C.at(lines,13).some(e=>e.text.includes('过半')));});
