const {test}=require('node:test'),assert=require('node:assert/strict'),G=require('../progression');
const cards=Array.from({length:6},(_,i)=>({name:'P'+i,playerId:'p'+i,tier:'银',team:i<3?'A':'B'}));
function state(){return G.ensure({year:1,phase:1,roster:cards.slice(0,5).map(G.key),team:{羁绊:20,状态:50,熟练:50},coach:{战术:50,临场:50,声望:50},stageRecords:[],mapKnowledge:{ascent:50},seasons:[]},['ascent']);}
const close=(a,b)=>assert(Math.abs(a-b)<1e-9,`${a} != ${b}`);
function map(s,id='m1',win=true){const m={mapId:'ascent',home:win?13:9,away:win?9:13,rounds:Array.from({length:22},(_,i)=>({win:i<(win?13:9),probability:.5}))};G.beginMap(s,m,cards,{expected:.8,plannedExpected:.6,standardExpected:.5,kind:'quick'});return G.settleMap(s,m,cards,id,{quick:true});}
test('round state converges, mastery saturates, and rest never creates free positive state',()=>{const s=state();for(let i=0;i<1000;i++)G.round(s,true,cards);assert(s.team.状态<70.00001);assert(s.team.熟练<100);G.recover(s,'timeout');assert(s.team.状态<=70.00001);for(let i=0;i<1000;i++)G.round(s,false,cards);assert(s.team.状态>29.9999);const before=s.team.状态;G.recover(s,'timeout');assert(s.team.状态>before&&s.team.状态<50);G.recover(s,'map');assert(s.team.状态<50);});
test('map freezes reputation, changes H/M independently and pays once even after JSON restore',()=>{let s=state();const m={mapId:'ascent',home:13,away:9,rounds:[]};G.beginMap(s,m,cards,{expected:.8});s.coach.声望=100;const r=G.settleMap(s,m,cards,'map:1');close(s.mapCoach.ascent,50.4);close(s.mapLineup.ascent,50.75);close(s.mapKnowledge.ascent,50.54);close(s.familiarity.p0,1.25);assert.equal(r.roster.length,5);const prior=JSON.stringify(s);s=JSON.parse(prior);assert.equal(G.settleMap(s,m,cards,'map:1'),null);assert.equal(JSON.stringify(s),prior);});
test('replacement preserves six pairs, affects lineup map mastery only, and new year inherits coach map component',()=>{const s=state();for(let i=0;i<50;i++)G.round(s,true,cards);const retained=G.pair('p0','p1'),value=s.rapport[retained];s.mapCoach.ascent=80;s.mapLineup.ascent=90;s.roster=cards.slice(0,4).concat(cards[5]).map(G.key);G.replace(s,4,cards);close(s.mapCoach.ascent,80);close(s.mapLineup.ascent,82);close(s.rapport[retained],value);assert.equal(s.rapport[G.pair('p0','p5')]||0,0);G.resetYear(s,['ascent']);close(s.mapCoach.ascent,80);close(s.mapLineup.ascent,50);close(s.mapKnowledge.ascent,68);});
test('BO5 and BO3 update coach once from evidence, can decrease, and missing evidence gives no fabricated rating',()=>{const s=state(),r=map(s,'a',false);r.evaluation={tactical:20,clinical:20};G.settleMatch(s,cards,{id:'series:1',kind:'formal',win:false,mapRecords:[r,r,r,r,r]});close(s.coach.战术,49);close(s.coach.临场,49);const once=JSON.stringify(s);G.settleMatch(s,cards,{id:'series:1',mapRecords:[r]});assert.equal(JSON.stringify(s),once);r.evaluation={tactical:null,clinical:null};G.settleMatch(s,cards,{id:'series:2',kind:'quick',win:true,mapRecords:[r]});close(s.coach.战术,49);close(s.coach.临场,49);r.evaluation={tactical:80,clinical:80};G.settleMatch(s,cards,{id:'series:3',kind:'formal',win:true,mapRecords:[r]});close(s.coach.战术,50);close(s.coach.临场,50);});
test('event gains are proportional to actual map attendance, shared across versions, and belong to departed players',()=>{const s=state(),r1=map(s,'m1'),old=s.familiarity.p4;s.roster=cards.slice(0,4).concat(cards[5]).map(G.key);const r2=map(s,'m2');G.settleMatch(s,cards,{id:'match1',kind:'quick',win:true,mapRecords:[r1]});G.settleMatch(s,cards,{id:'match2',kind:'formal',win:true,mapRecords:[r2]});const before={...s.familiarity},event=G.settleEvent(s,{id:'event1',phase:1,rank:1,total:12,played:true,playoffs:true});close(s.familiarity.p0-before.p0,4);close(s.familiarity.p4-old,2);close(s.familiarity.p5-before.p5,2);assert(event.participants.includes(G.key(cards[4])));const snapshot=JSON.stringify(s);G.settleEvent(s,{id:'event1',phase:1,rank:1,total:12,played:true});assert.equal(JSON.stringify(s),snapshot);assert(s.coach.声望<=54);});
test('missing a tournament gives no participation reward and annual reputation update is bounded and idempotent',()=>{const s=state();G.settleEvent(s,{id:'miss',phase:7,rank:999,total:16,played:false});assert.equal(s.coach.声望,50);assert.deepEqual(s.familiarity,{});s.stageRecords=[{phase:1,growth:{evaluation:0}},{phase:7,growth:{evaluation:0}}];G.settleYear(s,'year1');assert.equal(s.coach.声望,46);G.settleYear(s,'year1');assert.equal(s.coach.声望,46);});
test('legacy single map scores migrate without replaying old rewards or resetting earned familiarity',()=>{const s=state();delete s.mapCoach;delete s.mapLineup;delete s.progressionVersion;s.mapKnowledge.ascent=63;s.familiarity.p0=123;G.ensure(s,['ascent']);close(s.mapKnowledge.ascent,63);close(s.familiarity.p0,123);G.ensure(s,['ascent']);close(s.mapKnowledge.ascent,63);assert(G.familiar(123)<100);});
test('unfinished maps and qualification tiebreaks cannot award tournament achievement gains',()=>{const s=state();assert.throws(()=>G.settleMap(s,{mapId:'ascent',home:13,away:12,rounds:[]},cards,'unfinished'),/未完成/);assert.equal(s.familiarity.p0,undefined);const r=map(s,'qualification');G.settleMatch(s,cards,{id:'qual',kind:'quick',win:true,mapRecords:[r]});s.participation[0].eventParticipation=false;const before={...s.familiarity};G.settleEvent(s,{id:'champions',phase:1,rank:1,total:12,played:true});assert.deepEqual(s.familiarity,before);});
test('ordinary and diamond versions accumulate one player familiarity without sharing version honors',()=>{const diamond={...cards[4],tier:'钻',cut:'赛事版本'},pool=[...cards,diamond],s=state(),first=map(s,'normal');G.settleMatch(s,pool,{id:'normal-match',kind:'formal',win:true,mapRecords:[first]});s.roster[4]=G.key(diamond);const m={mapId:'ascent',home:13,away:9,rounds:[]};G.beginMap(s,m,pool);const second=G.settleMap(s,m,pool,'diamond-map');G.settleMatch(s,pool,{id:'diamond-match',kind:'formal',win:true,mapRecords:[second]});const prior=s.familiarity.p4;G.settleEvent(s,{id:'event',phase:1,rank:1,total:12,played:true});close(s.familiarity.p4-prior,4);assert(s.participation[0].cards.includes(G.key(cards[4])));assert(!s.participation[0].cards.includes(G.key(diamond)));assert(s.participation[1].cards.includes(G.key(diamond)));});
