const test=require('node:test'),assert=require('node:assert/strict'),P=require('../round-presentation'),H=require('./helpers/live-ui.cjs'),S=require('../spatial-match');
const map=(number,home,away,prev={home:home-1,away})=>({rounds:[{number:number-1,...prev},{number,home,away,win:true,side:'attack',ownTactic:'爆弹强攻',opponentTactic:'分区控图',reason:'交火取胜'}]});
test('close ordinary scores stay summaries, first pistol/half pistol and genuinely important boundaries are replayed',()=>{assert.equal(P.keyRound(map(15,8,7)),null);assert.equal(P.keyRound(map(23,12,11,{home:12,away:10})),null);assert.equal(P.keyRound(map(1,1,0)),'手枪局');assert.equal(P.keyRound(map(13,7,6)),'手枪局');assert.equal(P.keyRound(map(22,12,10)),'首次赛点');assert.equal(P.keyRound(map(25,13,12)),'加时');assert.equal(P.keyRound(map(20,13,7)),'决胜回合');});
test('winning clutches use actual events without changing the committed replay',()=>{const m=map(18,9,9);m.replay={events:[{type:'round_start',units:[{id:'a',side:'atk',alive:true},{id:'b',side:'def',alive:true},{id:'c',side:'def',alive:true}]},{type:'kill',killerId:'a',victimId:'b'},{type:'kill',killerId:'a',victimId:'c'},{type:'round_end',winner:'atk',reason:'elimination'}]};const before=JSON.stringify(m);assert.equal(P.keyRound(m),'残局逆转');assert.equal(JSON.stringify(m),before);m.replay.events.at(-1).winner='def';assert.equal(P.keyRound(m),null);});
test('skips are scoped to a unique year/match/map/round and fast-forward never mounts a replay',()=>{const s={year:1,matchToken:'m',map:0,liveMaps:[{...map(13,7,6),spatial:{}}]};assert.equal(P.mode(s).replay,true);s.skippedReplay=P.token(s);assert.equal(P.mode(s).replay,false);s.year=2;assert.equal(P.mode(s).replay,true);s.fastForward=true;assert.equal(P.mode(s).replay,false);});
test('summary retains the site and objective result without detailed gunfire commentary',()=>{const m=map(6,4,2);m.replay={events:[{type:'plant',unit:'甲',site:'B'},{type:'defuse',unit:'乙'},{type:'round_end',reason:'defuse'}]};assert.deepEqual(P.brief(m),{headline:'回防拆包',facts:['甲 在 B 点下包','乙 完成拆包']});});
test('next-round skips animation and commits exactly one fine round; shared windows block it and JSON continuation is deterministic',()=>{
 const x=H.load('presentation-next',{spatial:true}),R=x.PROTOTYPE_RULES;x.SPATIAL_MATCH=S;const s=H.begin(x);H.veto(x,s);s.run='match';s.agents[0]=Object.fromEntries(s.roster.map((k,i)=>[k,x.AGENT_SELECTION.recommend(x.FLOW_UI.lineup(s),x.CN_CONTENT.agents,R.mapsFor(s)[0]).agents[i]]));R.startMap(s);s.playing=true;assert(P.advance(s,R,x.DEMO.cards));assert.equal(s.liveMaps[0].rounds.length,1);assert.equal(s.liveMaps[0].progression.roundsSettled,1);assert.equal(s.playing,false);assert.equal(P.mode(s).replay,false);
 s.coachWindow='half';const before=JSON.stringify(s);assert.equal(P.advance(s,R,x.DEMO.cards),false);assert.equal(JSON.stringify(s),before);s.coachWindow='';const copy=JSON.parse(JSON.stringify(s));assert(P.advance(s,R,x.DEMO.cards));assert(P.advance(copy,R,x.DEMO.cards));assert.equal(JSON.stringify(s.liveMaps),JSON.stringify(copy.liveMaps));assert.equal(JSON.stringify(s.team),JSON.stringify(copy.team));
});
