const test=require('node:test'),assert=require('node:assert/strict');
const S=require('../spatial-match'),O=require('../round-outcome'),{GameMap}=require('../../引擎/gamemap'),{canObserve,recordObservations}=require('../../引擎/observation');
const cards=require('../catalog').cards.filter(c=>c.team==='EDG'&&c.tier!=='钻').slice(0,5),priority={attack:[0,1,2,3,4],defense:[1,0,2,3,4]};
const team=id=>({id,players:cards,team:{羁绊:40,状态:50,熟练:50},coach:{战术:50,临场:50,声望:50},mapKnowledge:{ascent:50}});
const map=new GameMap(S.mapDataV3,require('../../引擎/maps/ascent-geometry-v3.json'));
test('a moving player sees a legitimate visible enemy; invalid geometry never uses node fallback',()=>{const a={id:'A:0',alive:true,side:'atk',position:{x:182,y:620},moving:{to:'a_site'},node:'a_site'},b={id:'B:0',alive:true,side:'def',position:{x:193,y:638},node:'a_site'};assert(canObserve({map},a,b));b.position={x:350,y:450};assert(!canObserve({map},a,b));});
test('team reports have an actual communication delay and keep their observer and freshness',()=>{const a={id:'A:0',name:'a',alive:true,side:'atk',position:{x:182,y:620},node:'a_site',syn:70},b={id:'B:0',name:'b',alive:true,side:'def',position:{x:193,y:638},node:'a_site',syn:70};const r={map,units:[a,b],t:0,emit:()=>{},observations:{atk:{},def:{}}};recordObservations(r);assert.equal(Object.keys(r.observations.atk).length,0);r.t=.5;recordObservations(r);assert.equal(r.observations.atk['B:0'].observerId,'A:0');assert.equal(r.observations.atk['B:0'].lastSeenTick,0);});
test('v3 plays a real map, restores the same frozen journal and keeps all actors on valid floor',()=>{const a=team('A'),b=team('B'),m=O.create('v3-restore','ascent');S.initialize(m,a,b,priority,null,{version:3});for(let i=0;i<3;i++)S.step(m,a,b,priority);const copy=JSON.parse(JSON.stringify(m));for(let i=0;i<3;i++)assert.deepEqual(S.step(m,a,b,priority),S.step(copy,a,b,priority));assert.equal(JSON.stringify(m),JSON.stringify(copy));const record=S.replay(m,2);for(let t=0;t<=record.ticks;t+=.25)for(const u of Object.values(S.frame(record,t).units))assert(map.geometry.contains(u.position),u.name+' at '+t);});
test('batch simulation and visible stepping use one v3 execution path',()=>{const a=team('A'),b=team('B'),fast=S.simulate('v3-parity',a,b,priority),live=O.create('v3-parity','ascent');S.initialize(live,a,b,priority,null,{version:3});while(!live.spatial.boundary?.matchOver)S.step(live,a,b,priority);assert.deepEqual(live.rounds,fast.rounds);assert.equal(live.home,fast.home);assert.equal(live.away,fast.away);});
test('the delivered browser bundle reproduces v3 round events and replay frames exactly',()=>{
 const vm=require('node:vm'),fs=require('node:fs'),path=require('node:path'),ctx={structuredClone};vm.createContext(ctx);vm.runInContext(fs.readFileSync(path.resolve(__dirname,'../../设计文档/UI原型/complete-prototype-01/spatial-engine.js'),'utf8'),ctx);
 const web=ctx.SPATIAL_MATCH,a=team('A'),b=team('B'),direct=O.create('v3-browser-parity','ascent'),browser=O.create('v3-browser-parity','ascent');S.initialize(direct,a,b,priority,null,{version:3});web.initialize(browser,a,b,priority,null,{version:3});
 for(let i=0;i<3;i++){S.step(direct,a,b,priority);web.step(browser,a,b,priority);assert.equal(JSON.stringify(browser.replay),JSON.stringify(direct.replay));for(let t=0;t<=direct.replay.ticks;t+=.5)assert.equal(JSON.stringify(web.frame(browser.replay,t)),JSON.stringify(S.frame(direct.replay,t)));}
});
test('unknown saved rules or layout fail without replacing a saved match',()=>{
 const a=team('A'),b=team('B');for(const [field,value]of [['ruleVersion','future'],['layoutVersion','wrong-map']]){const m=O.create('frozen-version','ascent');S.initialize(m,a,b,priority,null,{version:3});m.spatial.initial[field]=value;const before=JSON.stringify(m);assert.throws(()=>S.step(m,a,b,priority),/版本不匹配/);assert.equal(JSON.stringify(m),before);}
});
