const test=require('node:test'),assert=require('node:assert/strict'),H=require('../team-style'),O=require('../round-outcome'),S=require('../season-2026'),UI=require('./helpers/live-ui.cjs');
const team=id=>({id,players:Array.from({length:5},(_,i)=>({name:id+i,AIM:70,SYN:70,SEN:70})),team:{羁绊:40,状态:50,熟练:50},coach:{战术:50,临场:50,声望:50},mapKnowledge:{ascent:50},tacticalProfile:H.create('test',id,{neutral:true})}),priority={attack:[0,1,2,3,4],defense:[2,0,1,3,4]};
test('a B-side formal result reverses tactics, economy and probability consistently with its score perspective',()=>{const r={home:5,away:2,win:true,side:'attack',ownTactic:'爆弹强攻',opponentTactic:'诱敌设伏',economy:2,probability:.8},b=O.reverseRound(r);assert.equal(b.home,2);assert.equal(b.side,'defense');assert.equal(b.ownTactic,'诱敌设伏');assert.equal(b.economy,-2);assert(Math.abs(b.probability-.2)<1e-12);const a=O.reverseRound(b);assert.equal(a.home,r.home);assert.equal(a.ownTactic,r.ownTactic);assert(Math.abs(a.probability-r.probability)<1e-12);});
test('opponent pauses respond to losses, respect a cooldown and never consume player timeouts',()=>{const x=UI.load('pause-style'),s=UI.begin(x,undefined,false),R=x.PROTOTYPE_RULES;R.register(s,x.DEMO.demoRoster(),x.DEMO.cards);x.SEASON_REVIEW.preparation(s);UI.veto(x,s);s.agents={0:Object.fromEntries(s.roster.map((k,i)=>[k,x.AGENT_SELECTION.recommend(x.FLOW_UI.lineup(s),x.CN_CONTENT.agents,x.FLOW_UI.matchMap(s).id).agents[i]]))};R.startMap(s);const m=s.liveMaps[0];m.home=3;m.away=0;m.rounds=Array.from({length:3},(_,i)=>({number:i+1,win:true,side:'attack',ownTactic:O.names.attack[0]}));s.round=3;assert(R.shouldOpponentTimeout(s));const own=R.timeoutLeft(s);assert(R.chargeTimeout(s,'opponent'));assert.equal(R.timeoutLeft(s),own);s.coachWindow='';assert(!R.shouldOpponentTimeout(s));m.rounds.push({number:4,win:false,side:'attack',ownTactic:O.names.attack[1]});s.round=4;assert(!R.shouldOpponentTimeout(s));});
test('individual map proficiency and the actual selected tactic each change probability independently',()=>{
 function round(change){const a=team('A'),b=team('B');change(a,b);const m=O.create('effects','ascent','attack',{model:H.version});return O.step(m,a,b,priority);}
 const plain=round(()=>{}),map=round(a=>a.mapKnowledge.ascent=90),skill=round(a=>a.tacticalProfile.attack.fill(90));assert(map.probability>plain.probability);assert(skill.probability>plain.probability);
});
test('new numerical maps freeze profiles, map baselines and card values while unknown models reject atomically',()=>{
 const a=team('A'),b=team('B'),m=O.create('frozen','ascent','attack',{model:H.version});O.step(m,a,b,priority);const copy=structuredClone(m),frozen=structuredClone(a);a.players[0].AIM=100;a.mapKnowledge.ascent=100;a.tacticalProfile.attack.fill(100);assert.deepEqual(O.step(m,a,b,priority),O.step(copy,frozen,b,priority));
 const bad=O.create('bad','ascent','attack',{model:'unknown'}),before=JSON.stringify(bad);assert.throws(()=>O.step(bad,a,b,priority),/未知比赛输入/);assert.equal(JSON.stringify(bad),before);
});
test('a damaged running numerical map cannot silently regenerate its frozen inputs',()=>{const a=team('A'),b=team('B'),m=O.create('missing-inputs','ascent','attack',{model:H.version});O.step(m,a,b,priority);delete m.styleInputs;const before=JSON.stringify(m);assert.throws(()=>O.step(m,a,b,priority),/缺少冻结输入/);assert.equal(JSON.stringify(m),before);});
test('a pause counters observed rushes with traps, irrespective of an unplayed future order',()=>{
 const a=team('A'),b=team('B'),m=O.create('read','ascent','attack',{model:H.version});O.step(m,a,b,priority);m.rounds=Array.from({length:6},(_,i)=>({number:i+1,side:'attack',ownTactic:O.names.attack[0],opponentTactic:O.names.defense[0]}));O.adapt(m);assert.equal(m.opponentPriorities.defense[0],2);
 const saved=structuredClone(m);a.tacticPriorities={attack:[2,3,4,1,0],defense:[1,4,3,2,0]};O.adapt(m);assert.deepEqual(m.opponentPriorities,saved.opponentPriorities);
});
test('season previews do not grow styles, committed numerical results grow once even after round details are removed',()=>{
 const x=UI.load('style-season'),ctx=S.create('style-season',x.CN_CONTENT.rosters,x.CN_CONTENT.globalCards,'EDG'),before=JSON.stringify(ctx.teams);S.findFeatured(ctx,0,x.DEMO.maps.map(m=>m.id).slice(0,7));assert.equal(JSON.stringify(ctx.teams),before);
 const node={id:'test-foreign',a:'G2',b:'NRG',bestOf:3},result=S.simulate(ctx,node,['ascent','haven','split','lotus','sunset','breeze','abyss']);assert(result.maps.every(m=>!m.rounds&&m.tacticUsage));S.settleTeamResult(ctx,node,result);const after=JSON.stringify(ctx.teams);assert.notEqual(after,before);S.settleTeamResult(ctx,node,result);assert.equal(JSON.stringify(ctx.teams),after);
});
test('current preparation exposes four labels without private scores; live and quick growth deduplicate after restore',()=>{
 const x=UI.load('style-ui'),s=UI.begin(x),R=x.PROTOTYPE_RULES;const rival=s.seasonEngine.teams.find(t=>t.id===s.opponentId),scout=H.scout(rival.tacticalProfile,rival.mapKnowledge),body=x.FLOW_UI.prepare(s).body;
 const section=body.match(/<section class="opponent-style"[\s\S]*?<\/section>/)[0];for(const label of [...scout.attack,...scout.defense])assert(section.includes(label));assert(!/(?:^|\D)(?:66|58|49|42|35)(?:\D|$)/.test(section));assert(!section.includes('tacticalProfile'));
 UI.veto(x,s);s.agents={0:Object.fromEntries(s.roster.map((k,i)=>[k,x.AGENT_SELECTION.recommend(x.FLOW_UI.lineup(s),x.CN_CONTENT.agents,x.FLOW_UI.matchMap(s).id).agents[i]]))};while(!R.mapOver(s))R.stepRound(s);const copy=JSON.parse(JSON.stringify(s)),after=JSON.stringify(s.tacticalProfile);assert(s.tacticalProfile.settled.includes(s.matchToken+':map:0'));R.settleMap(copy,x.DEMO.cards);assert.equal(JSON.stringify(copy.tacticalProfile),after);assert(x.FLOW_UI.tactics(s).body.includes('tactic-proficiency'));
});
